package model.promotions;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import model.utilisateur.ComptesUtilisateur;

/**
 * CampagnesMarketing generated by hbm2java
 */
public class CampagnesMarketing  implements java.io.Serializable {


     private int id;
     private ComptesUtilisateur comptesUtilisateur;
     private String nom;
     private String description;
     private String typeCampagne;
     private Serializable segmentsCibles;
     private Serializable criteresCiblage;
     private String sujet;
     private String contenuHtml;
     private String contenuTexte;
     private Serializable imagesUrls;
     private Timestamp dateDebut;
     private Timestamp dateFin;
     private String frequenceEnvoi;
     private Integer destinatairesCibles;
     private Integer messagesEnvoyes;
     private Integer messagesDelivres;
     private Integer ouvertures;
     private Integer clics;
     private Integer conversions;
     private BigDecimal budgetAlloue;
     private BigDecimal coutActuel;
     private String statut;
     private Timestamp creeLe;

    public CampagnesMarketing() {
    }

	
    public CampagnesMarketing(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public CampagnesMarketing(int id, ComptesUtilisateur comptesUtilisateur, String nom, String description, String typeCampagne, Serializable segmentsCibles, Serializable criteresCiblage, String sujet, String contenuHtml, String contenuTexte, Serializable imagesUrls, Timestamp dateDebut, Timestamp dateFin, String frequenceEnvoi, Integer destinatairesCibles, Integer messagesEnvoyes, Integer messagesDelivres, Integer ouvertures, Integer clics, Integer conversions, BigDecimal budgetAlloue, BigDecimal coutActuel, String statut, Timestamp creeLe) {
       this.id = id;
       this.comptesUtilisateur = comptesUtilisateur;
       this.nom = nom;
       this.description = description;
       this.typeCampagne = typeCampagne;
       this.segmentsCibles = segmentsCibles;
       this.criteresCiblage = criteresCiblage;
       this.sujet = sujet;
       this.contenuHtml = contenuHtml;
       this.contenuTexte = contenuTexte;
       this.imagesUrls = imagesUrls;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.frequenceEnvoi = frequenceEnvoi;
       this.destinatairesCibles = destinatairesCibles;
       this.messagesEnvoyes = messagesEnvoyes;
       this.messagesDelivres = messagesDelivres;
       this.ouvertures = ouvertures;
       this.clics = clics;
       this.conversions = conversions;
       this.budgetAlloue = budgetAlloue;
       this.coutActuel = coutActuel;
       this.statut = statut;
       this.creeLe = creeLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getTypeCampagne() {
        return this.typeCampagne;
    }
    
    public void setTypeCampagne(String typeCampagne) {
        this.typeCampagne = typeCampagne;
    }
    public Serializable getSegmentsCibles() {
        return this.segmentsCibles;
    }
    
    public void setSegmentsCibles(Serializable segmentsCibles) {
        this.segmentsCibles = segmentsCibles;
    }
    public Serializable getCriteresCiblage() {
        return this.criteresCiblage;
    }
    
    public void setCriteresCiblage(Serializable criteresCiblage) {
        this.criteresCiblage = criteresCiblage;
    }
    public String getSujet() {
        return this.sujet;
    }
    
    public void setSujet(String sujet) {
        this.sujet = sujet;
    }
    public String getContenuHtml() {
        return this.contenuHtml;
    }
    
    public void setContenuHtml(String contenuHtml) {
        this.contenuHtml = contenuHtml;
    }
    public String getContenuTexte() {
        return this.contenuTexte;
    }
    
    public void setContenuTexte(String contenuTexte) {
        this.contenuTexte = contenuTexte;
    }
    public Serializable getImagesUrls() {
        return this.imagesUrls;
    }
    
    public void setImagesUrls(Serializable imagesUrls) {
        this.imagesUrls = imagesUrls;
    }
    public Timestamp getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Timestamp dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Timestamp getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Timestamp dateFin) {
        this.dateFin = dateFin;
    }
    public String getFrequenceEnvoi() {
        return this.frequenceEnvoi;
    }
    
    public void setFrequenceEnvoi(String frequenceEnvoi) {
        this.frequenceEnvoi = frequenceEnvoi;
    }
    public Integer getDestinatairesCibles() {
        return this.destinatairesCibles;
    }
    
    public void setDestinatairesCibles(Integer destinatairesCibles) {
        this.destinatairesCibles = destinatairesCibles;
    }
    public Integer getMessagesEnvoyes() {
        return this.messagesEnvoyes;
    }
    
    public void setMessagesEnvoyes(Integer messagesEnvoyes) {
        this.messagesEnvoyes = messagesEnvoyes;
    }
    public Integer getMessagesDelivres() {
        return this.messagesDelivres;
    }
    
    public void setMessagesDelivres(Integer messagesDelivres) {
        this.messagesDelivres = messagesDelivres;
    }
    public Integer getOuvertures() {
        return this.ouvertures;
    }
    
    public void setOuvertures(Integer ouvertures) {
        this.ouvertures = ouvertures;
    }
    public Integer getClics() {
        return this.clics;
    }
    
    public void setClics(Integer clics) {
        this.clics = clics;
    }
    public Integer getConversions() {
        return this.conversions;
    }
    
    public void setConversions(Integer conversions) {
        this.conversions = conversions;
    }
    public BigDecimal getBudgetAlloue() {
        return this.budgetAlloue;
    }
    
    public void setBudgetAlloue(BigDecimal budgetAlloue) {
        this.budgetAlloue = budgetAlloue;
    }
    public BigDecimal getCoutActuel() {
        return this.coutActuel;
    }
    
    public void setCoutActuel(BigDecimal coutActuel) {
        this.coutActuel = coutActuel;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }




}


