package model.promotions;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import model.utilisateur.ComptesUtilisateur;

/**
 * CodesPromotionnels generated by hbm2java
 */
public class CodesPromotionnels  implements java.io.Serializable {


     private int id;
     private ComptesUtilisateur comptesUtilisateur;
     private String code;
     private String nom;
     private String description;
     private String typeRemise;
     private BigDecimal valeurRemise;
     private BigDecimal montantMaximum;
     private BigDecimal montantMinimumCommande;
     private Serializable produitsEligibles;
     private Serializable categoriesEligibles;
     private Serializable boutiquesEligibles;
     private Integer utilisationMaxGlobale;
     private Integer utilisationMaxParClient;
     private Integer utilisationActuelle;
     private Timestamp dateDebut;
     private Timestamp dateFin;
     private Serializable segmentsClients;
     private Serializable clientsSpecifiques;
     private String campagneMarketing;
     private String canalDistribution;
     private Boolean estActif;
     private Timestamp creeLe;
     private Set utilisationsCodesPromos = new HashSet(0);

    public CodesPromotionnels() {
    }

	
    public CodesPromotionnels(int id, String code, String nom, String typeRemise, BigDecimal valeurRemise, Timestamp dateDebut, Timestamp dateFin) {
        this.id = id;
        this.code = code;
        this.nom = nom;
        this.typeRemise = typeRemise;
        this.valeurRemise = valeurRemise;
        this.dateDebut = dateDebut;
        this.dateFin = dateFin;
    }
    public CodesPromotionnels(int id, ComptesUtilisateur comptesUtilisateur, String code, String nom, String description, String typeRemise, BigDecimal valeurRemise, BigDecimal montantMaximum, BigDecimal montantMinimumCommande, Serializable produitsEligibles, Serializable categoriesEligibles, Serializable boutiquesEligibles, Integer utilisationMaxGlobale, Integer utilisationMaxParClient, Integer utilisationActuelle, Timestamp dateDebut, Timestamp dateFin, Serializable segmentsClients, Serializable clientsSpecifiques, String campagneMarketing, String canalDistribution, Boolean estActif, Timestamp creeLe, Set utilisationsCodesPromos) {
       this.id = id;
       this.comptesUtilisateur = comptesUtilisateur;
       this.code = code;
       this.nom = nom;
       this.description = description;
       this.typeRemise = typeRemise;
       this.valeurRemise = valeurRemise;
       this.montantMaximum = montantMaximum;
       this.montantMinimumCommande = montantMinimumCommande;
       this.produitsEligibles = produitsEligibles;
       this.categoriesEligibles = categoriesEligibles;
       this.boutiquesEligibles = boutiquesEligibles;
       this.utilisationMaxGlobale = utilisationMaxGlobale;
       this.utilisationMaxParClient = utilisationMaxParClient;
       this.utilisationActuelle = utilisationActuelle;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.segmentsClients = segmentsClients;
       this.clientsSpecifiques = clientsSpecifiques;
       this.campagneMarketing = campagneMarketing;
       this.canalDistribution = canalDistribution;
       this.estActif = estActif;
       this.creeLe = creeLe;
       this.utilisationsCodesPromos = utilisationsCodesPromos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getTypeRemise() {
        return this.typeRemise;
    }
    
    public void setTypeRemise(String typeRemise) {
        this.typeRemise = typeRemise;
    }
    public BigDecimal getValeurRemise() {
        return this.valeurRemise;
    }
    
    public void setValeurRemise(BigDecimal valeurRemise) {
        this.valeurRemise = valeurRemise;
    }
    public BigDecimal getMontantMaximum() {
        return this.montantMaximum;
    }
    
    public void setMontantMaximum(BigDecimal montantMaximum) {
        this.montantMaximum = montantMaximum;
    }
    public BigDecimal getMontantMinimumCommande() {
        return this.montantMinimumCommande;
    }
    
    public void setMontantMinimumCommande(BigDecimal montantMinimumCommande) {
        this.montantMinimumCommande = montantMinimumCommande;
    }
    public Serializable getProduitsEligibles() {
        return this.produitsEligibles;
    }
    
    public void setProduitsEligibles(Serializable produitsEligibles) {
        this.produitsEligibles = produitsEligibles;
    }
    public Serializable getCategoriesEligibles() {
        return this.categoriesEligibles;
    }
    
    public void setCategoriesEligibles(Serializable categoriesEligibles) {
        this.categoriesEligibles = categoriesEligibles;
    }
    public Serializable getBoutiquesEligibles() {
        return this.boutiquesEligibles;
    }
    
    public void setBoutiquesEligibles(Serializable boutiquesEligibles) {
        this.boutiquesEligibles = boutiquesEligibles;
    }
    public Integer getUtilisationMaxGlobale() {
        return this.utilisationMaxGlobale;
    }
    
    public void setUtilisationMaxGlobale(Integer utilisationMaxGlobale) {
        this.utilisationMaxGlobale = utilisationMaxGlobale;
    }
    public Integer getUtilisationMaxParClient() {
        return this.utilisationMaxParClient;
    }
    
    public void setUtilisationMaxParClient(Integer utilisationMaxParClient) {
        this.utilisationMaxParClient = utilisationMaxParClient;
    }
    public Integer getUtilisationActuelle() {
        return this.utilisationActuelle;
    }
    
    public void setUtilisationActuelle(Integer utilisationActuelle) {
        this.utilisationActuelle = utilisationActuelle;
    }
    public Timestamp getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Timestamp dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Timestamp getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Timestamp dateFin) {
        this.dateFin = dateFin;
    }
    public Serializable getSegmentsClients() {
        return this.segmentsClients;
    }
    
    public void setSegmentsClients(Serializable segmentsClients) {
        this.segmentsClients = segmentsClients;
    }
    public Serializable getClientsSpecifiques() {
        return this.clientsSpecifiques;
    }
    
    public void setClientsSpecifiques(Serializable clientsSpecifiques) {
        this.clientsSpecifiques = clientsSpecifiques;
    }
    public String getCampagneMarketing() {
        return this.campagneMarketing;
    }
    
    public void setCampagneMarketing(String campagneMarketing) {
        this.campagneMarketing = campagneMarketing;
    }
    public String getCanalDistribution() {
        return this.canalDistribution;
    }
    
    public void setCanalDistribution(String canalDistribution) {
        this.canalDistribution = canalDistribution;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Set getUtilisationsCodesPromos() {
        return this.utilisationsCodesPromos;
    }
    
    public void setUtilisationsCodesPromos(Set utilisationsCodesPromos) {
        this.utilisationsCodesPromos = utilisationsCodesPromos;
    }




}


