package model.livraison;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;

/**
 * SuiviLivraisons generated by hbm2java
 */
public class SuiviLivraisons  implements java.io.Serializable {


     private int id;
     private Livraisons livraisons;
     private String evenement;
     private String description;
     private String lieu;
     private Serializable coordonnees;
     private Serializable transporteurInfo;
     private Serializable detailsSupplementaires;
     private Timestamp timestampEvenement;
     private Timestamp timestampExterne;
     private String source;
     private Timestamp creeLe;

    public SuiviLivraisons() {
    }

	
    public SuiviLivraisons(int id, Livraisons livraisons, String evenement) {
        this.id = id;
        this.livraisons = livraisons;
        this.evenement = evenement;
    }
    public SuiviLivraisons(int id, Livraisons livraisons, String evenement, String description, String lieu, Serializable coordonnees, Serializable transporteurInfo, Serializable detailsSupplementaires, Timestamp timestampEvenement, Timestamp timestampExterne, String source, Timestamp creeLe) {
       this.id = id;
       this.livraisons = livraisons;
       this.evenement = evenement;
       this.description = description;
       this.lieu = lieu;
       this.coordonnees = coordonnees;
       this.transporteurInfo = transporteurInfo;
       this.detailsSupplementaires = detailsSupplementaires;
       this.timestampEvenement = timestampEvenement;
       this.timestampExterne = timestampExterne;
       this.source = source;
       this.creeLe = creeLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Livraisons getLivraisons() {
        return this.livraisons;
    }
    
    public void setLivraisons(Livraisons livraisons) {
        this.livraisons = livraisons;
    }
    public String getEvenement() {
        return this.evenement;
    }
    
    public void setEvenement(String evenement) {
        this.evenement = evenement;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLieu() {
        return this.lieu;
    }
    
    public void setLieu(String lieu) {
        this.lieu = lieu;
    }
    public Serializable getCoordonnees() {
        return this.coordonnees;
    }
    
    public void setCoordonnees(Serializable coordonnees) {
        this.coordonnees = coordonnees;
    }
    public Serializable getTransporteurInfo() {
        return this.transporteurInfo;
    }
    
    public void setTransporteurInfo(Serializable transporteurInfo) {
        this.transporteurInfo = transporteurInfo;
    }
    public Serializable getDetailsSupplementaires() {
        return this.detailsSupplementaires;
    }
    
    public void setDetailsSupplementaires(Serializable detailsSupplementaires) {
        this.detailsSupplementaires = detailsSupplementaires;
    }
    public Timestamp getTimestampEvenement() {
        return this.timestampEvenement;
    }
    
    public void setTimestampEvenement(Timestamp timestampEvenement) {
        this.timestampEvenement = timestampEvenement;
    }
    public Timestamp getTimestampExterne() {
        return this.timestampExterne;
    }
    
    public void setTimestampExterne(Timestamp timestampExterne) {
        this.timestampExterne = timestampExterne;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }




}


