package model.produit;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final



/**
 * AttributsProduits generated by hbm2java
 */
public class AttributsProduits  implements java.io.Serializable {


     private int id;
     private Produits produits;
     private String nomAttribut;
     private String valeurAttribut;
     private String typeAttribut;
     private Integer ordreAffichage;
     private Boolean estFiltrable;
     private Boolean estObligatoire;

    public AttributsProduits() {
    }

	
    public AttributsProduits(int id, Produits produits, String nomAttribut, String valeurAttribut) {
        this.id = id;
        this.produits = produits;
        this.nomAttribut = nomAttribut;
        this.valeurAttribut = valeurAttribut;
    }
    public AttributsProduits(int id, Produits produits, String nomAttribut, String valeurAttribut, String typeAttribut, Integer ordreAffichage, Boolean estFiltrable, Boolean estObligatoire) {
       this.id = id;
       this.produits = produits;
       this.nomAttribut = nomAttribut;
       this.valeurAttribut = valeurAttribut;
       this.typeAttribut = typeAttribut;
       this.ordreAffichage = ordreAffichage;
       this.estFiltrable = estFiltrable;
       this.estObligatoire = estObligatoire;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public String getNomAttribut() {
        return this.nomAttribut;
    }
    
    public void setNomAttribut(String nomAttribut) {
        this.nomAttribut = nomAttribut;
    }
    public String getValeurAttribut() {
        return this.valeurAttribut;
    }
    
    public void setValeurAttribut(String valeurAttribut) {
        this.valeurAttribut = valeurAttribut;
    }
    public String getTypeAttribut() {
        return this.typeAttribut;
    }
    
    public void setTypeAttribut(String typeAttribut) {
        this.typeAttribut = typeAttribut;
    }
    public Integer getOrdreAffichage() {
        return this.ordreAffichage;
    }
    
    public void setOrdreAffichage(Integer ordreAffichage) {
        this.ordreAffichage = ordreAffichage;
    }
    public Boolean getEstFiltrable() {
        return this.estFiltrable;
    }
    
    public void setEstFiltrable(Boolean estFiltrable) {
        this.estFiltrable = estFiltrable;
    }
    public Boolean getEstObligatoire() {
        return this.estObligatoire;
    }
    
    public void setEstObligatoire(Boolean estObligatoire) {
        this.estObligatoire = estObligatoire;
    }




}


