package model.produit;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * CategoriesProduits generated by hbm2java
 */
public class CategoriesProduits  implements java.io.Serializable {


     private int id;
     private CategoriesProduits categoriesProduits;
     private String nom;
     private String description;
     private String iconeUrl;
     private String imageUrl;
     private Integer niveau;
     private Integer ordreAffichage;
     private String cheminHierarchique;
     private Serializable motsCles;
     private Serializable contenuRecherche;
     private Serializable attributsRequis;
     private Serializable parametres;
     private Boolean estActif;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set categoriesProduitses = new HashSet(0);
     private Set produitses = new HashSet(0);

    public CategoriesProduits() {
    }

	
    public CategoriesProduits(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public CategoriesProduits(int id, CategoriesProduits categoriesProduits, String nom, String description, String iconeUrl, String imageUrl, Integer niveau, Integer ordreAffichage, String cheminHierarchique, Serializable motsCles, Serializable contenuRecherche, Serializable attributsRequis, Serializable parametres, Boolean estActif, Timestamp creeLe, Timestamp modifieLe, Set categoriesProduitses, Set produitses) {
       this.id = id;
       this.categoriesProduits = categoriesProduits;
       this.nom = nom;
       this.description = description;
       this.iconeUrl = iconeUrl;
       this.imageUrl = imageUrl;
       this.niveau = niveau;
       this.ordreAffichage = ordreAffichage;
       this.cheminHierarchique = cheminHierarchique;
       this.motsCles = motsCles;
       this.contenuRecherche = contenuRecherche;
       this.attributsRequis = attributsRequis;
       this.parametres = parametres;
       this.estActif = estActif;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.categoriesProduitses = categoriesProduitses;
       this.produitses = produitses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CategoriesProduits getCategoriesProduits() {
        return this.categoriesProduits;
    }
    
    public void setCategoriesProduits(CategoriesProduits categoriesProduits) {
        this.categoriesProduits = categoriesProduits;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getIconeUrl() {
        return this.iconeUrl;
    }
    
    public void setIconeUrl(String iconeUrl) {
        this.iconeUrl = iconeUrl;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public Integer getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(Integer niveau) {
        this.niveau = niveau;
    }
    public Integer getOrdreAffichage() {
        return this.ordreAffichage;
    }
    
    public void setOrdreAffichage(Integer ordreAffichage) {
        this.ordreAffichage = ordreAffichage;
    }
    public String getCheminHierarchique() {
        return this.cheminHierarchique;
    }
    
    public void setCheminHierarchique(String cheminHierarchique) {
        this.cheminHierarchique = cheminHierarchique;
    }
    public Serializable getMotsCles() {
        return this.motsCles;
    }
    
    public void setMotsCles(Serializable motsCles) {
        this.motsCles = motsCles;
    }
    public Serializable getContenuRecherche() {
        return this.contenuRecherche;
    }
    
    public void setContenuRecherche(Serializable contenuRecherche) {
        this.contenuRecherche = contenuRecherche;
    }
    public Serializable getAttributsRequis() {
        return this.attributsRequis;
    }
    
    public void setAttributsRequis(Serializable attributsRequis) {
        this.attributsRequis = attributsRequis;
    }
    public Serializable getParametres() {
        return this.parametres;
    }
    
    public void setParametres(Serializable parametres) {
        this.parametres = parametres;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getCategoriesProduitses() {
        return this.categoriesProduitses;
    }
    
    public void setCategoriesProduitses(Set categoriesProduitses) {
        this.categoriesProduitses = categoriesProduitses;
    }
    public Set getProduitses() {
        return this.produitses;
    }
    
    public void setProduitses(Set produitses) {
        this.produitses = produitses;
    }




}


