package model.produit;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import model.reference.Pays;

/**
 * Marques generated by hbm2java
 */
public class Marques  implements java.io.Serializable {


     private int id;
     private Pays pays;
     private String nom;
     private String description;
     private String logoUrl;
     private String siteWeb;
     private Serializable metadonnees;
     private Boolean estActif;
     private Timestamp creeLe;
     private Set produitses = new HashSet(0);

    public Marques() {
    }

	
    public Marques(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public Marques(int id, Pays pays, String nom, String description, String logoUrl, String siteWeb, Serializable metadonnees, Boolean estActif, Timestamp creeLe, Set produitses) {
       this.id = id;
       this.pays = pays;
       this.nom = nom;
       this.description = description;
       this.logoUrl = logoUrl;
       this.siteWeb = siteWeb;
       this.metadonnees = metadonnees;
       this.estActif = estActif;
       this.creeLe = creeLe;
       this.produitses = produitses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pays getPays() {
        return this.pays;
    }
    
    public void setPays(Pays pays) {
        this.pays = pays;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLogoUrl() {
        return this.logoUrl;
    }
    
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
    public String getSiteWeb() {
        return this.siteWeb;
    }
    
    public void setSiteWeb(String siteWeb) {
        this.siteWeb = siteWeb;
    }
    public Serializable getMetadonnees() {
        return this.metadonnees;
    }
    
    public void setMetadonnees(Serializable metadonnees) {
        this.metadonnees = metadonnees;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Set getProduitses() {
        return this.produitses;
    }
    
    public void setProduitses(Set produitses) {
        this.produitses = produitses;
    }




}


