package model.produit;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import model.utilisateur.Clients;

/**
 * Paniers generated by hbm2java
 */
public class Paniers  implements java.io.Serializable {


     private int id;
     private Clients clients;
     private String sessionId;
     private BigDecimal sousTotal;
     private BigDecimal montantTva;
     private BigDecimal fraisLivraison;
     private BigDecimal remiseAppliquee;
     private BigDecimal totalFinal;
     private String codePromoApplique;
     private Boolean estActif;
     private Timestamp dateExpiration;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set articlesPaniers = new HashSet(0);

    public Paniers() {
    }

	
    public Paniers(int id, Clients clients) {
        this.id = id;
        this.clients = clients;
    }
    public Paniers(int id, Clients clients, String sessionId, BigDecimal sousTotal, BigDecimal montantTva, BigDecimal fraisLivraison, BigDecimal remiseAppliquee, BigDecimal totalFinal, String codePromoApplique, Boolean estActif, Timestamp dateExpiration, Timestamp creeLe, Timestamp modifieLe, Set articlesPaniers) {
       this.id = id;
       this.clients = clients;
       this.sessionId = sessionId;
       this.sousTotal = sousTotal;
       this.montantTva = montantTva;
       this.fraisLivraison = fraisLivraison;
       this.remiseAppliquee = remiseAppliquee;
       this.totalFinal = totalFinal;
       this.codePromoApplique = codePromoApplique;
       this.estActif = estActif;
       this.dateExpiration = dateExpiration;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.articlesPaniers = articlesPaniers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public BigDecimal getSousTotal() {
        return this.sousTotal;
    }
    
    public void setSousTotal(BigDecimal sousTotal) {
        this.sousTotal = sousTotal;
    }
    public BigDecimal getMontantTva() {
        return this.montantTva;
    }
    
    public void setMontantTva(BigDecimal montantTva) {
        this.montantTva = montantTva;
    }
    public BigDecimal getFraisLivraison() {
        return this.fraisLivraison;
    }
    
    public void setFraisLivraison(BigDecimal fraisLivraison) {
        this.fraisLivraison = fraisLivraison;
    }
    public BigDecimal getRemiseAppliquee() {
        return this.remiseAppliquee;
    }
    
    public void setRemiseAppliquee(BigDecimal remiseAppliquee) {
        this.remiseAppliquee = remiseAppliquee;
    }
    public BigDecimal getTotalFinal() {
        return this.totalFinal;
    }
    
    public void setTotalFinal(BigDecimal totalFinal) {
        this.totalFinal = totalFinal;
    }
    public String getCodePromoApplique() {
        return this.codePromoApplique;
    }
    
    public void setCodePromoApplique(String codePromoApplique) {
        this.codePromoApplique = codePromoApplique;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Timestamp getDateExpiration() {
        return this.dateExpiration;
    }
    
    public void setDateExpiration(Timestamp dateExpiration) {
        this.dateExpiration = dateExpiration;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getArticlesPaniers() {
        return this.articlesPaniers;
    }
    
    public void setArticlesPaniers(Set articlesPaniers) {
        this.articlesPaniers = articlesPaniers;
    }




}


