package model.recherche;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import model.entreprise.Boutiques;
import model.produit.Produits;
import model.utilisateur.ComptesUtilisateur;

/**
 * HistoriqueRecherches generated by hbm2java
 */
public class HistoriqueRecherches  implements java.io.Serializable {


     private int id;
     private Produits produits;
     private ComptesUtilisateur comptesUtilisateur;
     private Boutiques boutiques;
     private String sessionId;
     private String texteRecherche;
     private String typeRecherche;
     private String langueRecherche;
     private String fichierAudioUrl;
     private String transcriptionAudio;
     private BigDecimal confianceTranscription;
     private String imageRechercheUrl;
     private String hashImage;
     private Serializable objetsDetectes;
     private Integer nombreResultats;
     private Serializable resultatsIds;
     private Integer tempsRechercheMs;
     private Serializable coordonneesRecherche;
     private Integer rayonRechercheKm;
     private Serializable filtresAppliques;
     private String triApplique;
     private Boolean ACliqueResultat;
     private Integer positionClic;
     private Timestamp creeLe;

    public HistoriqueRecherches() {
    }

	
    public HistoriqueRecherches(int id) {
        this.id = id;
    }
    public HistoriqueRecherches(int id, Produits produits, ComptesUtilisateur comptesUtilisateur, Boutiques boutiques, String sessionId, String texteRecherche, String typeRecherche, String langueRecherche, String fichierAudioUrl, String transcriptionAudio, BigDecimal confianceTranscription, String imageRechercheUrl, String hashImage, Serializable objetsDetectes, Integer nombreResultats, Serializable resultatsIds, Integer tempsRechercheMs, Serializable coordonneesRecherche, Integer rayonRechercheKm, Serializable filtresAppliques, String triApplique, Boolean ACliqueResultat, Integer positionClic, Timestamp creeLe) {
       this.id = id;
       this.produits = produits;
       this.comptesUtilisateur = comptesUtilisateur;
       this.boutiques = boutiques;
       this.sessionId = sessionId;
       this.texteRecherche = texteRecherche;
       this.typeRecherche = typeRecherche;
       this.langueRecherche = langueRecherche;
       this.fichierAudioUrl = fichierAudioUrl;
       this.transcriptionAudio = transcriptionAudio;
       this.confianceTranscription = confianceTranscription;
       this.imageRechercheUrl = imageRechercheUrl;
       this.hashImage = hashImage;
       this.objetsDetectes = objetsDetectes;
       this.nombreResultats = nombreResultats;
       this.resultatsIds = resultatsIds;
       this.tempsRechercheMs = tempsRechercheMs;
       this.coordonneesRecherche = coordonneesRecherche;
       this.rayonRechercheKm = rayonRechercheKm;
       this.filtresAppliques = filtresAppliques;
       this.triApplique = triApplique;
       this.ACliqueResultat = ACliqueResultat;
       this.positionClic = positionClic;
       this.creeLe = creeLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public Boutiques getBoutiques() {
        return this.boutiques;
    }
    
    public void setBoutiques(Boutiques boutiques) {
        this.boutiques = boutiques;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public String getTexteRecherche() {
        return this.texteRecherche;
    }
    
    public void setTexteRecherche(String texteRecherche) {
        this.texteRecherche = texteRecherche;
    }
    public String getTypeRecherche() {
        return this.typeRecherche;
    }
    
    public void setTypeRecherche(String typeRecherche) {
        this.typeRecherche = typeRecherche;
    }
    public String getLangueRecherche() {
        return this.langueRecherche;
    }
    
    public void setLangueRecherche(String langueRecherche) {
        this.langueRecherche = langueRecherche;
    }
    public String getFichierAudioUrl() {
        return this.fichierAudioUrl;
    }
    
    public void setFichierAudioUrl(String fichierAudioUrl) {
        this.fichierAudioUrl = fichierAudioUrl;
    }
    public String getTranscriptionAudio() {
        return this.transcriptionAudio;
    }
    
    public void setTranscriptionAudio(String transcriptionAudio) {
        this.transcriptionAudio = transcriptionAudio;
    }
    public BigDecimal getConfianceTranscription() {
        return this.confianceTranscription;
    }
    
    public void setConfianceTranscription(BigDecimal confianceTranscription) {
        this.confianceTranscription = confianceTranscription;
    }
    public String getImageRechercheUrl() {
        return this.imageRechercheUrl;
    }
    
    public void setImageRechercheUrl(String imageRechercheUrl) {
        this.imageRechercheUrl = imageRechercheUrl;
    }
    public String getHashImage() {
        return this.hashImage;
    }
    
    public void setHashImage(String hashImage) {
        this.hashImage = hashImage;
    }
    public Serializable getObjetsDetectes() {
        return this.objetsDetectes;
    }
    
    public void setObjetsDetectes(Serializable objetsDetectes) {
        this.objetsDetectes = objetsDetectes;
    }
    public Integer getNombreResultats() {
        return this.nombreResultats;
    }
    
    public void setNombreResultats(Integer nombreResultats) {
        this.nombreResultats = nombreResultats;
    }
    public Serializable getResultatsIds() {
        return this.resultatsIds;
    }
    
    public void setResultatsIds(Serializable resultatsIds) {
        this.resultatsIds = resultatsIds;
    }
    public Integer getTempsRechercheMs() {
        return this.tempsRechercheMs;
    }
    
    public void setTempsRechercheMs(Integer tempsRechercheMs) {
        this.tempsRechercheMs = tempsRechercheMs;
    }
    public Serializable getCoordonneesRecherche() {
        return this.coordonneesRecherche;
    }
    
    public void setCoordonneesRecherche(Serializable coordonneesRecherche) {
        this.coordonneesRecherche = coordonneesRecherche;
    }
    public Integer getRayonRechercheKm() {
        return this.rayonRechercheKm;
    }
    
    public void setRayonRechercheKm(Integer rayonRechercheKm) {
        this.rayonRechercheKm = rayonRechercheKm;
    }
    public Serializable getFiltresAppliques() {
        return this.filtresAppliques;
    }
    
    public void setFiltresAppliques(Serializable filtresAppliques) {
        this.filtresAppliques = filtresAppliques;
    }
    public String getTriApplique() {
        return this.triApplique;
    }
    
    public void setTriApplique(String triApplique) {
        this.triApplique = triApplique;
    }
    public Boolean getACliqueResultat() {
        return this.ACliqueResultat;
    }
    
    public void setACliqueResultat(Boolean ACliqueResultat) {
        this.ACliqueResultat = ACliqueResultat;
    }
    public Integer getPositionClic() {
        return this.positionClic;
    }
    
    public void setPositionClic(Integer positionClic) {
        this.positionClic = positionClic;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }




}


