package model.recherche;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * SuggestionsRecherche generated by hbm2java
 */
public class SuggestionsRecherche  implements java.io.Serializable {


     private int id;
     private String texteSuggestion;
     private Integer frequenceUtilisation;
     private String langue;
     private Serializable categoriesAssociees;
     private Serializable tagsAssocies;
     private BigDecimal populariteScore;
     private Boolean estActif;
     private Timestamp creeLe;
     private Timestamp modifieLe;

    public SuggestionsRecherche() {
    }

	
    public SuggestionsRecherche(int id, String texteSuggestion) {
        this.id = id;
        this.texteSuggestion = texteSuggestion;
    }
    public SuggestionsRecherche(int id, String texteSuggestion, Integer frequenceUtilisation, String langue, Serializable categoriesAssociees, Serializable tagsAssocies, BigDecimal populariteScore, Boolean estActif, Timestamp creeLe, Timestamp modifieLe) {
       this.id = id;
       this.texteSuggestion = texteSuggestion;
       this.frequenceUtilisation = frequenceUtilisation;
       this.langue = langue;
       this.categoriesAssociees = categoriesAssociees;
       this.tagsAssocies = tagsAssocies;
       this.populariteScore = populariteScore;
       this.estActif = estActif;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTexteSuggestion() {
        return this.texteSuggestion;
    }
    
    public void setTexteSuggestion(String texteSuggestion) {
        this.texteSuggestion = texteSuggestion;
    }
    public Integer getFrequenceUtilisation() {
        return this.frequenceUtilisation;
    }
    
    public void setFrequenceUtilisation(Integer frequenceUtilisation) {
        this.frequenceUtilisation = frequenceUtilisation;
    }
    public String getLangue() {
        return this.langue;
    }
    
    public void setLangue(String langue) {
        this.langue = langue;
    }
    public Serializable getCategoriesAssociees() {
        return this.categoriesAssociees;
    }
    
    public void setCategoriesAssociees(Serializable categoriesAssociees) {
        this.categoriesAssociees = categoriesAssociees;
    }
    public Serializable getTagsAssocies() {
        return this.tagsAssocies;
    }
    
    public void setTagsAssocies(Serializable tagsAssocies) {
        this.tagsAssocies = tagsAssocies;
    }
    public BigDecimal getPopulariteScore() {
        return this.populariteScore;
    }
    
    public void setPopulariteScore(BigDecimal populariteScore) {
        this.populariteScore = populariteScore;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }




}


