package model.recherche;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.math.BigDecimal;

/**
 * SynonymesRecherche generated by hbm2java
 */
public class SynonymesRecherche  implements java.io.Serializable {


     private int id;
     private String motPrincipal;
     private String synonyme;
     private String langue;
     private BigDecimal poids;
     private Boolean estActif;

    public SynonymesRecherche() {
    }

	
    public SynonymesRecherche(int id, String motPrincipal, String synonyme) {
        this.id = id;
        this.motPrincipal = motPrincipal;
        this.synonyme = synonyme;
    }
    public SynonymesRecherche(int id, String motPrincipal, String synonyme, String langue, BigDecimal poids, Boolean estActif) {
       this.id = id;
       this.motPrincipal = motPrincipal;
       this.synonyme = synonyme;
       this.langue = langue;
       this.poids = poids;
       this.estActif = estActif;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMotPrincipal() {
        return this.motPrincipal;
    }
    
    public void setMotPrincipal(String motPrincipal) {
        this.motPrincipal = motPrincipal;
    }
    public String getSynonyme() {
        return this.synonyme;
    }
    
    public void setSynonyme(String synonyme) {
        this.synonyme = synonyme;
    }
    public String getLangue() {
        return this.langue;
    }
    
    public void setLangue(String langue) {
        this.langue = langue;
    }
    public BigDecimal getPoids() {
        return this.poids;
    }
    
    public void setPoids(BigDecimal poids) {
        this.poids = poids;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }




}


