package model.utilisateur;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
public class Clients  implements java.io.Serializable {


     private int id;
     private Personnes personnes;
     private String numeroClient;
     private Serializable boutiquesPreferees;
     private Serializable categoriesPreferees;
     private Serializable marquesPreferees;
     private Timestamp premiereCommandeLe;
     private Timestamp derniereCommandeLe;
     private Integer nombreCommandes;
     private BigDecimal totalDepense;
     private BigDecimal panierMoyen;
     private Integer pointsFidelite;
     private String niveauFidelite;
     private Boolean accepteNewsletter;
     private Boolean accepteSmsPromo;
     private Boolean accepteNotificationsPush;
     private Serializable comportementAchat;
     private String segmentationClient;
     private Timestamp dateInscription;
     private Timestamp derniereActivite;
     private Boolean estActif;
     private Set evaluationsBoutiqueses = new HashSet(0);
     private Set panierses = new HashSet(0);
     private Set commandeses = new HashSet(0);
     private Set utilisationsCodesPromos = new HashSet(0);
     private Set votesEvaluationses = new HashSet(0);
     private Set evaluationsProduitses = new HashSet(0);

    public Clients() {
    }

	
    public Clients(int id, Personnes personnes) {
        this.id = id;
        this.personnes = personnes;
    }
    public Clients(int id, Personnes personnes, String numeroClient, Serializable boutiquesPreferees, Serializable categoriesPreferees, Serializable marquesPreferees, Timestamp premiereCommandeLe, Timestamp derniereCommandeLe, Integer nombreCommandes, BigDecimal totalDepense, BigDecimal panierMoyen, Integer pointsFidelite, String niveauFidelite, Boolean accepteNewsletter, Boolean accepteSmsPromo, Boolean accepteNotificationsPush, Serializable comportementAchat, String segmentationClient, Timestamp dateInscription, Timestamp derniereActivite, Boolean estActif, Set evaluationsBoutiqueses, Set panierses, Set commandeses, Set utilisationsCodesPromos, Set votesEvaluationses, Set evaluationsProduitses) {
       this.id = id;
       this.personnes = personnes;
       this.numeroClient = numeroClient;
       this.boutiquesPreferees = boutiquesPreferees;
       this.categoriesPreferees = categoriesPreferees;
       this.marquesPreferees = marquesPreferees;
       this.premiereCommandeLe = premiereCommandeLe;
       this.derniereCommandeLe = derniereCommandeLe;
       this.nombreCommandes = nombreCommandes;
       this.totalDepense = totalDepense;
       this.panierMoyen = panierMoyen;
       this.pointsFidelite = pointsFidelite;
       this.niveauFidelite = niveauFidelite;
       this.accepteNewsletter = accepteNewsletter;
       this.accepteSmsPromo = accepteSmsPromo;
       this.accepteNotificationsPush = accepteNotificationsPush;
       this.comportementAchat = comportementAchat;
       this.segmentationClient = segmentationClient;
       this.dateInscription = dateInscription;
       this.derniereActivite = derniereActivite;
       this.estActif = estActif;
       this.evaluationsBoutiqueses = evaluationsBoutiqueses;
       this.panierses = panierses;
       this.commandeses = commandeses;
       this.utilisationsCodesPromos = utilisationsCodesPromos;
       this.votesEvaluationses = votesEvaluationses;
       this.evaluationsProduitses = evaluationsProduitses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Personnes getPersonnes() {
        return this.personnes;
    }
    
    public void setPersonnes(Personnes personnes) {
        this.personnes = personnes;
    }
    public String getNumeroClient() {
        return this.numeroClient;
    }
    
    public void setNumeroClient(String numeroClient) {
        this.numeroClient = numeroClient;
    }
    public Serializable getBoutiquesPreferees() {
        return this.boutiquesPreferees;
    }
    
    public void setBoutiquesPreferees(Serializable boutiquesPreferees) {
        this.boutiquesPreferees = boutiquesPreferees;
    }
    public Serializable getCategoriesPreferees() {
        return this.categoriesPreferees;
    }
    
    public void setCategoriesPreferees(Serializable categoriesPreferees) {
        this.categoriesPreferees = categoriesPreferees;
    }
    public Serializable getMarquesPreferees() {
        return this.marquesPreferees;
    }
    
    public void setMarquesPreferees(Serializable marquesPreferees) {
        this.marquesPreferees = marquesPreferees;
    }
    public Timestamp getPremiereCommandeLe() {
        return this.premiereCommandeLe;
    }
    
    public void setPremiereCommandeLe(Timestamp premiereCommandeLe) {
        this.premiereCommandeLe = premiereCommandeLe;
    }
    public Timestamp getDerniereCommandeLe() {
        return this.derniereCommandeLe;
    }
    
    public void setDerniereCommandeLe(Timestamp derniereCommandeLe) {
        this.derniereCommandeLe = derniereCommandeLe;
    }
    public Integer getNombreCommandes() {
        return this.nombreCommandes;
    }
    
    public void setNombreCommandes(Integer nombreCommandes) {
        this.nombreCommandes = nombreCommandes;
    }
    public BigDecimal getTotalDepense() {
        return this.totalDepense;
    }
    
    public void setTotalDepense(BigDecimal totalDepense) {
        this.totalDepense = totalDepense;
    }
    public BigDecimal getPanierMoyen() {
        return this.panierMoyen;
    }
    
    public void setPanierMoyen(BigDecimal panierMoyen) {
        this.panierMoyen = panierMoyen;
    }
    public Integer getPointsFidelite() {
        return this.pointsFidelite;
    }
    
    public void setPointsFidelite(Integer pointsFidelite) {
        this.pointsFidelite = pointsFidelite;
    }
    public String getNiveauFidelite() {
        return this.niveauFidelite;
    }
    
    public void setNiveauFidelite(String niveauFidelite) {
        this.niveauFidelite = niveauFidelite;
    }
    public Boolean getAccepteNewsletter() {
        return this.accepteNewsletter;
    }
    
    public void setAccepteNewsletter(Boolean accepteNewsletter) {
        this.accepteNewsletter = accepteNewsletter;
    }
    public Boolean getAccepteSmsPromo() {
        return this.accepteSmsPromo;
    }
    
    public void setAccepteSmsPromo(Boolean accepteSmsPromo) {
        this.accepteSmsPromo = accepteSmsPromo;
    }
    public Boolean getAccepteNotificationsPush() {
        return this.accepteNotificationsPush;
    }
    
    public void setAccepteNotificationsPush(Boolean accepteNotificationsPush) {
        this.accepteNotificationsPush = accepteNotificationsPush;
    }
    public Serializable getComportementAchat() {
        return this.comportementAchat;
    }
    
    public void setComportementAchat(Serializable comportementAchat) {
        this.comportementAchat = comportementAchat;
    }
    public String getSegmentationClient() {
        return this.segmentationClient;
    }
    
    public void setSegmentationClient(String segmentationClient) {
        this.segmentationClient = segmentationClient;
    }
    public Timestamp getDateInscription() {
        return this.dateInscription;
    }
    
    public void setDateInscription(Timestamp dateInscription) {
        this.dateInscription = dateInscription;
    }
    public Timestamp getDerniereActivite() {
        return this.derniereActivite;
    }
    
    public void setDerniereActivite(Timestamp derniereActivite) {
        this.derniereActivite = derniereActivite;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Set getEvaluationsBoutiqueses() {
        return this.evaluationsBoutiqueses;
    }
    
    public void setEvaluationsBoutiqueses(Set evaluationsBoutiqueses) {
        this.evaluationsBoutiqueses = evaluationsBoutiqueses;
    }
    public Set getPanierses() {
        return this.panierses;
    }
    
    public void setPanierses(Set panierses) {
        this.panierses = panierses;
    }
    public Set getCommandeses() {
        return this.commandeses;
    }
    
    public void setCommandeses(Set commandeses) {
        this.commandeses = commandeses;
    }
    public Set getUtilisationsCodesPromos() {
        return this.utilisationsCodesPromos;
    }
    
    public void setUtilisationsCodesPromos(Set utilisationsCodesPromos) {
        this.utilisationsCodesPromos = utilisationsCodesPromos;
    }
    public Set getVotesEvaluationses() {
        return this.votesEvaluationses;
    }
    
    public void setVotesEvaluationses(Set votesEvaluationses) {
        this.votesEvaluationses = votesEvaluationses;
    }
    public Set getEvaluationsProduitses() {
        return this.evaluationsProduitses;
    }
    
    public void setEvaluationsProduitses(Set evaluationsProduitses) {
        this.evaluationsProduitses = evaluationsProduitses;
    }




}


