package model.utilisateur;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * ComptesUtilisateur generated by hbm2java
 */
public class ComptesUtilisateur  implements java.io.Serializable {


     private int id;
     private Personnes personnes;
     private String nomUtilisateur;
     private String email;
     private String motDePasseHash;
     private String googleId;
     private String googleAccessToken;
     private String googleRefreshToken;
     private Timestamp googleTokenExpireLe;
     private String facebookId;
     private String appleId;
     private Serializable oauthMetadata;
     private Boolean doubleAuthentificationActive;
     private String secretDoubleAuth;
     private Serializable codesRecuperation;
     private Timestamp emailVerifieLe;
     private Timestamp telephoneVerifieLe;
     private String codeVerification;
     private Timestamp codeExpireLe;
     private Timestamp derniereConnexionLe;
     private Serializable derniereConnexionIp;
     private Integer tentativesEchec;
     private Timestamp verrouilleJusqu;
     private Timestamp motDePasseExpireLe;
     private Boolean notificationsEmail;
     private Boolean notificationsPush;
     private Boolean notificationsSms;
     private String stripeCustomerId;
     private String stripeAccountId;
     private Boolean estActif;
     private Boolean estVerifie;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set mouvementsStocks = new HashSet(0);
     private Set logsSystemes = new HashSet(0);
     private Set evaluationsProduitses = new HashSet(0);
     private Set historiqueConnexionses = new HashSet(0);
     private Set historiqueStatutsCommandes = new HashSet(0);
     private Set remboursementsesForApprouvePar = new HashSet(0);
     private Set codesPromotionnelses = new HashSet(0);
     private Set templatesNotificationses = new HashSet(0);
     private Set evenementsAnalyticses = new HashSet(0);
     private Set preferencesNotificationses = new HashSet(0);
     private Set auditModificationses = new HashSet(0);
     private Set remboursementsesForDemandePar = new HashSet(0);
     private Set historiqueRechercheses = new HashSet(0);
     private Set campagnesMarketings = new HashSet(0);
     private Set notificationsEnvoyeeses = new HashSet(0);
     private Set sessionsActiveses = new HashSet(0);

    public ComptesUtilisateur() {
    }

	
    public ComptesUtilisateur(int id, Personnes personnes, String email) {
        this.id = id;
        this.personnes = personnes;
        this.email = email;
    }
    public ComptesUtilisateur(int id, Personnes personnes, String nomUtilisateur, String email, String motDePasseHash, String googleId, String googleAccessToken, String googleRefreshToken, Timestamp googleTokenExpireLe, String facebookId, String appleId, Serializable oauthMetadata, Boolean doubleAuthentificationActive, String secretDoubleAuth, Serializable codesRecuperation, Timestamp emailVerifieLe, Timestamp telephoneVerifieLe, String codeVerification, Timestamp codeExpireLe, Timestamp derniereConnexionLe, Serializable derniereConnexionIp, Integer tentativesEchec, Timestamp verrouilleJusqu, Timestamp motDePasseExpireLe, Boolean notificationsEmail, Boolean notificationsPush, Boolean notificationsSms, String stripeCustomerId, String stripeAccountId, Boolean estActif, Boolean estVerifie, Timestamp creeLe, Timestamp modifieLe, Set mouvementsStocks, Set logsSystemes, Set evaluationsProduitses, Set historiqueConnexionses, Set historiqueStatutsCommandes, Set remboursementsesForApprouvePar, Set codesPromotionnelses, Set templatesNotificationses, Set evenementsAnalyticses, Set preferencesNotificationses, Set auditModificationses, Set remboursementsesForDemandePar, Set historiqueRechercheses, Set campagnesMarketings, Set notificationsEnvoyeeses, Set sessionsActiveses) {
       this.id = id;
       this.personnes = personnes;
       this.nomUtilisateur = nomUtilisateur;
       this.email = email;
       this.motDePasseHash = motDePasseHash;
       this.googleId = googleId;
       this.googleAccessToken = googleAccessToken;
       this.googleRefreshToken = googleRefreshToken;
       this.googleTokenExpireLe = googleTokenExpireLe;
       this.facebookId = facebookId;
       this.appleId = appleId;
       this.oauthMetadata = oauthMetadata;
       this.doubleAuthentificationActive = doubleAuthentificationActive;
       this.secretDoubleAuth = secretDoubleAuth;
       this.codesRecuperation = codesRecuperation;
       this.emailVerifieLe = emailVerifieLe;
       this.telephoneVerifieLe = telephoneVerifieLe;
       this.codeVerification = codeVerification;
       this.codeExpireLe = codeExpireLe;
       this.derniereConnexionLe = derniereConnexionLe;
       this.derniereConnexionIp = derniereConnexionIp;
       this.tentativesEchec = tentativesEchec;
       this.verrouilleJusqu = verrouilleJusqu;
       this.motDePasseExpireLe = motDePasseExpireLe;
       this.notificationsEmail = notificationsEmail;
       this.notificationsPush = notificationsPush;
       this.notificationsSms = notificationsSms;
       this.stripeCustomerId = stripeCustomerId;
       this.stripeAccountId = stripeAccountId;
       this.estActif = estActif;
       this.estVerifie = estVerifie;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.mouvementsStocks = mouvementsStocks;
       this.logsSystemes = logsSystemes;
       this.evaluationsProduitses = evaluationsProduitses;
       this.historiqueConnexionses = historiqueConnexionses;
       this.historiqueStatutsCommandes = historiqueStatutsCommandes;
       this.remboursementsesForApprouvePar = remboursementsesForApprouvePar;
       this.codesPromotionnelses = codesPromotionnelses;
       this.templatesNotificationses = templatesNotificationses;
       this.evenementsAnalyticses = evenementsAnalyticses;
       this.preferencesNotificationses = preferencesNotificationses;
       this.auditModificationses = auditModificationses;
       this.remboursementsesForDemandePar = remboursementsesForDemandePar;
       this.historiqueRechercheses = historiqueRechercheses;
       this.campagnesMarketings = campagnesMarketings;
       this.notificationsEnvoyeeses = notificationsEnvoyeeses;
       this.sessionsActiveses = sessionsActiveses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Personnes getPersonnes() {
        return this.personnes;
    }
    
    public void setPersonnes(Personnes personnes) {
        this.personnes = personnes;
    }
    public String getNomUtilisateur() {
        return this.nomUtilisateur;
    }
    
    public void setNomUtilisateur(String nomUtilisateur) {
        this.nomUtilisateur = nomUtilisateur;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMotDePasseHash() {
        return this.motDePasseHash;
    }
    
    public void setMotDePasseHash(String motDePasseHash) {
        this.motDePasseHash = motDePasseHash;
    }
    public String getGoogleId() {
        return this.googleId;
    }
    
    public void setGoogleId(String googleId) {
        this.googleId = googleId;
    }
    public String getGoogleAccessToken() {
        return this.googleAccessToken;
    }
    
    public void setGoogleAccessToken(String googleAccessToken) {
        this.googleAccessToken = googleAccessToken;
    }
    public String getGoogleRefreshToken() {
        return this.googleRefreshToken;
    }
    
    public void setGoogleRefreshToken(String googleRefreshToken) {
        this.googleRefreshToken = googleRefreshToken;
    }
    public Timestamp getGoogleTokenExpireLe() {
        return this.googleTokenExpireLe;
    }
    
    public void setGoogleTokenExpireLe(Timestamp googleTokenExpireLe) {
        this.googleTokenExpireLe = googleTokenExpireLe;
    }
    public String getFacebookId() {
        return this.facebookId;
    }
    
    public void setFacebookId(String facebookId) {
        this.facebookId = facebookId;
    }
    public String getAppleId() {
        return this.appleId;
    }
    
    public void setAppleId(String appleId) {
        this.appleId = appleId;
    }
    public Serializable getOauthMetadata() {
        return this.oauthMetadata;
    }
    
    public void setOauthMetadata(Serializable oauthMetadata) {
        this.oauthMetadata = oauthMetadata;
    }
    public Boolean getDoubleAuthentificationActive() {
        return this.doubleAuthentificationActive;
    }
    
    public void setDoubleAuthentificationActive(Boolean doubleAuthentificationActive) {
        this.doubleAuthentificationActive = doubleAuthentificationActive;
    }
    public String getSecretDoubleAuth() {
        return this.secretDoubleAuth;
    }
    
    public void setSecretDoubleAuth(String secretDoubleAuth) {
        this.secretDoubleAuth = secretDoubleAuth;
    }
    public Serializable getCodesRecuperation() {
        return this.codesRecuperation;
    }
    
    public void setCodesRecuperation(Serializable codesRecuperation) {
        this.codesRecuperation = codesRecuperation;
    }
    public Timestamp getEmailVerifieLe() {
        return this.emailVerifieLe;
    }
    
    public void setEmailVerifieLe(Timestamp emailVerifieLe) {
        this.emailVerifieLe = emailVerifieLe;
    }
    public Timestamp getTelephoneVerifieLe() {
        return this.telephoneVerifieLe;
    }
    
    public void setTelephoneVerifieLe(Timestamp telephoneVerifieLe) {
        this.telephoneVerifieLe = telephoneVerifieLe;
    }
    public String getCodeVerification() {
        return this.codeVerification;
    }
    
    public void setCodeVerification(String codeVerification) {
        this.codeVerification = codeVerification;
    }
    public Timestamp getCodeExpireLe() {
        return this.codeExpireLe;
    }
    
    public void setCodeExpireLe(Timestamp codeExpireLe) {
        this.codeExpireLe = codeExpireLe;
    }
    public Timestamp getDerniereConnexionLe() {
        return this.derniereConnexionLe;
    }
    
    public void setDerniereConnexionLe(Timestamp derniereConnexionLe) {
        this.derniereConnexionLe = derniereConnexionLe;
    }
    public Serializable getDerniereConnexionIp() {
        return this.derniereConnexionIp;
    }
    
    public void setDerniereConnexionIp(Serializable derniereConnexionIp) {
        this.derniereConnexionIp = derniereConnexionIp;
    }
    public Integer getTentativesEchec() {
        return this.tentativesEchec;
    }
    
    public void setTentativesEchec(Integer tentativesEchec) {
        this.tentativesEchec = tentativesEchec;
    }
    public Timestamp getVerrouilleJusqu() {
        return this.verrouilleJusqu;
    }
    
    public void setVerrouilleJusqu(Timestamp verrouilleJusqu) {
        this.verrouilleJusqu = verrouilleJusqu;
    }
    public Timestamp getMotDePasseExpireLe() {
        return this.motDePasseExpireLe;
    }
    
    public void setMotDePasseExpireLe(Timestamp motDePasseExpireLe) {
        this.motDePasseExpireLe = motDePasseExpireLe;
    }
    public Boolean getNotificationsEmail() {
        return this.notificationsEmail;
    }
    
    public void setNotificationsEmail(Boolean notificationsEmail) {
        this.notificationsEmail = notificationsEmail;
    }
    public Boolean getNotificationsPush() {
        return this.notificationsPush;
    }
    
    public void setNotificationsPush(Boolean notificationsPush) {
        this.notificationsPush = notificationsPush;
    }
    public Boolean getNotificationsSms() {
        return this.notificationsSms;
    }
    
    public void setNotificationsSms(Boolean notificationsSms) {
        this.notificationsSms = notificationsSms;
    }
    public String getStripeCustomerId() {
        return this.stripeCustomerId;
    }
    
    public void setStripeCustomerId(String stripeCustomerId) {
        this.stripeCustomerId = stripeCustomerId;
    }
    public String getStripeAccountId() {
        return this.stripeAccountId;
    }
    
    public void setStripeAccountId(String stripeAccountId) {
        this.stripeAccountId = stripeAccountId;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Boolean getEstVerifie() {
        return this.estVerifie;
    }
    
    public void setEstVerifie(Boolean estVerifie) {
        this.estVerifie = estVerifie;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getMouvementsStocks() {
        return this.mouvementsStocks;
    }
    
    public void setMouvementsStocks(Set mouvementsStocks) {
        this.mouvementsStocks = mouvementsStocks;
    }
    public Set getLogsSystemes() {
        return this.logsSystemes;
    }
    
    public void setLogsSystemes(Set logsSystemes) {
        this.logsSystemes = logsSystemes;
    }
    public Set getEvaluationsProduitses() {
        return this.evaluationsProduitses;
    }
    
    public void setEvaluationsProduitses(Set evaluationsProduitses) {
        this.evaluationsProduitses = evaluationsProduitses;
    }
    public Set getHistoriqueConnexionses() {
        return this.historiqueConnexionses;
    }
    
    public void setHistoriqueConnexionses(Set historiqueConnexionses) {
        this.historiqueConnexionses = historiqueConnexionses;
    }
    public Set getHistoriqueStatutsCommandes() {
        return this.historiqueStatutsCommandes;
    }
    
    public void setHistoriqueStatutsCommandes(Set historiqueStatutsCommandes) {
        this.historiqueStatutsCommandes = historiqueStatutsCommandes;
    }
    public Set getRemboursementsesForApprouvePar() {
        return this.remboursementsesForApprouvePar;
    }
    
    public void setRemboursementsesForApprouvePar(Set remboursementsesForApprouvePar) {
        this.remboursementsesForApprouvePar = remboursementsesForApprouvePar;
    }
    public Set getCodesPromotionnelses() {
        return this.codesPromotionnelses;
    }
    
    public void setCodesPromotionnelses(Set codesPromotionnelses) {
        this.codesPromotionnelses = codesPromotionnelses;
    }
    public Set getTemplatesNotificationses() {
        return this.templatesNotificationses;
    }
    
    public void setTemplatesNotificationses(Set templatesNotificationses) {
        this.templatesNotificationses = templatesNotificationses;
    }
    public Set getEvenementsAnalyticses() {
        return this.evenementsAnalyticses;
    }
    
    public void setEvenementsAnalyticses(Set evenementsAnalyticses) {
        this.evenementsAnalyticses = evenementsAnalyticses;
    }
    public Set getPreferencesNotificationses() {
        return this.preferencesNotificationses;
    }
    
    public void setPreferencesNotificationses(Set preferencesNotificationses) {
        this.preferencesNotificationses = preferencesNotificationses;
    }
    public Set getAuditModificationses() {
        return this.auditModificationses;
    }
    
    public void setAuditModificationses(Set auditModificationses) {
        this.auditModificationses = auditModificationses;
    }
    public Set getRemboursementsesForDemandePar() {
        return this.remboursementsesForDemandePar;
    }
    
    public void setRemboursementsesForDemandePar(Set remboursementsesForDemandePar) {
        this.remboursementsesForDemandePar = remboursementsesForDemandePar;
    }
    public Set getHistoriqueRechercheses() {
        return this.historiqueRechercheses;
    }
    
    public void setHistoriqueRechercheses(Set historiqueRechercheses) {
        this.historiqueRechercheses = historiqueRechercheses;
    }
    public Set getCampagnesMarketings() {
        return this.campagnesMarketings;
    }
    
    public void setCampagnesMarketings(Set campagnesMarketings) {
        this.campagnesMarketings = campagnesMarketings;
    }
    public Set getNotificationsEnvoyeeses() {
        return this.notificationsEnvoyeeses;
    }
    
    public void setNotificationsEnvoyeeses(Set notificationsEnvoyeeses) {
        this.notificationsEnvoyeeses = notificationsEnvoyeeses;
    }
    public Set getSessionsActiveses() {
        return this.sessionsActiveses;
    }
    
    public void setSessionsActiveses(Set sessionsActiveses) {
        this.sessionsActiveses = sessionsActiveses;
    }




}


