package model.utilisateur;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;

/**
 * HistoriqueConnexions generated by hbm2java
 */
public class HistoriqueConnexions  implements java.io.Serializable {


     private int id;
     private ComptesUtilisateur comptesUtilisateur;
     private String typeConnexion;
     private String methodeAuth;
     private Timestamp connecteLe;
     private Timestamp deconnecteLe;
     private Serializable dureeSession;
     private Serializable adresseIp;
     private String userAgent;
     private String empreinteAppareil;
     private String appareilType;
     private String navigateur;
     private String systemeExploitation;
     private String paysConnexion;
     private String villeConnexion;
     private Boolean estConnexionSuspecte;
     private String raisonSuspicion;
     private String actionSecuritePrise;
     private Boolean estReussie;
     private String codeErreur;
     private String messageErreur;

    public HistoriqueConnexions() {
    }

	
    public HistoriqueConnexions(int id, ComptesUtilisateur comptesUtilisateur, String typeConnexion) {
        this.id = id;
        this.comptesUtilisateur = comptesUtilisateur;
        this.typeConnexion = typeConnexion;
    }
    public HistoriqueConnexions(int id, ComptesUtilisateur comptesUtilisateur, String typeConnexion, String methodeAuth, Timestamp connecteLe, Timestamp deconnecteLe, Serializable dureeSession, Serializable adresseIp, String userAgent, String empreinteAppareil, String appareilType, String navigateur, String systemeExploitation, String paysConnexion, String villeConnexion, Boolean estConnexionSuspecte, String raisonSuspicion, String actionSecuritePrise, Boolean estReussie, String codeErreur, String messageErreur) {
       this.id = id;
       this.comptesUtilisateur = comptesUtilisateur;
       this.typeConnexion = typeConnexion;
       this.methodeAuth = methodeAuth;
       this.connecteLe = connecteLe;
       this.deconnecteLe = deconnecteLe;
       this.dureeSession = dureeSession;
       this.adresseIp = adresseIp;
       this.userAgent = userAgent;
       this.empreinteAppareil = empreinteAppareil;
       this.appareilType = appareilType;
       this.navigateur = navigateur;
       this.systemeExploitation = systemeExploitation;
       this.paysConnexion = paysConnexion;
       this.villeConnexion = villeConnexion;
       this.estConnexionSuspecte = estConnexionSuspecte;
       this.raisonSuspicion = raisonSuspicion;
       this.actionSecuritePrise = actionSecuritePrise;
       this.estReussie = estReussie;
       this.codeErreur = codeErreur;
       this.messageErreur = messageErreur;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public String getTypeConnexion() {
        return this.typeConnexion;
    }
    
    public void setTypeConnexion(String typeConnexion) {
        this.typeConnexion = typeConnexion;
    }
    public String getMethodeAuth() {
        return this.methodeAuth;
    }
    
    public void setMethodeAuth(String methodeAuth) {
        this.methodeAuth = methodeAuth;
    }
    public Timestamp getConnecteLe() {
        return this.connecteLe;
    }
    
    public void setConnecteLe(Timestamp connecteLe) {
        this.connecteLe = connecteLe;
    }
    public Timestamp getDeconnecteLe() {
        return this.deconnecteLe;
    }
    
    public void setDeconnecteLe(Timestamp deconnecteLe) {
        this.deconnecteLe = deconnecteLe;
    }
    public Serializable getDureeSession() {
        return this.dureeSession;
    }
    
    public void setDureeSession(Serializable dureeSession) {
        this.dureeSession = dureeSession;
    }
    public Serializable getAdresseIp() {
        return this.adresseIp;
    }
    
    public void setAdresseIp(Serializable adresseIp) {
        this.adresseIp = adresseIp;
    }
    public String getUserAgent() {
        return this.userAgent;
    }
    
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }
    public String getEmpreinteAppareil() {
        return this.empreinteAppareil;
    }
    
    public void setEmpreinteAppareil(String empreinteAppareil) {
        this.empreinteAppareil = empreinteAppareil;
    }
    public String getAppareilType() {
        return this.appareilType;
    }
    
    public void setAppareilType(String appareilType) {
        this.appareilType = appareilType;
    }
    public String getNavigateur() {
        return this.navigateur;
    }
    
    public void setNavigateur(String navigateur) {
        this.navigateur = navigateur;
    }
    public String getSystemeExploitation() {
        return this.systemeExploitation;
    }
    
    public void setSystemeExploitation(String systemeExploitation) {
        this.systemeExploitation = systemeExploitation;
    }
    public String getPaysConnexion() {
        return this.paysConnexion;
    }
    
    public void setPaysConnexion(String paysConnexion) {
        this.paysConnexion = paysConnexion;
    }
    public String getVilleConnexion() {
        return this.villeConnexion;
    }
    
    public void setVilleConnexion(String villeConnexion) {
        this.villeConnexion = villeConnexion;
    }
    public Boolean getEstConnexionSuspecte() {
        return this.estConnexionSuspecte;
    }
    
    public void setEstConnexionSuspecte(Boolean estConnexionSuspecte) {
        this.estConnexionSuspecte = estConnexionSuspecte;
    }
    public String getRaisonSuspicion() {
        return this.raisonSuspicion;
    }
    
    public void setRaisonSuspicion(String raisonSuspicion) {
        this.raisonSuspicion = raisonSuspicion;
    }
    public String getActionSecuritePrise() {
        return this.actionSecuritePrise;
    }
    
    public void setActionSecuritePrise(String actionSecuritePrise) {
        this.actionSecuritePrise = actionSecuritePrise;
    }
    public Boolean getEstReussie() {
        return this.estReussie;
    }
    
    public void setEstReussie(Boolean estReussie) {
        this.estReussie = estReussie;
    }
    public String getCodeErreur() {
        return this.codeErreur;
    }
    
    public void setCodeErreur(String codeErreur) {
        this.codeErreur = codeErreur;
    }
    public String getMessageErreur() {
        return this.messageErreur;
    }
    
    public void setMessageErreur(String messageErreur) {
        this.messageErreur = messageErreur;
    }




}


