package model.entreprise;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import model.reference.Pays;
import model.utilisateur.Personnes;

/**
 * Boutiques generated by hbm2java
 */
public class Boutiques  implements java.io.Serializable {


     private int id;
     private Entreprises entreprises;
     private Personnes personnes;
     private Pays pays;
     private Serializable uuid;
     private String nom;
     private String codeBoutique;
     private String description;
     private String slogan;
     private String email;
     private String telephone;
     private String siteWeb;
     private String adresseLigne1;
     private String adresseLigne2;
     private String ville;
     private String region;
     private String codePostal;
     private Serializable coordonneesGps;
     private Serializable horairesOuverture;
     private String logoUrl;
     private String banniereUrl;
     private Serializable photosBoutique;
     private Serializable couleursTheme;
     private String categoriePrincipale;
     private Serializable categoriesSecondaires;
     private Serializable motsClesRecherche;
     private BigDecimal noteMoyenne;
     private Integer nombreEvaluations;
     private Boolean livraisonDisponible;
     private Integer rayonLivraisonKm;
     private BigDecimal fraisLivraison;
     private BigDecimal livraisonGratuiteSeuil;
     private Boolean accepteEspeces;
     private Boolean accepteCarte;
     private Boolean accepteMobileMoney;
     private String stripeAccountId;
     private Serializable contenuRecherche;
     private Serializable tagsRecherche;
     private Serializable parametres;
     private Serializable metadonnees;
     private Boolean estActif;
     private Boolean estVerifie;
     private Boolean estEnLigne;
     private Timestamp derniereActivite;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set evenementsAnalyticses = new HashSet(0);
     private Set employeses = new HashSet(0);
     private Set metriquesQuotidienneses = new HashSet(0);
     private Set produitses = new HashSet(0);
     private Set commandeses = new HashSet(0);
     private Set historiqueRechercheses = new HashSet(0);
     private Set evaluationsBoutiqueses = new HashSet(0);

    public Boutiques() {
    }

	
    public Boutiques(int id, String nom, String adresseLigne1, String ville, Serializable coordonneesGps) {
        this.id = id;
        this.nom = nom;
        this.adresseLigne1 = adresseLigne1;
        this.ville = ville;
        this.coordonneesGps = coordonneesGps;
    }
    public Boutiques(int id, Entreprises entreprises, Personnes personnes, Pays pays, Serializable uuid, String nom, String codeBoutique, String description, String slogan, String email, String telephone, String siteWeb, String adresseLigne1, String adresseLigne2, String ville, String region, String codePostal, Serializable coordonneesGps, Serializable horairesOuverture, String logoUrl, String banniereUrl, Serializable photosBoutique, Serializable couleursTheme, String categoriePrincipale, Serializable categoriesSecondaires, Serializable motsClesRecherche, BigDecimal noteMoyenne, Integer nombreEvaluations, Boolean livraisonDisponible, Integer rayonLivraisonKm, BigDecimal fraisLivraison, BigDecimal livraisonGratuiteSeuil, Boolean accepteEspeces, Boolean accepteCarte, Boolean accepteMobileMoney, String stripeAccountId, Serializable contenuRecherche, Serializable tagsRecherche, Serializable parametres, Serializable metadonnees, Boolean estActif, Boolean estVerifie, Boolean estEnLigne, Timestamp derniereActivite, Timestamp creeLe, Timestamp modifieLe, Set evenementsAnalyticses, Set employeses, Set metriquesQuotidienneses, Set produitses, Set commandeses, Set historiqueRechercheses, Set evaluationsBoutiqueses) {
       this.id = id;
       this.entreprises = entreprises;
       this.personnes = personnes;
       this.pays = pays;
       this.uuid = uuid;
       this.nom = nom;
       this.codeBoutique = codeBoutique;
       this.description = description;
       this.slogan = slogan;
       this.email = email;
       this.telephone = telephone;
       this.siteWeb = siteWeb;
       this.adresseLigne1 = adresseLigne1;
       this.adresseLigne2 = adresseLigne2;
       this.ville = ville;
       this.region = region;
       this.codePostal = codePostal;
       this.coordonneesGps = coordonneesGps;
       this.horairesOuverture = horairesOuverture;
       this.logoUrl = logoUrl;
       this.banniereUrl = banniereUrl;
       this.photosBoutique = photosBoutique;
       this.couleursTheme = couleursTheme;
       this.categoriePrincipale = categoriePrincipale;
       this.categoriesSecondaires = categoriesSecondaires;
       this.motsClesRecherche = motsClesRecherche;
       this.noteMoyenne = noteMoyenne;
       this.nombreEvaluations = nombreEvaluations;
       this.livraisonDisponible = livraisonDisponible;
       this.rayonLivraisonKm = rayonLivraisonKm;
       this.fraisLivraison = fraisLivraison;
       this.livraisonGratuiteSeuil = livraisonGratuiteSeuil;
       this.accepteEspeces = accepteEspeces;
       this.accepteCarte = accepteCarte;
       this.accepteMobileMoney = accepteMobileMoney;
       this.stripeAccountId = stripeAccountId;
       this.contenuRecherche = contenuRecherche;
       this.tagsRecherche = tagsRecherche;
       this.parametres = parametres;
       this.metadonnees = metadonnees;
       this.estActif = estActif;
       this.estVerifie = estVerifie;
       this.estEnLigne = estEnLigne;
       this.derniereActivite = derniereActivite;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.evenementsAnalyticses = evenementsAnalyticses;
       this.employeses = employeses;
       this.metriquesQuotidienneses = metriquesQuotidienneses;
       this.produitses = produitses;
       this.commandeses = commandeses;
       this.historiqueRechercheses = historiqueRechercheses;
       this.evaluationsBoutiqueses = evaluationsBoutiqueses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Entreprises getEntreprises() {
        return this.entreprises;
    }
    
    public void setEntreprises(Entreprises entreprises) {
        this.entreprises = entreprises;
    }
    public Personnes getPersonnes() {
        return this.personnes;
    }
    
    public void setPersonnes(Personnes personnes) {
        this.personnes = personnes;
    }
    public Pays getPays() {
        return this.pays;
    }
    
    public void setPays(Pays pays) {
        this.pays = pays;
    }
    public Serializable getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Serializable uuid) {
        this.uuid = uuid;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getCodeBoutique() {
        return this.codeBoutique;
    }
    
    public void setCodeBoutique(String codeBoutique) {
        this.codeBoutique = codeBoutique;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getSlogan() {
        return this.slogan;
    }
    
    public void setSlogan(String slogan) {
        this.slogan = slogan;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getSiteWeb() {
        return this.siteWeb;
    }
    
    public void setSiteWeb(String siteWeb) {
        this.siteWeb = siteWeb;
    }
    public String getAdresseLigne1() {
        return this.adresseLigne1;
    }
    
    public void setAdresseLigne1(String adresseLigne1) {
        this.adresseLigne1 = adresseLigne1;
    }
    public String getAdresseLigne2() {
        return this.adresseLigne2;
    }
    
    public void setAdresseLigne2(String adresseLigne2) {
        this.adresseLigne2 = adresseLigne2;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getCodePostal() {
        return this.codePostal;
    }
    
    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }
    public Serializable getCoordonneesGps() {
        return this.coordonneesGps;
    }
    
    public void setCoordonneesGps(Serializable coordonneesGps) {
        this.coordonneesGps = coordonneesGps;
    }
    public Serializable getHorairesOuverture() {
        return this.horairesOuverture;
    }
    
    public void setHorairesOuverture(Serializable horairesOuverture) {
        this.horairesOuverture = horairesOuverture;
    }
    public String getLogoUrl() {
        return this.logoUrl;
    }
    
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
    public String getBanniereUrl() {
        return this.banniereUrl;
    }
    
    public void setBanniereUrl(String banniereUrl) {
        this.banniereUrl = banniereUrl;
    }
    public Serializable getPhotosBoutique() {
        return this.photosBoutique;
    }
    
    public void setPhotosBoutique(Serializable photosBoutique) {
        this.photosBoutique = photosBoutique;
    }
    public Serializable getCouleursTheme() {
        return this.couleursTheme;
    }
    
    public void setCouleursTheme(Serializable couleursTheme) {
        this.couleursTheme = couleursTheme;
    }
    public String getCategoriePrincipale() {
        return this.categoriePrincipale;
    }
    
    public void setCategoriePrincipale(String categoriePrincipale) {
        this.categoriePrincipale = categoriePrincipale;
    }
    public Serializable getCategoriesSecondaires() {
        return this.categoriesSecondaires;
    }
    
    public void setCategoriesSecondaires(Serializable categoriesSecondaires) {
        this.categoriesSecondaires = categoriesSecondaires;
    }
    public Serializable getMotsClesRecherche() {
        return this.motsClesRecherche;
    }
    
    public void setMotsClesRecherche(Serializable motsClesRecherche) {
        this.motsClesRecherche = motsClesRecherche;
    }
    public BigDecimal getNoteMoyenne() {
        return this.noteMoyenne;
    }
    
    public void setNoteMoyenne(BigDecimal noteMoyenne) {
        this.noteMoyenne = noteMoyenne;
    }
    public Integer getNombreEvaluations() {
        return this.nombreEvaluations;
    }
    
    public void setNombreEvaluations(Integer nombreEvaluations) {
        this.nombreEvaluations = nombreEvaluations;
    }
    public Boolean getLivraisonDisponible() {
        return this.livraisonDisponible;
    }
    
    public void setLivraisonDisponible(Boolean livraisonDisponible) {
        this.livraisonDisponible = livraisonDisponible;
    }
    public Integer getRayonLivraisonKm() {
        return this.rayonLivraisonKm;
    }
    
    public void setRayonLivraisonKm(Integer rayonLivraisonKm) {
        this.rayonLivraisonKm = rayonLivraisonKm;
    }
    public BigDecimal getFraisLivraison() {
        return this.fraisLivraison;
    }
    
    public void setFraisLivraison(BigDecimal fraisLivraison) {
        this.fraisLivraison = fraisLivraison;
    }
    public BigDecimal getLivraisonGratuiteSeuil() {
        return this.livraisonGratuiteSeuil;
    }
    
    public void setLivraisonGratuiteSeuil(BigDecimal livraisonGratuiteSeuil) {
        this.livraisonGratuiteSeuil = livraisonGratuiteSeuil;
    }
    public Boolean getAccepteEspeces() {
        return this.accepteEspeces;
    }
    
    public void setAccepteEspeces(Boolean accepteEspeces) {
        this.accepteEspeces = accepteEspeces;
    }
    public Boolean getAccepteCarte() {
        return this.accepteCarte;
    }
    
    public void setAccepteCarte(Boolean accepteCarte) {
        this.accepteCarte = accepteCarte;
    }
    public Boolean getAccepteMobileMoney() {
        return this.accepteMobileMoney;
    }
    
    public void setAccepteMobileMoney(Boolean accepteMobileMoney) {
        this.accepteMobileMoney = accepteMobileMoney;
    }
    public String getStripeAccountId() {
        return this.stripeAccountId;
    }
    
    public void setStripeAccountId(String stripeAccountId) {
        this.stripeAccountId = stripeAccountId;
    }
    public Serializable getContenuRecherche() {
        return this.contenuRecherche;
    }
    
    public void setContenuRecherche(Serializable contenuRecherche) {
        this.contenuRecherche = contenuRecherche;
    }
    public Serializable getTagsRecherche() {
        return this.tagsRecherche;
    }
    
    public void setTagsRecherche(Serializable tagsRecherche) {
        this.tagsRecherche = tagsRecherche;
    }
    public Serializable getParametres() {
        return this.parametres;
    }
    
    public void setParametres(Serializable parametres) {
        this.parametres = parametres;
    }
    public Serializable getMetadonnees() {
        return this.metadonnees;
    }
    
    public void setMetadonnees(Serializable metadonnees) {
        this.metadonnees = metadonnees;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Boolean getEstVerifie() {
        return this.estVerifie;
    }
    
    public void setEstVerifie(Boolean estVerifie) {
        this.estVerifie = estVerifie;
    }
    public Boolean getEstEnLigne() {
        return this.estEnLigne;
    }
    
    public void setEstEnLigne(Boolean estEnLigne) {
        this.estEnLigne = estEnLigne;
    }
    public Timestamp getDerniereActivite() {
        return this.derniereActivite;
    }
    
    public void setDerniereActivite(Timestamp derniereActivite) {
        this.derniereActivite = derniereActivite;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getEvenementsAnalyticses() {
        return this.evenementsAnalyticses;
    }
    
    public void setEvenementsAnalyticses(Set evenementsAnalyticses) {
        this.evenementsAnalyticses = evenementsAnalyticses;
    }
    public Set getEmployeses() {
        return this.employeses;
    }
    
    public void setEmployeses(Set employeses) {
        this.employeses = employeses;
    }
    public Set getMetriquesQuotidienneses() {
        return this.metriquesQuotidienneses;
    }
    
    public void setMetriquesQuotidienneses(Set metriquesQuotidienneses) {
        this.metriquesQuotidienneses = metriquesQuotidienneses;
    }
    public Set getProduitses() {
        return this.produitses;
    }
    
    public void setProduitses(Set produitses) {
        this.produitses = produitses;
    }
    public Set getCommandeses() {
        return this.commandeses;
    }
    
    public void setCommandeses(Set commandeses) {
        this.commandeses = commandeses;
    }
    public Set getHistoriqueRechercheses() {
        return this.historiqueRechercheses;
    }
    
    public void setHistoriqueRechercheses(Set historiqueRechercheses) {
        this.historiqueRechercheses = historiqueRechercheses;
    }
    public Set getEvaluationsBoutiqueses() {
        return this.evaluationsBoutiqueses;
    }
    
    public void setEvaluationsBoutiqueses(Set evaluationsBoutiqueses) {
        this.evaluationsBoutiqueses = evaluationsBoutiqueses;
    }




}


