package model.entreprise;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import model.utilisateur.Personnes;

/**
 * Employes generated by hbm2java
 */
public class Employes  implements java.io.Serializable {


     private int id;
     private Boutiques boutiques;
     private Entreprises entreprises;
     private Personnes personnes;
     private String numeroEmploye;
     private String poste;
     private String departement;
     private Integer niveauAcces;
     private Date dateEmbauche;
     private Date dateFinContrat;
     private Timestamp derniereConnexion;
     private Boolean peutVendre;
     private Boolean peutGererStock;
     private Boolean peutVoirRapports;
     private Boolean peutModifierPrix;
     private Serializable permissionsSupplementaires;
     private Boolean estActif;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set mouvementsStocks = new HashSet(0);
     private Set livraisonses = new HashSet(0);

    public Employes() {
    }

	
    public Employes(int id, Personnes personnes, String poste, Date dateEmbauche) {
        this.id = id;
        this.personnes = personnes;
        this.poste = poste;
        this.dateEmbauche = dateEmbauche;
    }
    public Employes(int id, Boutiques boutiques, Entreprises entreprises, Personnes personnes, String numeroEmploye, String poste, String departement, Integer niveauAcces, Date dateEmbauche, Date dateFinContrat, Timestamp derniereConnexion, Boolean peutVendre, Boolean peutGererStock, Boolean peutVoirRapports, Boolean peutModifierPrix, Serializable permissionsSupplementaires, Boolean estActif, Timestamp creeLe, Timestamp modifieLe, Set mouvementsStocks, Set livraisonses) {
       this.id = id;
       this.boutiques = boutiques;
       this.entreprises = entreprises;
       this.personnes = personnes;
       this.numeroEmploye = numeroEmploye;
       this.poste = poste;
       this.departement = departement;
       this.niveauAcces = niveauAcces;
       this.dateEmbauche = dateEmbauche;
       this.dateFinContrat = dateFinContrat;
       this.derniereConnexion = derniereConnexion;
       this.peutVendre = peutVendre;
       this.peutGererStock = peutGererStock;
       this.peutVoirRapports = peutVoirRapports;
       this.peutModifierPrix = peutModifierPrix;
       this.permissionsSupplementaires = permissionsSupplementaires;
       this.estActif = estActif;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.mouvementsStocks = mouvementsStocks;
       this.livraisonses = livraisonses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Boutiques getBoutiques() {
        return this.boutiques;
    }
    
    public void setBoutiques(Boutiques boutiques) {
        this.boutiques = boutiques;
    }
    public Entreprises getEntreprises() {
        return this.entreprises;
    }
    
    public void setEntreprises(Entreprises entreprises) {
        this.entreprises = entreprises;
    }
    public Personnes getPersonnes() {
        return this.personnes;
    }
    
    public void setPersonnes(Personnes personnes) {
        this.personnes = personnes;
    }
    public String getNumeroEmploye() {
        return this.numeroEmploye;
    }
    
    public void setNumeroEmploye(String numeroEmploye) {
        this.numeroEmploye = numeroEmploye;
    }
    public String getPoste() {
        return this.poste;
    }
    
    public void setPoste(String poste) {
        this.poste = poste;
    }
    public String getDepartement() {
        return this.departement;
    }
    
    public void setDepartement(String departement) {
        this.departement = departement;
    }
    public Integer getNiveauAcces() {
        return this.niveauAcces;
    }
    
    public void setNiveauAcces(Integer niveauAcces) {
        this.niveauAcces = niveauAcces;
    }
    public Date getDateEmbauche() {
        return this.dateEmbauche;
    }
    
    public void setDateEmbauche(Date dateEmbauche) {
        this.dateEmbauche = dateEmbauche;
    }
    public Date getDateFinContrat() {
        return this.dateFinContrat;
    }
    
    public void setDateFinContrat(Date dateFinContrat) {
        this.dateFinContrat = dateFinContrat;
    }
    public Timestamp getDerniereConnexion() {
        return this.derniereConnexion;
    }
    
    public void setDerniereConnexion(Timestamp derniereConnexion) {
        this.derniereConnexion = derniereConnexion;
    }
    public Boolean getPeutVendre() {
        return this.peutVendre;
    }
    
    public void setPeutVendre(Boolean peutVendre) {
        this.peutVendre = peutVendre;
    }
    public Boolean getPeutGererStock() {
        return this.peutGererStock;
    }
    
    public void setPeutGererStock(Boolean peutGererStock) {
        this.peutGererStock = peutGererStock;
    }
    public Boolean getPeutVoirRapports() {
        return this.peutVoirRapports;
    }
    
    public void setPeutVoirRapports(Boolean peutVoirRapports) {
        this.peutVoirRapports = peutVoirRapports;
    }
    public Boolean getPeutModifierPrix() {
        return this.peutModifierPrix;
    }
    
    public void setPeutModifierPrix(Boolean peutModifierPrix) {
        this.peutModifierPrix = peutModifierPrix;
    }
    public Serializable getPermissionsSupplementaires() {
        return this.permissionsSupplementaires;
    }
    
    public void setPermissionsSupplementaires(Serializable permissionsSupplementaires) {
        this.permissionsSupplementaires = permissionsSupplementaires;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getMouvementsStocks() {
        return this.mouvementsStocks;
    }
    
    public void setMouvementsStocks(Set mouvementsStocks) {
        this.mouvementsStocks = mouvementsStocks;
    }
    public Set getLivraisonses() {
        return this.livraisonses;
    }
    
    public void setLivraisonses(Set livraisonses) {
        this.livraisonses = livraisonses;
    }




}


