package model.entreprise;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import model.reference.Devises;
import model.reference.Pays;

/**
 * Entreprises generated by hbm2java
 */
public class Entreprises  implements java.io.Serializable {


     private int id;
     private Devises devises;
     private Pays pays;
     private Serializable uuid;
     private String nom;
     private String nomLegal;
     private String numeroEnregistrement;
     private String numeroFiscal;
     private String codeEntreprise;
     private String email;
     private String telephone;
     private String siteWeb;
     private String adresseLigne1;
     private String adresseLigne2;
     private String ville;
     private String region;
     private String codePostal;
     private Serializable coordonneesGps;
     private String secteurActivite;
     private Integer nombreEmployes;
     private Integer anneeCreation;
     private BigDecimal chiffreAffaires;
     private String logoUrl;
     private Serializable couleursMarque;
     private String fuseauHoraire;
     private String langueParDefaut;
     private Serializable parametres;
     private Boolean estActif;
     private Boolean estVerifie;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set boutiqueses = new HashSet(0);
     private Set employeses = new HashSet(0);

    public Entreprises() {
    }

	
    public Entreprises(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public Entreprises(int id, Devises devises, Pays pays, Serializable uuid, String nom, String nomLegal, String numeroEnregistrement, String numeroFiscal, String codeEntreprise, String email, String telephone, String siteWeb, String adresseLigne1, String adresseLigne2, String ville, String region, String codePostal, Serializable coordonneesGps, String secteurActivite, Integer nombreEmployes, Integer anneeCreation, BigDecimal chiffreAffaires, String logoUrl, Serializable couleursMarque, String fuseauHoraire, String langueParDefaut, Serializable parametres, Boolean estActif, Boolean estVerifie, Timestamp creeLe, Timestamp modifieLe, Set boutiqueses, Set employeses) {
       this.id = id;
       this.devises = devises;
       this.pays = pays;
       this.uuid = uuid;
       this.nom = nom;
       this.nomLegal = nomLegal;
       this.numeroEnregistrement = numeroEnregistrement;
       this.numeroFiscal = numeroFiscal;
       this.codeEntreprise = codeEntreprise;
       this.email = email;
       this.telephone = telephone;
       this.siteWeb = siteWeb;
       this.adresseLigne1 = adresseLigne1;
       this.adresseLigne2 = adresseLigne2;
       this.ville = ville;
       this.region = region;
       this.codePostal = codePostal;
       this.coordonneesGps = coordonneesGps;
       this.secteurActivite = secteurActivite;
       this.nombreEmployes = nombreEmployes;
       this.anneeCreation = anneeCreation;
       this.chiffreAffaires = chiffreAffaires;
       this.logoUrl = logoUrl;
       this.couleursMarque = couleursMarque;
       this.fuseauHoraire = fuseauHoraire;
       this.langueParDefaut = langueParDefaut;
       this.parametres = parametres;
       this.estActif = estActif;
       this.estVerifie = estVerifie;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.boutiqueses = boutiqueses;
       this.employeses = employeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Devises getDevises() {
        return this.devises;
    }
    
    public void setDevises(Devises devises) {
        this.devises = devises;
    }
    public Pays getPays() {
        return this.pays;
    }
    
    public void setPays(Pays pays) {
        this.pays = pays;
    }
    public Serializable getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Serializable uuid) {
        this.uuid = uuid;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getNomLegal() {
        return this.nomLegal;
    }
    
    public void setNomLegal(String nomLegal) {
        this.nomLegal = nomLegal;
    }
    public String getNumeroEnregistrement() {
        return this.numeroEnregistrement;
    }
    
    public void setNumeroEnregistrement(String numeroEnregistrement) {
        this.numeroEnregistrement = numeroEnregistrement;
    }
    public String getNumeroFiscal() {
        return this.numeroFiscal;
    }
    
    public void setNumeroFiscal(String numeroFiscal) {
        this.numeroFiscal = numeroFiscal;
    }
    public String getCodeEntreprise() {
        return this.codeEntreprise;
    }
    
    public void setCodeEntreprise(String codeEntreprise) {
        this.codeEntreprise = codeEntreprise;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getSiteWeb() {
        return this.siteWeb;
    }
    
    public void setSiteWeb(String siteWeb) {
        this.siteWeb = siteWeb;
    }
    public String getAdresseLigne1() {
        return this.adresseLigne1;
    }
    
    public void setAdresseLigne1(String adresseLigne1) {
        this.adresseLigne1 = adresseLigne1;
    }
    public String getAdresseLigne2() {
        return this.adresseLigne2;
    }
    
    public void setAdresseLigne2(String adresseLigne2) {
        this.adresseLigne2 = adresseLigne2;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getCodePostal() {
        return this.codePostal;
    }
    
    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }
    public Serializable getCoordonneesGps() {
        return this.coordonneesGps;
    }
    
    public void setCoordonneesGps(Serializable coordonneesGps) {
        this.coordonneesGps = coordonneesGps;
    }
    public String getSecteurActivite() {
        return this.secteurActivite;
    }
    
    public void setSecteurActivite(String secteurActivite) {
        this.secteurActivite = secteurActivite;
    }
    public Integer getNombreEmployes() {
        return this.nombreEmployes;
    }
    
    public void setNombreEmployes(Integer nombreEmployes) {
        this.nombreEmployes = nombreEmployes;
    }
    public Integer getAnneeCreation() {
        return this.anneeCreation;
    }
    
    public void setAnneeCreation(Integer anneeCreation) {
        this.anneeCreation = anneeCreation;
    }
    public BigDecimal getChiffreAffaires() {
        return this.chiffreAffaires;
    }
    
    public void setChiffreAffaires(BigDecimal chiffreAffaires) {
        this.chiffreAffaires = chiffreAffaires;
    }
    public String getLogoUrl() {
        return this.logoUrl;
    }
    
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
    public Serializable getCouleursMarque() {
        return this.couleursMarque;
    }
    
    public void setCouleursMarque(Serializable couleursMarque) {
        this.couleursMarque = couleursMarque;
    }
    public String getFuseauHoraire() {
        return this.fuseauHoraire;
    }
    
    public void setFuseauHoraire(String fuseauHoraire) {
        this.fuseauHoraire = fuseauHoraire;
    }
    public String getLangueParDefaut() {
        return this.langueParDefaut;
    }
    
    public void setLangueParDefaut(String langueParDefaut) {
        this.langueParDefaut = langueParDefaut;
    }
    public Serializable getParametres() {
        return this.parametres;
    }
    
    public void setParametres(Serializable parametres) {
        this.parametres = parametres;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Boolean getEstVerifie() {
        return this.estVerifie;
    }
    
    public void setEstVerifie(Boolean estVerifie) {
        this.estVerifie = estVerifie;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getBoutiqueses() {
        return this.boutiqueses;
    }
    
    public void setBoutiqueses(Set boutiqueses) {
        this.boutiqueses = boutiqueses;
    }
    public Set getEmployeses() {
        return this.employeses;
    }
    
    public void setEmployeses(Set employeses) {
        this.employeses = employeses;
    }




}


