package model.securite;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;

import model.utilisateur.ComptesUtilisateur;

/**
 * AuditModifications generated by hbm2java
 */
public class AuditModifications  implements java.io.Serializable {


     private int id;
     private ComptesUtilisateur comptesUtilisateur;
     private String tableConcernee;
     private int idEnregistrement;
     private String operation;
     private Timestamp modifieLe;
     private Serializable adresseIp;
     private Serializable donneesAvant;
     private Serializable donneesApres;
     private Serializable champsModifies;
     private String raisonModification;
     private String sessionId;

    public AuditModifications() {
    }

	
    public AuditModifications(int id, String tableConcernee, int idEnregistrement, String operation) {
        this.id = id;
        this.tableConcernee = tableConcernee;
        this.idEnregistrement = idEnregistrement;
        this.operation = operation;
    }
    public AuditModifications(int id, ComptesUtilisateur comptesUtilisateur, String tableConcernee, int idEnregistrement, String operation, Timestamp modifieLe, Serializable adresseIp, Serializable donneesAvant, Serializable donneesApres, Serializable champsModifies, String raisonModification, String sessionId) {
       this.id = id;
       this.comptesUtilisateur = comptesUtilisateur;
       this.tableConcernee = tableConcernee;
       this.idEnregistrement = idEnregistrement;
       this.operation = operation;
       this.modifieLe = modifieLe;
       this.adresseIp = adresseIp;
       this.donneesAvant = donneesAvant;
       this.donneesApres = donneesApres;
       this.champsModifies = champsModifies;
       this.raisonModification = raisonModification;
       this.sessionId = sessionId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public String getTableConcernee() {
        return this.tableConcernee;
    }
    
    public void setTableConcernee(String tableConcernee) {
        this.tableConcernee = tableConcernee;
    }
    public int getIdEnregistrement() {
        return this.idEnregistrement;
    }
    
    public void setIdEnregistrement(int idEnregistrement) {
        this.idEnregistrement = idEnregistrement;
    }
    public String getOperation() {
        return this.operation;
    }
    
    public void setOperation(String operation) {
        this.operation = operation;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Serializable getAdresseIp() {
        return this.adresseIp;
    }
    
    public void setAdresseIp(Serializable adresseIp) {
        this.adresseIp = adresseIp;
    }
    public Serializable getDonneesAvant() {
        return this.donneesAvant;
    }
    
    public void setDonneesAvant(Serializable donneesAvant) {
        this.donneesAvant = donneesAvant;
    }
    public Serializable getDonneesApres() {
        return this.donneesApres;
    }
    
    public void setDonneesApres(Serializable donneesApres) {
        this.donneesApres = donneesApres;
    }
    public Serializable getChampsModifies() {
        return this.champsModifies;
    }
    
    public void setChampsModifies(Serializable champsModifies) {
        this.champsModifies = champsModifies;
    }
    public String getRaisonModification() {
        return this.raisonModification;
    }
    
    public void setRaisonModification(String raisonModification) {
        this.raisonModification = raisonModification;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }




}


