package model.securite;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;

import model.utilisateur.ComptesUtilisateur;

/**
 * LogsSysteme generated by hbm2java
 */
public class LogsSysteme  implements java.io.Serializable {


     private int id;
     private ComptesUtilisateur comptesUtilisateur;
     private String niveau;
     private String module;
     private String action;
     private String sessionId;
     private Serializable adresseIp;
     private String message;
     private Serializable donnees;
     private String stackTrace;
     private Integer dureeExecution;
     private Integer memoireUtilisee;
     private Timestamp timestampLog;

    public LogsSysteme() {
    }

	
    public LogsSysteme(int id, String niveau, String module, String action, String message) {
        this.id = id;
        this.niveau = niveau;
        this.module = module;
        this.action = action;
        this.message = message;
    }
    public LogsSysteme(int id, ComptesUtilisateur comptesUtilisateur, String niveau, String module, String action, String sessionId, Serializable adresseIp, String message, Serializable donnees, String stackTrace, Integer dureeExecution, Integer memoireUtilisee, Timestamp timestampLog) {
       this.id = id;
       this.comptesUtilisateur = comptesUtilisateur;
       this.niveau = niveau;
       this.module = module;
       this.action = action;
       this.sessionId = sessionId;
       this.adresseIp = adresseIp;
       this.message = message;
       this.donnees = donnees;
       this.stackTrace = stackTrace;
       this.dureeExecution = dureeExecution;
       this.memoireUtilisee = memoireUtilisee;
       this.timestampLog = timestampLog;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public String getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(String niveau) {
        this.niveau = niveau;
    }
    public String getModule() {
        return this.module;
    }
    
    public void setModule(String module) {
        this.module = module;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public Serializable getAdresseIp() {
        return this.adresseIp;
    }
    
    public void setAdresseIp(Serializable adresseIp) {
        this.adresseIp = adresseIp;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Serializable getDonnees() {
        return this.donnees;
    }
    
    public void setDonnees(Serializable donnees) {
        this.donnees = donnees;
    }
    public String getStackTrace() {
        return this.stackTrace;
    }
    
    public void setStackTrace(String stackTrace) {
        this.stackTrace = stackTrace;
    }
    public Integer getDureeExecution() {
        return this.dureeExecution;
    }
    
    public void setDureeExecution(Integer dureeExecution) {
        this.dureeExecution = dureeExecution;
    }
    public Integer getMemoireUtilisee() {
        return this.memoireUtilisee;
    }
    
    public void setMemoireUtilisee(Integer memoireUtilisee) {
        this.memoireUtilisee = memoireUtilisee;
    }
    public Timestamp getTimestampLog() {
        return this.timestampLog;
    }
    
    public void setTimestampLog(Timestamp timestampLog) {
        this.timestampLog = timestampLog;
    }




}


