package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * ArticlesPanier generated by hbm2java
 */
public class ArticlesPanier  implements java.io.Serializable {


     private int id;
     private Produits produits;
     private Paniers paniers;
     private int quantite;
     private BigDecimal prixUnitaire;
     private BigDecimal prixTotal;
     private Serializable variationsSelectionnees;
     private String notesClient;
     private Timestamp ajouteLe;
     private Timestamp modifieLe;

    public ArticlesPanier() {
    }

	
    public ArticlesPanier(int id, Produits produits, Paniers paniers, int quantite, BigDecimal prixUnitaire, BigDecimal prixTotal) {
        this.id = id;
        this.produits = produits;
        this.paniers = paniers;
        this.quantite = quantite;
        this.prixUnitaire = prixUnitaire;
        this.prixTotal = prixTotal;
    }
    public ArticlesPanier(int id, Produits produits, Paniers paniers, int quantite, BigDecimal prixUnitaire, BigDecimal prixTotal, Serializable variationsSelectionnees, String notesClient, Timestamp ajouteLe, Timestamp modifieLe) {
       this.id = id;
       this.produits = produits;
       this.paniers = paniers;
       this.quantite = quantite;
       this.prixUnitaire = prixUnitaire;
       this.prixTotal = prixTotal;
       this.variationsSelectionnees = variationsSelectionnees;
       this.notesClient = notesClient;
       this.ajouteLe = ajouteLe;
       this.modifieLe = modifieLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public Paniers getPaniers() {
        return this.paniers;
    }
    
    public void setPaniers(Paniers paniers) {
        this.paniers = paniers;
    }
    public int getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(int quantite) {
        this.quantite = quantite;
    }
    public BigDecimal getPrixUnitaire() {
        return this.prixUnitaire;
    }
    
    public void setPrixUnitaire(BigDecimal prixUnitaire) {
        this.prixUnitaire = prixUnitaire;
    }
    public BigDecimal getPrixTotal() {
        return this.prixTotal;
    }
    
    public void setPrixTotal(BigDecimal prixTotal) {
        this.prixTotal = prixTotal;
    }
    public Serializable getVariationsSelectionnees() {
        return this.variationsSelectionnees;
    }
    
    public void setVariationsSelectionnees(Serializable variationsSelectionnees) {
        this.variationsSelectionnees = variationsSelectionnees;
    }
    public String getNotesClient() {
        return this.notesClient;
    }
    
    public void setNotesClient(String notesClient) {
        this.notesClient = notesClient;
    }
    public Timestamp getAjouteLe() {
        return this.ajouteLe;
    }
    
    public void setAjouteLe(Timestamp ajouteLe) {
        this.ajouteLe = ajouteLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }




}


