package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Commandes generated by hbm2java
 */
public class Commandes  implements java.io.Serializable {


     private int id;
     private Boutiques boutiques;
     private Devises devises;
     private StatutsCommande statutsCommande;
     private Clients clients;
     private Serializable uuid;
     private String numeroCommande;
     private BigDecimal sousTotal;
     private BigDecimal montantTva;
     private BigDecimal fraisLivraison;
     private BigDecimal montantRemise;
     private BigDecimal totalCommande;
     private String codePromoUtilise;
     private BigDecimal remisePourcentage;
     private BigDecimal remiseMontant;
     private Serializable adresseLivraison;
     private Serializable coordonneesLivraison;
     private String instructionsLivraison;
     private Timestamp dateCommande;
     private Timestamp dateConfirmation;
     private Timestamp datePreparation;
     private Timestamp dateExpedition;
     private Timestamp dateLivraisonPrevue;
     private Timestamp dateLivraisonReelle;
     private String numeroSuivi;
     private String transporteur;
     private String modePaiement;
     private String statutPaiement;
     private String transactionStripeId;
     private String transactionExterneId;
     private Boolean emailConfirmationEnvoye;
     private Boolean smsConfirmationEnvoye;
     private Serializable notificationsEnvoyees;
     private String canalCommande;
     private String appareilCommande;
     private String navigateurCommande;
     private String notesClient;
     private String notesInterne;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set articlesCommandes = new HashSet(0);
     private Set livraisonses = new HashSet(0);
     private Set evaluationsBoutiqueses = new HashSet(0);
     private Set evaluationsProduitses = new HashSet(0);
     private Set historiqueStatutsCommandes = new HashSet(0);
     private Set remboursementses = new HashSet(0);
     private Set transactionsPaiements = new HashSet(0);
     private Set utilisationsCodesPromos = new HashSet(0);

    public Commandes() {
    }

	
    public Commandes(int id, Boutiques boutiques, StatutsCommande statutsCommande, Clients clients, String numeroCommande, BigDecimal sousTotal, BigDecimal totalCommande, Serializable adresseLivraison) {
        this.id = id;
        this.boutiques = boutiques;
        this.statutsCommande = statutsCommande;
        this.clients = clients;
        this.numeroCommande = numeroCommande;
        this.sousTotal = sousTotal;
        this.totalCommande = totalCommande;
        this.adresseLivraison = adresseLivraison;
    }
    public Commandes(int id, Boutiques boutiques, Devises devises, StatutsCommande statutsCommande, Clients clients, Serializable uuid, String numeroCommande, BigDecimal sousTotal, BigDecimal montantTva, BigDecimal fraisLivraison, BigDecimal montantRemise, BigDecimal totalCommande, String codePromoUtilise, BigDecimal remisePourcentage, BigDecimal remiseMontant, Serializable adresseLivraison, Serializable coordonneesLivraison, String instructionsLivraison, Timestamp dateCommande, Timestamp dateConfirmation, Timestamp datePreparation, Timestamp dateExpedition, Timestamp dateLivraisonPrevue, Timestamp dateLivraisonReelle, String numeroSuivi, String transporteur, String modePaiement, String statutPaiement, String transactionStripeId, String transactionExterneId, Boolean emailConfirmationEnvoye, Boolean smsConfirmationEnvoye, Serializable notificationsEnvoyees, String canalCommande, String appareilCommande, String navigateurCommande, String notesClient, String notesInterne, Timestamp creeLe, Timestamp modifieLe, Set articlesCommandes, Set livraisonses, Set evaluationsBoutiqueses, Set evaluationsProduitses, Set historiqueStatutsCommandes, Set remboursementses, Set transactionsPaiements, Set utilisationsCodesPromos) {
       this.id = id;
       this.boutiques = boutiques;
       this.devises = devises;
       this.statutsCommande = statutsCommande;
       this.clients = clients;
       this.uuid = uuid;
       this.numeroCommande = numeroCommande;
       this.sousTotal = sousTotal;
       this.montantTva = montantTva;
       this.fraisLivraison = fraisLivraison;
       this.montantRemise = montantRemise;
       this.totalCommande = totalCommande;
       this.codePromoUtilise = codePromoUtilise;
       this.remisePourcentage = remisePourcentage;
       this.remiseMontant = remiseMontant;
       this.adresseLivraison = adresseLivraison;
       this.coordonneesLivraison = coordonneesLivraison;
       this.instructionsLivraison = instructionsLivraison;
       this.dateCommande = dateCommande;
       this.dateConfirmation = dateConfirmation;
       this.datePreparation = datePreparation;
       this.dateExpedition = dateExpedition;
       this.dateLivraisonPrevue = dateLivraisonPrevue;
       this.dateLivraisonReelle = dateLivraisonReelle;
       this.numeroSuivi = numeroSuivi;
       this.transporteur = transporteur;
       this.modePaiement = modePaiement;
       this.statutPaiement = statutPaiement;
       this.transactionStripeId = transactionStripeId;
       this.transactionExterneId = transactionExterneId;
       this.emailConfirmationEnvoye = emailConfirmationEnvoye;
       this.smsConfirmationEnvoye = smsConfirmationEnvoye;
       this.notificationsEnvoyees = notificationsEnvoyees;
       this.canalCommande = canalCommande;
       this.appareilCommande = appareilCommande;
       this.navigateurCommande = navigateurCommande;
       this.notesClient = notesClient;
       this.notesInterne = notesInterne;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.articlesCommandes = articlesCommandes;
       this.livraisonses = livraisonses;
       this.evaluationsBoutiqueses = evaluationsBoutiqueses;
       this.evaluationsProduitses = evaluationsProduitses;
       this.historiqueStatutsCommandes = historiqueStatutsCommandes;
       this.remboursementses = remboursementses;
       this.transactionsPaiements = transactionsPaiements;
       this.utilisationsCodesPromos = utilisationsCodesPromos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Boutiques getBoutiques() {
        return this.boutiques;
    }
    
    public void setBoutiques(Boutiques boutiques) {
        this.boutiques = boutiques;
    }
    public Devises getDevises() {
        return this.devises;
    }
    
    public void setDevises(Devises devises) {
        this.devises = devises;
    }
    public StatutsCommande getStatutsCommande() {
        return this.statutsCommande;
    }
    
    public void setStatutsCommande(StatutsCommande statutsCommande) {
        this.statutsCommande = statutsCommande;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public Serializable getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Serializable uuid) {
        this.uuid = uuid;
    }
    public String getNumeroCommande() {
        return this.numeroCommande;
    }
    
    public void setNumeroCommande(String numeroCommande) {
        this.numeroCommande = numeroCommande;
    }
    public BigDecimal getSousTotal() {
        return this.sousTotal;
    }
    
    public void setSousTotal(BigDecimal sousTotal) {
        this.sousTotal = sousTotal;
    }
    public BigDecimal getMontantTva() {
        return this.montantTva;
    }
    
    public void setMontantTva(BigDecimal montantTva) {
        this.montantTva = montantTva;
    }
    public BigDecimal getFraisLivraison() {
        return this.fraisLivraison;
    }
    
    public void setFraisLivraison(BigDecimal fraisLivraison) {
        this.fraisLivraison = fraisLivraison;
    }
    public BigDecimal getMontantRemise() {
        return this.montantRemise;
    }
    
    public void setMontantRemise(BigDecimal montantRemise) {
        this.montantRemise = montantRemise;
    }
    public BigDecimal getTotalCommande() {
        return this.totalCommande;
    }
    
    public void setTotalCommande(BigDecimal totalCommande) {
        this.totalCommande = totalCommande;
    }
    public String getCodePromoUtilise() {
        return this.codePromoUtilise;
    }
    
    public void setCodePromoUtilise(String codePromoUtilise) {
        this.codePromoUtilise = codePromoUtilise;
    }
    public BigDecimal getRemisePourcentage() {
        return this.remisePourcentage;
    }
    
    public void setRemisePourcentage(BigDecimal remisePourcentage) {
        this.remisePourcentage = remisePourcentage;
    }
    public BigDecimal getRemiseMontant() {
        return this.remiseMontant;
    }
    
    public void setRemiseMontant(BigDecimal remiseMontant) {
        this.remiseMontant = remiseMontant;
    }
    public Serializable getAdresseLivraison() {
        return this.adresseLivraison;
    }
    
    public void setAdresseLivraison(Serializable adresseLivraison) {
        this.adresseLivraison = adresseLivraison;
    }
    public Serializable getCoordonneesLivraison() {
        return this.coordonneesLivraison;
    }
    
    public void setCoordonneesLivraison(Serializable coordonneesLivraison) {
        this.coordonneesLivraison = coordonneesLivraison;
    }
    public String getInstructionsLivraison() {
        return this.instructionsLivraison;
    }
    
    public void setInstructionsLivraison(String instructionsLivraison) {
        this.instructionsLivraison = instructionsLivraison;
    }
    public Timestamp getDateCommande() {
        return this.dateCommande;
    }
    
    public void setDateCommande(Timestamp dateCommande) {
        this.dateCommande = dateCommande;
    }
    public Timestamp getDateConfirmation() {
        return this.dateConfirmation;
    }
    
    public void setDateConfirmation(Timestamp dateConfirmation) {
        this.dateConfirmation = dateConfirmation;
    }
    public Timestamp getDatePreparation() {
        return this.datePreparation;
    }
    
    public void setDatePreparation(Timestamp datePreparation) {
        this.datePreparation = datePreparation;
    }
    public Timestamp getDateExpedition() {
        return this.dateExpedition;
    }
    
    public void setDateExpedition(Timestamp dateExpedition) {
        this.dateExpedition = dateExpedition;
    }
    public Timestamp getDateLivraisonPrevue() {
        return this.dateLivraisonPrevue;
    }
    
    public void setDateLivraisonPrevue(Timestamp dateLivraisonPrevue) {
        this.dateLivraisonPrevue = dateLivraisonPrevue;
    }
    public Timestamp getDateLivraisonReelle() {
        return this.dateLivraisonReelle;
    }
    
    public void setDateLivraisonReelle(Timestamp dateLivraisonReelle) {
        this.dateLivraisonReelle = dateLivraisonReelle;
    }
    public String getNumeroSuivi() {
        return this.numeroSuivi;
    }
    
    public void setNumeroSuivi(String numeroSuivi) {
        this.numeroSuivi = numeroSuivi;
    }
    public String getTransporteur() {
        return this.transporteur;
    }
    
    public void setTransporteur(String transporteur) {
        this.transporteur = transporteur;
    }
    public String getModePaiement() {
        return this.modePaiement;
    }
    
    public void setModePaiement(String modePaiement) {
        this.modePaiement = modePaiement;
    }
    public String getStatutPaiement() {
        return this.statutPaiement;
    }
    
    public void setStatutPaiement(String statutPaiement) {
        this.statutPaiement = statutPaiement;
    }
    public String getTransactionStripeId() {
        return this.transactionStripeId;
    }
    
    public void setTransactionStripeId(String transactionStripeId) {
        this.transactionStripeId = transactionStripeId;
    }
    public String getTransactionExterneId() {
        return this.transactionExterneId;
    }
    
    public void setTransactionExterneId(String transactionExterneId) {
        this.transactionExterneId = transactionExterneId;
    }
    public Boolean getEmailConfirmationEnvoye() {
        return this.emailConfirmationEnvoye;
    }
    
    public void setEmailConfirmationEnvoye(Boolean emailConfirmationEnvoye) {
        this.emailConfirmationEnvoye = emailConfirmationEnvoye;
    }
    public Boolean getSmsConfirmationEnvoye() {
        return this.smsConfirmationEnvoye;
    }
    
    public void setSmsConfirmationEnvoye(Boolean smsConfirmationEnvoye) {
        this.smsConfirmationEnvoye = smsConfirmationEnvoye;
    }
    public Serializable getNotificationsEnvoyees() {
        return this.notificationsEnvoyees;
    }
    
    public void setNotificationsEnvoyees(Serializable notificationsEnvoyees) {
        this.notificationsEnvoyees = notificationsEnvoyees;
    }
    public String getCanalCommande() {
        return this.canalCommande;
    }
    
    public void setCanalCommande(String canalCommande) {
        this.canalCommande = canalCommande;
    }
    public String getAppareilCommande() {
        return this.appareilCommande;
    }
    
    public void setAppareilCommande(String appareilCommande) {
        this.appareilCommande = appareilCommande;
    }
    public String getNavigateurCommande() {
        return this.navigateurCommande;
    }
    
    public void setNavigateurCommande(String navigateurCommande) {
        this.navigateurCommande = navigateurCommande;
    }
    public String getNotesClient() {
        return this.notesClient;
    }
    
    public void setNotesClient(String notesClient) {
        this.notesClient = notesClient;
    }
    public String getNotesInterne() {
        return this.notesInterne;
    }
    
    public void setNotesInterne(String notesInterne) {
        this.notesInterne = notesInterne;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getArticlesCommandes() {
        return this.articlesCommandes;
    }
    
    public void setArticlesCommandes(Set articlesCommandes) {
        this.articlesCommandes = articlesCommandes;
    }
    public Set getLivraisonses() {
        return this.livraisonses;
    }
    
    public void setLivraisonses(Set livraisonses) {
        this.livraisonses = livraisonses;
    }
    public Set getEvaluationsBoutiqueses() {
        return this.evaluationsBoutiqueses;
    }
    
    public void setEvaluationsBoutiqueses(Set evaluationsBoutiqueses) {
        this.evaluationsBoutiqueses = evaluationsBoutiqueses;
    }
    public Set getEvaluationsProduitses() {
        return this.evaluationsProduitses;
    }
    
    public void setEvaluationsProduitses(Set evaluationsProduitses) {
        this.evaluationsProduitses = evaluationsProduitses;
    }
    public Set getHistoriqueStatutsCommandes() {
        return this.historiqueStatutsCommandes;
    }
    
    public void setHistoriqueStatutsCommandes(Set historiqueStatutsCommandes) {
        this.historiqueStatutsCommandes = historiqueStatutsCommandes;
    }
    public Set getRemboursementses() {
        return this.remboursementses;
    }
    
    public void setRemboursementses(Set remboursementses) {
        this.remboursementses = remboursementses;
    }
    public Set getTransactionsPaiements() {
        return this.transactionsPaiements;
    }
    
    public void setTransactionsPaiements(Set transactionsPaiements) {
        this.transactionsPaiements = transactionsPaiements;
    }
    public Set getUtilisationsCodesPromos() {
        return this.utilisationsCodesPromos;
    }
    
    public void setUtilisationsCodesPromos(Set utilisationsCodesPromos) {
        this.utilisationsCodesPromos = utilisationsCodesPromos;
    }




}


