package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Devises generated by hbm2java
 */
public class Devises  implements java.io.Serializable {


     private int id;
     private String code;
     private String nom;
     private String symbole;
     private Integer decimales;
     private BigDecimal tauxChange;
     private Boolean estDeviseBase;
     private Timestamp modifieLe;
     private Set produitses = new HashSet(0);
     private Set entrepriseses = new HashSet(0);
     private Set transactionsPaiements = new HashSet(0);
     private Set commandeses = new HashSet(0);
     private Set methodesPaiements = new HashSet(0);

    public Devises() {
    }

	
    public Devises(int id, String code, String nom) {
        this.id = id;
        this.code = code;
        this.nom = nom;
    }
    public Devises(int id, String code, String nom, String symbole, Integer decimales, BigDecimal tauxChange, Boolean estDeviseBase, Timestamp modifieLe, Set produitses, Set entrepriseses, Set transactionsPaiements, Set commandeses, Set methodesPaiements) {
       this.id = id;
       this.code = code;
       this.nom = nom;
       this.symbole = symbole;
       this.decimales = decimales;
       this.tauxChange = tauxChange;
       this.estDeviseBase = estDeviseBase;
       this.modifieLe = modifieLe;
       this.produitses = produitses;
       this.entrepriseses = entrepriseses;
       this.transactionsPaiements = transactionsPaiements;
       this.commandeses = commandeses;
       this.methodesPaiements = methodesPaiements;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getSymbole() {
        return this.symbole;
    }
    
    public void setSymbole(String symbole) {
        this.symbole = symbole;
    }
    public Integer getDecimales() {
        return this.decimales;
    }
    
    public void setDecimales(Integer decimales) {
        this.decimales = decimales;
    }
    public BigDecimal getTauxChange() {
        return this.tauxChange;
    }
    
    public void setTauxChange(BigDecimal tauxChange) {
        this.tauxChange = tauxChange;
    }
    public Boolean getEstDeviseBase() {
        return this.estDeviseBase;
    }
    
    public void setEstDeviseBase(Boolean estDeviseBase) {
        this.estDeviseBase = estDeviseBase;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getProduitses() {
        return this.produitses;
    }
    
    public void setProduitses(Set produitses) {
        this.produitses = produitses;
    }
    public Set getEntrepriseses() {
        return this.entrepriseses;
    }
    
    public void setEntrepriseses(Set entrepriseses) {
        this.entrepriseses = entrepriseses;
    }
    public Set getTransactionsPaiements() {
        return this.transactionsPaiements;
    }
    
    public void setTransactionsPaiements(Set transactionsPaiements) {
        this.transactionsPaiements = transactionsPaiements;
    }
    public Set getCommandeses() {
        return this.commandeses;
    }
    
    public void setCommandeses(Set commandeses) {
        this.commandeses = commandeses;
    }
    public Set getMethodesPaiements() {
        return this.methodesPaiements;
    }
    
    public void setMethodesPaiements(Set methodesPaiements) {
        this.methodesPaiements = methodesPaiements;
    }




}


