package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * EvaluationsProduits generated by hbm2java
 */
public class EvaluationsProduits  implements java.io.Serializable {


     private int id;
     private Produits produits;
     private ComptesUtilisateur comptesUtilisateur;
     private Commandes commandes;
     private Clients clients;
     private int note;
     private String titre;
     private String commentaire;
     private String avantages;
     private String inconvenients;
     private Boolean recommande;
     private Serializable photosUrls;
     private Serializable videosUrls;
     private Boolean achatVerifie;
     private String langueAvis;
     private Boolean estModere;
     private Boolean estApprouve;
     private String raisonRejet;
     private Integer votesUtile;
     private Integer votesInutile;
     private Integer signalements;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set votesEvaluationses = new HashSet(0);

    public EvaluationsProduits() {
    }

	
    public EvaluationsProduits(int id, Produits produits, Clients clients, int note) {
        this.id = id;
        this.produits = produits;
        this.clients = clients;
        this.note = note;
    }
    public EvaluationsProduits(int id, Produits produits, ComptesUtilisateur comptesUtilisateur, Commandes commandes, Clients clients, int note, String titre, String commentaire, String avantages, String inconvenients, Boolean recommande, Serializable photosUrls, Serializable videosUrls, Boolean achatVerifie, String langueAvis, Boolean estModere, Boolean estApprouve, String raisonRejet, Integer votesUtile, Integer votesInutile, Integer signalements, Timestamp creeLe, Timestamp modifieLe, Set votesEvaluationses) {
       this.id = id;
       this.produits = produits;
       this.comptesUtilisateur = comptesUtilisateur;
       this.commandes = commandes;
       this.clients = clients;
       this.note = note;
       this.titre = titre;
       this.commentaire = commentaire;
       this.avantages = avantages;
       this.inconvenients = inconvenients;
       this.recommande = recommande;
       this.photosUrls = photosUrls;
       this.videosUrls = videosUrls;
       this.achatVerifie = achatVerifie;
       this.langueAvis = langueAvis;
       this.estModere = estModere;
       this.estApprouve = estApprouve;
       this.raisonRejet = raisonRejet;
       this.votesUtile = votesUtile;
       this.votesInutile = votesInutile;
       this.signalements = signalements;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.votesEvaluationses = votesEvaluationses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public Commandes getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Commandes commandes) {
        this.commandes = commandes;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public int getNote() {
        return this.note;
    }
    
    public void setNote(int note) {
        this.note = note;
    }
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }
    public String getAvantages() {
        return this.avantages;
    }
    
    public void setAvantages(String avantages) {
        this.avantages = avantages;
    }
    public String getInconvenients() {
        return this.inconvenients;
    }
    
    public void setInconvenients(String inconvenients) {
        this.inconvenients = inconvenients;
    }
    public Boolean getRecommande() {
        return this.recommande;
    }
    
    public void setRecommande(Boolean recommande) {
        this.recommande = recommande;
    }
    public Serializable getPhotosUrls() {
        return this.photosUrls;
    }
    
    public void setPhotosUrls(Serializable photosUrls) {
        this.photosUrls = photosUrls;
    }
    public Serializable getVideosUrls() {
        return this.videosUrls;
    }
    
    public void setVideosUrls(Serializable videosUrls) {
        this.videosUrls = videosUrls;
    }
    public Boolean getAchatVerifie() {
        return this.achatVerifie;
    }
    
    public void setAchatVerifie(Boolean achatVerifie) {
        this.achatVerifie = achatVerifie;
    }
    public String getLangueAvis() {
        return this.langueAvis;
    }
    
    public void setLangueAvis(String langueAvis) {
        this.langueAvis = langueAvis;
    }
    public Boolean getEstModere() {
        return this.estModere;
    }
    
    public void setEstModere(Boolean estModere) {
        this.estModere = estModere;
    }
    public Boolean getEstApprouve() {
        return this.estApprouve;
    }
    
    public void setEstApprouve(Boolean estApprouve) {
        this.estApprouve = estApprouve;
    }
    public String getRaisonRejet() {
        return this.raisonRejet;
    }
    
    public void setRaisonRejet(String raisonRejet) {
        this.raisonRejet = raisonRejet;
    }
    public Integer getVotesUtile() {
        return this.votesUtile;
    }
    
    public void setVotesUtile(Integer votesUtile) {
        this.votesUtile = votesUtile;
    }
    public Integer getVotesInutile() {
        return this.votesInutile;
    }
    
    public void setVotesInutile(Integer votesInutile) {
        this.votesInutile = votesInutile;
    }
    public Integer getSignalements() {
        return this.signalements;
    }
    
    public void setSignalements(Integer signalements) {
        this.signalements = signalements;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getVotesEvaluationses() {
        return this.votesEvaluationses;
    }
    
    public void setVotesEvaluationses(Set votesEvaluationses) {
        this.votesEvaluationses = votesEvaluationses;
    }




}


