package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * EvenementsAnalytics generated by hbm2java
 */
public class EvenementsAnalytics  implements java.io.Serializable {


     private int id;
     private Produits produits;
     private ComptesUtilisateur comptesUtilisateur;
     private Boutiques boutiques;
     private String sessionId;
     private String nomEvenement;
     private String categorieEvenement;
     private String pageUrl;
     private String pagePrecedente;
     private Serializable proprietes;
     private BigDecimal valeurMonetaire;
     private Serializable adresseIp;
     private String userAgent;
     private String appareilType;
     private String systemeExploitation;
     private String navigateur;
     private String pays;
     private String ville;
     private Serializable coordonnees;
     private Timestamp timestampEvenement;

    public EvenementsAnalytics() {
    }

	
    public EvenementsAnalytics(int id, String nomEvenement) {
        this.id = id;
        this.nomEvenement = nomEvenement;
    }
    public EvenementsAnalytics(int id, Produits produits, ComptesUtilisateur comptesUtilisateur, Boutiques boutiques, String sessionId, String nomEvenement, String categorieEvenement, String pageUrl, String pagePrecedente, Serializable proprietes, BigDecimal valeurMonetaire, Serializable adresseIp, String userAgent, String appareilType, String systemeExploitation, String navigateur, String pays, String ville, Serializable coordonnees, Timestamp timestampEvenement) {
       this.id = id;
       this.produits = produits;
       this.comptesUtilisateur = comptesUtilisateur;
       this.boutiques = boutiques;
       this.sessionId = sessionId;
       this.nomEvenement = nomEvenement;
       this.categorieEvenement = categorieEvenement;
       this.pageUrl = pageUrl;
       this.pagePrecedente = pagePrecedente;
       this.proprietes = proprietes;
       this.valeurMonetaire = valeurMonetaire;
       this.adresseIp = adresseIp;
       this.userAgent = userAgent;
       this.appareilType = appareilType;
       this.systemeExploitation = systemeExploitation;
       this.navigateur = navigateur;
       this.pays = pays;
       this.ville = ville;
       this.coordonnees = coordonnees;
       this.timestampEvenement = timestampEvenement;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public Boutiques getBoutiques() {
        return this.boutiques;
    }
    
    public void setBoutiques(Boutiques boutiques) {
        this.boutiques = boutiques;
    }
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    public String getNomEvenement() {
        return this.nomEvenement;
    }
    
    public void setNomEvenement(String nomEvenement) {
        this.nomEvenement = nomEvenement;
    }
    public String getCategorieEvenement() {
        return this.categorieEvenement;
    }
    
    public void setCategorieEvenement(String categorieEvenement) {
        this.categorieEvenement = categorieEvenement;
    }
    public String getPageUrl() {
        return this.pageUrl;
    }
    
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl;
    }
    public String getPagePrecedente() {
        return this.pagePrecedente;
    }
    
    public void setPagePrecedente(String pagePrecedente) {
        this.pagePrecedente = pagePrecedente;
    }
    public Serializable getProprietes() {
        return this.proprietes;
    }
    
    public void setProprietes(Serializable proprietes) {
        this.proprietes = proprietes;
    }
    public BigDecimal getValeurMonetaire() {
        return this.valeurMonetaire;
    }
    
    public void setValeurMonetaire(BigDecimal valeurMonetaire) {
        this.valeurMonetaire = valeurMonetaire;
    }
    public Serializable getAdresseIp() {
        return this.adresseIp;
    }
    
    public void setAdresseIp(Serializable adresseIp) {
        this.adresseIp = adresseIp;
    }
    public String getUserAgent() {
        return this.userAgent;
    }
    
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }
    public String getAppareilType() {
        return this.appareilType;
    }
    
    public void setAppareilType(String appareilType) {
        this.appareilType = appareilType;
    }
    public String getSystemeExploitation() {
        return this.systemeExploitation;
    }
    
    public void setSystemeExploitation(String systemeExploitation) {
        this.systemeExploitation = systemeExploitation;
    }
    public String getNavigateur() {
        return this.navigateur;
    }
    
    public void setNavigateur(String navigateur) {
        this.navigateur = navigateur;
    }
    public String getPays() {
        return this.pays;
    }
    
    public void setPays(String pays) {
        this.pays = pays;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public Serializable getCoordonnees() {
        return this.coordonnees;
    }
    
    public void setCoordonnees(Serializable coordonnees) {
        this.coordonnees = coordonnees;
    }
    public Timestamp getTimestampEvenement() {
        return this.timestampEvenement;
    }
    
    public void setTimestampEvenement(Timestamp timestampEvenement) {
        this.timestampEvenement = timestampEvenement;
    }




}


