package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.sql.Timestamp;

/**
 * HistoriqueStatutsCommande generated by hbm2java
 */
public class HistoriqueStatutsCommande  implements java.io.Serializable {


     private int id;
     private ComptesUtilisateur comptesUtilisateur;
     private Commandes commandes;
     private StatutsCommande statutsCommandeByAncienStatutId;
     private StatutsCommande statutsCommandeByNouveauStatutId;
     private String raisonChangement;
     private String commentaire;
     private Boolean notificationClientEnvoyee;
     private Timestamp changeLe;

    public HistoriqueStatutsCommande() {
    }

	
    public HistoriqueStatutsCommande(int id, Commandes commandes, StatutsCommande statutsCommandeByNouveauStatutId) {
        this.id = id;
        this.commandes = commandes;
        this.statutsCommandeByNouveauStatutId = statutsCommandeByNouveauStatutId;
    }
    public HistoriqueStatutsCommande(int id, ComptesUtilisateur comptesUtilisateur, Commandes commandes, StatutsCommande statutsCommandeByAncienStatutId, StatutsCommande statutsCommandeByNouveauStatutId, String raisonChangement, String commentaire, Boolean notificationClientEnvoyee, Timestamp changeLe) {
       this.id = id;
       this.comptesUtilisateur = comptesUtilisateur;
       this.commandes = commandes;
       this.statutsCommandeByAncienStatutId = statutsCommandeByAncienStatutId;
       this.statutsCommandeByNouveauStatutId = statutsCommandeByNouveauStatutId;
       this.raisonChangement = raisonChangement;
       this.commentaire = commentaire;
       this.notificationClientEnvoyee = notificationClientEnvoyee;
       this.changeLe = changeLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public Commandes getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Commandes commandes) {
        this.commandes = commandes;
    }
    public StatutsCommande getStatutsCommandeByAncienStatutId() {
        return this.statutsCommandeByAncienStatutId;
    }
    
    public void setStatutsCommandeByAncienStatutId(StatutsCommande statutsCommandeByAncienStatutId) {
        this.statutsCommandeByAncienStatutId = statutsCommandeByAncienStatutId;
    }
    public StatutsCommande getStatutsCommandeByNouveauStatutId() {
        return this.statutsCommandeByNouveauStatutId;
    }
    
    public void setStatutsCommandeByNouveauStatutId(StatutsCommande statutsCommandeByNouveauStatutId) {
        this.statutsCommandeByNouveauStatutId = statutsCommandeByNouveauStatutId;
    }
    public String getRaisonChangement() {
        return this.raisonChangement;
    }
    
    public void setRaisonChangement(String raisonChangement) {
        this.raisonChangement = raisonChangement;
    }
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }
    public Boolean getNotificationClientEnvoyee() {
        return this.notificationClientEnvoyee;
    }
    
    public void setNotificationClientEnvoyee(Boolean notificationClientEnvoyee) {
        this.notificationClientEnvoyee = notificationClientEnvoyee;
    }
    public Timestamp getChangeLe() {
        return this.changeLe;
    }
    
    public void setChangeLe(Timestamp changeLe) {
        this.changeLe = changeLe;
    }




}


