package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final



/**
 * Langues generated by hbm2java
 */
public class Langues  implements java.io.Serializable {


     private int id;
     private String code;
     private String nom;
     private String nomNatif;
     private Boolean estActif;

    public Langues() {
    }

	
    public Langues(int id, String code, String nom) {
        this.id = id;
        this.code = code;
        this.nom = nom;
    }
    public Langues(int id, String code, String nom, String nomNatif, Boolean estActif) {
       this.id = id;
       this.code = code;
       this.nom = nom;
       this.nomNatif = nomNatif;
       this.estActif = estActif;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getNomNatif() {
        return this.nomNatif;
    }
    
    public void setNomNatif(String nomNatif) {
        this.nomNatif = nomNatif;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }




}


