package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Livraisons generated by hbm2java
 */
public class Livraisons  implements java.io.Serializable {


     private int id;
     private Transporteurs transporteurs;
     private Employes employes;
     private Commandes commandes;
     private Serializable uuid;
     private String numeroSuivi;
     private String typeLivraison;
     private Serializable adresseOrigine;
     private Serializable adresseDestination;
     private Serializable coordonneesOrigine;
     private Serializable coordonneesDestination;
     private String instructionsLivraison;
     private String notesLivreur;
     private String codeAcces;
     private Timestamp dateExpedition;
     private Timestamp dateLivraisonPrevue;
     private Timestamp creneauLivraisonDebut;
     private Timestamp creneauLivraisonFin;
     private Timestamp dateLivraisonReelle;
     private String statut;
     private Serializable dernierePosition;
     private Timestamp derniereMiseAJour;
     private BigDecimal poidsTotal;
     private Serializable dimensions;
     private BigDecimal valeurDeclaree;
     private Boolean estFragile;
     private Boolean necessiteSignature;
     private Integer nombreTentatives;
     private Integer maxTentatives;
     private BigDecimal fraisLivraison;
     private BigDecimal fraisAdditionnels;
     private String photoExpeditionUrl;
     private String photoLivraisonUrl;
     private String signatureElectronique;
     private String nomReceptionnaire;
     private String lienReceptionnaire;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set suiviLivraisonses = new HashSet(0);

    public Livraisons() {
    }

	
    public Livraisons(int id, Commandes commandes, Serializable adresseOrigine, Serializable adresseDestination) {
        this.id = id;
        this.commandes = commandes;
        this.adresseOrigine = adresseOrigine;
        this.adresseDestination = adresseDestination;
    }
    public Livraisons(int id, Transporteurs transporteurs, Employes employes, Commandes commandes, Serializable uuid, String numeroSuivi, String typeLivraison, Serializable adresseOrigine, Serializable adresseDestination, Serializable coordonneesOrigine, Serializable coordonneesDestination, String instructionsLivraison, String notesLivreur, String codeAcces, Timestamp dateExpedition, Timestamp dateLivraisonPrevue, Timestamp creneauLivraisonDebut, Timestamp creneauLivraisonFin, Timestamp dateLivraisonReelle, String statut, Serializable dernierePosition, Timestamp derniereMiseAJour, BigDecimal poidsTotal, Serializable dimensions, BigDecimal valeurDeclaree, Boolean estFragile, Boolean necessiteSignature, Integer nombreTentatives, Integer maxTentatives, BigDecimal fraisLivraison, BigDecimal fraisAdditionnels, String photoExpeditionUrl, String photoLivraisonUrl, String signatureElectronique, String nomReceptionnaire, String lienReceptionnaire, Timestamp creeLe, Timestamp modifieLe, Set suiviLivraisonses) {
       this.id = id;
       this.transporteurs = transporteurs;
       this.employes = employes;
       this.commandes = commandes;
       this.uuid = uuid;
       this.numeroSuivi = numeroSuivi;
       this.typeLivraison = typeLivraison;
       this.adresseOrigine = adresseOrigine;
       this.adresseDestination = adresseDestination;
       this.coordonneesOrigine = coordonneesOrigine;
       this.coordonneesDestination = coordonneesDestination;
       this.instructionsLivraison = instructionsLivraison;
       this.notesLivreur = notesLivreur;
       this.codeAcces = codeAcces;
       this.dateExpedition = dateExpedition;
       this.dateLivraisonPrevue = dateLivraisonPrevue;
       this.creneauLivraisonDebut = creneauLivraisonDebut;
       this.creneauLivraisonFin = creneauLivraisonFin;
       this.dateLivraisonReelle = dateLivraisonReelle;
       this.statut = statut;
       this.dernierePosition = dernierePosition;
       this.derniereMiseAJour = derniereMiseAJour;
       this.poidsTotal = poidsTotal;
       this.dimensions = dimensions;
       this.valeurDeclaree = valeurDeclaree;
       this.estFragile = estFragile;
       this.necessiteSignature = necessiteSignature;
       this.nombreTentatives = nombreTentatives;
       this.maxTentatives = maxTentatives;
       this.fraisLivraison = fraisLivraison;
       this.fraisAdditionnels = fraisAdditionnels;
       this.photoExpeditionUrl = photoExpeditionUrl;
       this.photoLivraisonUrl = photoLivraisonUrl;
       this.signatureElectronique = signatureElectronique;
       this.nomReceptionnaire = nomReceptionnaire;
       this.lienReceptionnaire = lienReceptionnaire;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.suiviLivraisonses = suiviLivraisonses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Transporteurs getTransporteurs() {
        return this.transporteurs;
    }
    
    public void setTransporteurs(Transporteurs transporteurs) {
        this.transporteurs = transporteurs;
    }
    public Employes getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Employes employes) {
        this.employes = employes;
    }
    public Commandes getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Commandes commandes) {
        this.commandes = commandes;
    }
    public Serializable getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Serializable uuid) {
        this.uuid = uuid;
    }
    public String getNumeroSuivi() {
        return this.numeroSuivi;
    }
    
    public void setNumeroSuivi(String numeroSuivi) {
        this.numeroSuivi = numeroSuivi;
    }
    public String getTypeLivraison() {
        return this.typeLivraison;
    }
    
    public void setTypeLivraison(String typeLivraison) {
        this.typeLivraison = typeLivraison;
    }
    public Serializable getAdresseOrigine() {
        return this.adresseOrigine;
    }
    
    public void setAdresseOrigine(Serializable adresseOrigine) {
        this.adresseOrigine = adresseOrigine;
    }
    public Serializable getAdresseDestination() {
        return this.adresseDestination;
    }
    
    public void setAdresseDestination(Serializable adresseDestination) {
        this.adresseDestination = adresseDestination;
    }
    public Serializable getCoordonneesOrigine() {
        return this.coordonneesOrigine;
    }
    
    public void setCoordonneesOrigine(Serializable coordonneesOrigine) {
        this.coordonneesOrigine = coordonneesOrigine;
    }
    public Serializable getCoordonneesDestination() {
        return this.coordonneesDestination;
    }
    
    public void setCoordonneesDestination(Serializable coordonneesDestination) {
        this.coordonneesDestination = coordonneesDestination;
    }
    public String getInstructionsLivraison() {
        return this.instructionsLivraison;
    }
    
    public void setInstructionsLivraison(String instructionsLivraison) {
        this.instructionsLivraison = instructionsLivraison;
    }
    public String getNotesLivreur() {
        return this.notesLivreur;
    }
    
    public void setNotesLivreur(String notesLivreur) {
        this.notesLivreur = notesLivreur;
    }
    public String getCodeAcces() {
        return this.codeAcces;
    }
    
    public void setCodeAcces(String codeAcces) {
        this.codeAcces = codeAcces;
    }
    public Timestamp getDateExpedition() {
        return this.dateExpedition;
    }
    
    public void setDateExpedition(Timestamp dateExpedition) {
        this.dateExpedition = dateExpedition;
    }
    public Timestamp getDateLivraisonPrevue() {
        return this.dateLivraisonPrevue;
    }
    
    public void setDateLivraisonPrevue(Timestamp dateLivraisonPrevue) {
        this.dateLivraisonPrevue = dateLivraisonPrevue;
    }
    public Timestamp getCreneauLivraisonDebut() {
        return this.creneauLivraisonDebut;
    }
    
    public void setCreneauLivraisonDebut(Timestamp creneauLivraisonDebut) {
        this.creneauLivraisonDebut = creneauLivraisonDebut;
    }
    public Timestamp getCreneauLivraisonFin() {
        return this.creneauLivraisonFin;
    }
    
    public void setCreneauLivraisonFin(Timestamp creneauLivraisonFin) {
        this.creneauLivraisonFin = creneauLivraisonFin;
    }
    public Timestamp getDateLivraisonReelle() {
        return this.dateLivraisonReelle;
    }
    
    public void setDateLivraisonReelle(Timestamp dateLivraisonReelle) {
        this.dateLivraisonReelle = dateLivraisonReelle;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }
    public Serializable getDernierePosition() {
        return this.dernierePosition;
    }
    
    public void setDernierePosition(Serializable dernierePosition) {
        this.dernierePosition = dernierePosition;
    }
    public Timestamp getDerniereMiseAJour() {
        return this.derniereMiseAJour;
    }
    
    public void setDerniereMiseAJour(Timestamp derniereMiseAJour) {
        this.derniereMiseAJour = derniereMiseAJour;
    }
    public BigDecimal getPoidsTotal() {
        return this.poidsTotal;
    }
    
    public void setPoidsTotal(BigDecimal poidsTotal) {
        this.poidsTotal = poidsTotal;
    }
    public Serializable getDimensions() {
        return this.dimensions;
    }
    
    public void setDimensions(Serializable dimensions) {
        this.dimensions = dimensions;
    }
    public BigDecimal getValeurDeclaree() {
        return this.valeurDeclaree;
    }
    
    public void setValeurDeclaree(BigDecimal valeurDeclaree) {
        this.valeurDeclaree = valeurDeclaree;
    }
    public Boolean getEstFragile() {
        return this.estFragile;
    }
    
    public void setEstFragile(Boolean estFragile) {
        this.estFragile = estFragile;
    }
    public Boolean getNecessiteSignature() {
        return this.necessiteSignature;
    }
    
    public void setNecessiteSignature(Boolean necessiteSignature) {
        this.necessiteSignature = necessiteSignature;
    }
    public Integer getNombreTentatives() {
        return this.nombreTentatives;
    }
    
    public void setNombreTentatives(Integer nombreTentatives) {
        this.nombreTentatives = nombreTentatives;
    }
    public Integer getMaxTentatives() {
        return this.maxTentatives;
    }
    
    public void setMaxTentatives(Integer maxTentatives) {
        this.maxTentatives = maxTentatives;
    }
    public BigDecimal getFraisLivraison() {
        return this.fraisLivraison;
    }
    
    public void setFraisLivraison(BigDecimal fraisLivraison) {
        this.fraisLivraison = fraisLivraison;
    }
    public BigDecimal getFraisAdditionnels() {
        return this.fraisAdditionnels;
    }
    
    public void setFraisAdditionnels(BigDecimal fraisAdditionnels) {
        this.fraisAdditionnels = fraisAdditionnels;
    }
    public String getPhotoExpeditionUrl() {
        return this.photoExpeditionUrl;
    }
    
    public void setPhotoExpeditionUrl(String photoExpeditionUrl) {
        this.photoExpeditionUrl = photoExpeditionUrl;
    }
    public String getPhotoLivraisonUrl() {
        return this.photoLivraisonUrl;
    }
    
    public void setPhotoLivraisonUrl(String photoLivraisonUrl) {
        this.photoLivraisonUrl = photoLivraisonUrl;
    }
    public String getSignatureElectronique() {
        return this.signatureElectronique;
    }
    
    public void setSignatureElectronique(String signatureElectronique) {
        this.signatureElectronique = signatureElectronique;
    }
    public String getNomReceptionnaire() {
        return this.nomReceptionnaire;
    }
    
    public void setNomReceptionnaire(String nomReceptionnaire) {
        this.nomReceptionnaire = nomReceptionnaire;
    }
    public String getLienReceptionnaire() {
        return this.lienReceptionnaire;
    }
    
    public void setLienReceptionnaire(String lienReceptionnaire) {
        this.lienReceptionnaire = lienReceptionnaire;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getSuiviLivraisonses() {
        return this.suiviLivraisonses;
    }
    
    public void setSuiviLivraisonses(Set suiviLivraisonses) {
        this.suiviLivraisonses = suiviLivraisonses;
    }




}


