package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * MethodesPaiement generated by hbm2java
 */
public class MethodesPaiement  implements java.io.Serializable {


     private int id;
     private Devises devises;
     private String code;
     private String nom;
     private String description;
     private Boolean estEnLigne;
     private Boolean estHorsLigne;
     private BigDecimal fraisPourcentage;
     private BigDecimal fraisFixe;
     private BigDecimal montantMinimum;
     private BigDecimal montantMaximum;
     private String stripePaymentMethodType;
     private String iconeUrl;
     private String couleurTheme;
     private Serializable paysSupportes;
     private Boolean estActif;
     private Timestamp creeLe;
     private Set transactionsPaiements = new HashSet(0);

    public MethodesPaiement() {
    }

	
    public MethodesPaiement(int id, String code, String nom) {
        this.id = id;
        this.code = code;
        this.nom = nom;
    }
    public MethodesPaiement(int id, Devises devises, String code, String nom, String description, Boolean estEnLigne, Boolean estHorsLigne, BigDecimal fraisPourcentage, BigDecimal fraisFixe, BigDecimal montantMinimum, BigDecimal montantMaximum, String stripePaymentMethodType, String iconeUrl, String couleurTheme, Serializable paysSupportes, Boolean estActif, Timestamp creeLe, Set transactionsPaiements) {
       this.id = id;
       this.devises = devises;
       this.code = code;
       this.nom = nom;
       this.description = description;
       this.estEnLigne = estEnLigne;
       this.estHorsLigne = estHorsLigne;
       this.fraisPourcentage = fraisPourcentage;
       this.fraisFixe = fraisFixe;
       this.montantMinimum = montantMinimum;
       this.montantMaximum = montantMaximum;
       this.stripePaymentMethodType = stripePaymentMethodType;
       this.iconeUrl = iconeUrl;
       this.couleurTheme = couleurTheme;
       this.paysSupportes = paysSupportes;
       this.estActif = estActif;
       this.creeLe = creeLe;
       this.transactionsPaiements = transactionsPaiements;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Devises getDevises() {
        return this.devises;
    }
    
    public void setDevises(Devises devises) {
        this.devises = devises;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getEstEnLigne() {
        return this.estEnLigne;
    }
    
    public void setEstEnLigne(Boolean estEnLigne) {
        this.estEnLigne = estEnLigne;
    }
    public Boolean getEstHorsLigne() {
        return this.estHorsLigne;
    }
    
    public void setEstHorsLigne(Boolean estHorsLigne) {
        this.estHorsLigne = estHorsLigne;
    }
    public BigDecimal getFraisPourcentage() {
        return this.fraisPourcentage;
    }
    
    public void setFraisPourcentage(BigDecimal fraisPourcentage) {
        this.fraisPourcentage = fraisPourcentage;
    }
    public BigDecimal getFraisFixe() {
        return this.fraisFixe;
    }
    
    public void setFraisFixe(BigDecimal fraisFixe) {
        this.fraisFixe = fraisFixe;
    }
    public BigDecimal getMontantMinimum() {
        return this.montantMinimum;
    }
    
    public void setMontantMinimum(BigDecimal montantMinimum) {
        this.montantMinimum = montantMinimum;
    }
    public BigDecimal getMontantMaximum() {
        return this.montantMaximum;
    }
    
    public void setMontantMaximum(BigDecimal montantMaximum) {
        this.montantMaximum = montantMaximum;
    }
    public String getStripePaymentMethodType() {
        return this.stripePaymentMethodType;
    }
    
    public void setStripePaymentMethodType(String stripePaymentMethodType) {
        this.stripePaymentMethodType = stripePaymentMethodType;
    }
    public String getIconeUrl() {
        return this.iconeUrl;
    }
    
    public void setIconeUrl(String iconeUrl) {
        this.iconeUrl = iconeUrl;
    }
    public String getCouleurTheme() {
        return this.couleurTheme;
    }
    
    public void setCouleurTheme(String couleurTheme) {
        this.couleurTheme = couleurTheme;
    }
    public Serializable getPaysSupportes() {
        return this.paysSupportes;
    }
    
    public void setPaysSupportes(Serializable paysSupportes) {
        this.paysSupportes = paysSupportes;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Set getTransactionsPaiements() {
        return this.transactionsPaiements;
    }
    
    public void setTransactionsPaiements(Set transactionsPaiements) {
        this.transactionsPaiements = transactionsPaiements;
    }




}


