package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

/**
 * MetriquesQuotidiennes generated by hbm2java
 */
public class MetriquesQuotidiennes  implements java.io.Serializable {


     private int id;
     private Boutiques boutiques;
     private Date dateMetrique;
     private Integer nombreCommandes;
     private BigDecimal chiffreAffaires;
     private BigDecimal panierMoyen;
     private Integer nombreArticlesVendus;
     private Integer visiteursUniques;
     private Integer pagesVues;
     private BigDecimal tauxConversion;
     private BigDecimal tauxAbandonPanier;
     private Integer recherchesEffectuees;
     private Integer recherchesSansResultat;
     private Integer recherchesVocales;
     private Integer recherchesImages;
     private Integer evaluationsRecues;
     private BigDecimal noteMoyenneJour;
     private Integer nouveauxClients;
     private Integer nouveauxVendeurs;
     private Timestamp calculeeLe;

    public MetriquesQuotidiennes() {
    }

	
    public MetriquesQuotidiennes(int id, Date dateMetrique) {
        this.id = id;
        this.dateMetrique = dateMetrique;
    }
    public MetriquesQuotidiennes(int id, Boutiques boutiques, Date dateMetrique, Integer nombreCommandes, BigDecimal chiffreAffaires, BigDecimal panierMoyen, Integer nombreArticlesVendus, Integer visiteursUniques, Integer pagesVues, BigDecimal tauxConversion, BigDecimal tauxAbandonPanier, Integer recherchesEffectuees, Integer recherchesSansResultat, Integer recherchesVocales, Integer recherchesImages, Integer evaluationsRecues, BigDecimal noteMoyenneJour, Integer nouveauxClients, Integer nouveauxVendeurs, Timestamp calculeeLe) {
       this.id = id;
       this.boutiques = boutiques;
       this.dateMetrique = dateMetrique;
       this.nombreCommandes = nombreCommandes;
       this.chiffreAffaires = chiffreAffaires;
       this.panierMoyen = panierMoyen;
       this.nombreArticlesVendus = nombreArticlesVendus;
       this.visiteursUniques = visiteursUniques;
       this.pagesVues = pagesVues;
       this.tauxConversion = tauxConversion;
       this.tauxAbandonPanier = tauxAbandonPanier;
       this.recherchesEffectuees = recherchesEffectuees;
       this.recherchesSansResultat = recherchesSansResultat;
       this.recherchesVocales = recherchesVocales;
       this.recherchesImages = recherchesImages;
       this.evaluationsRecues = evaluationsRecues;
       this.noteMoyenneJour = noteMoyenneJour;
       this.nouveauxClients = nouveauxClients;
       this.nouveauxVendeurs = nouveauxVendeurs;
       this.calculeeLe = calculeeLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Boutiques getBoutiques() {
        return this.boutiques;
    }
    
    public void setBoutiques(Boutiques boutiques) {
        this.boutiques = boutiques;
    }
    public Date getDateMetrique() {
        return this.dateMetrique;
    }
    
    public void setDateMetrique(Date dateMetrique) {
        this.dateMetrique = dateMetrique;
    }
    public Integer getNombreCommandes() {
        return this.nombreCommandes;
    }
    
    public void setNombreCommandes(Integer nombreCommandes) {
        this.nombreCommandes = nombreCommandes;
    }
    public BigDecimal getChiffreAffaires() {
        return this.chiffreAffaires;
    }
    
    public void setChiffreAffaires(BigDecimal chiffreAffaires) {
        this.chiffreAffaires = chiffreAffaires;
    }
    public BigDecimal getPanierMoyen() {
        return this.panierMoyen;
    }
    
    public void setPanierMoyen(BigDecimal panierMoyen) {
        this.panierMoyen = panierMoyen;
    }
    public Integer getNombreArticlesVendus() {
        return this.nombreArticlesVendus;
    }
    
    public void setNombreArticlesVendus(Integer nombreArticlesVendus) {
        this.nombreArticlesVendus = nombreArticlesVendus;
    }
    public Integer getVisiteursUniques() {
        return this.visiteursUniques;
    }
    
    public void setVisiteursUniques(Integer visiteursUniques) {
        this.visiteursUniques = visiteursUniques;
    }
    public Integer getPagesVues() {
        return this.pagesVues;
    }
    
    public void setPagesVues(Integer pagesVues) {
        this.pagesVues = pagesVues;
    }
    public BigDecimal getTauxConversion() {
        return this.tauxConversion;
    }
    
    public void setTauxConversion(BigDecimal tauxConversion) {
        this.tauxConversion = tauxConversion;
    }
    public BigDecimal getTauxAbandonPanier() {
        return this.tauxAbandonPanier;
    }
    
    public void setTauxAbandonPanier(BigDecimal tauxAbandonPanier) {
        this.tauxAbandonPanier = tauxAbandonPanier;
    }
    public Integer getRecherchesEffectuees() {
        return this.recherchesEffectuees;
    }
    
    public void setRecherchesEffectuees(Integer recherchesEffectuees) {
        this.recherchesEffectuees = recherchesEffectuees;
    }
    public Integer getRecherchesSansResultat() {
        return this.recherchesSansResultat;
    }
    
    public void setRecherchesSansResultat(Integer recherchesSansResultat) {
        this.recherchesSansResultat = recherchesSansResultat;
    }
    public Integer getRecherchesVocales() {
        return this.recherchesVocales;
    }
    
    public void setRecherchesVocales(Integer recherchesVocales) {
        this.recherchesVocales = recherchesVocales;
    }
    public Integer getRecherchesImages() {
        return this.recherchesImages;
    }
    
    public void setRecherchesImages(Integer recherchesImages) {
        this.recherchesImages = recherchesImages;
    }
    public Integer getEvaluationsRecues() {
        return this.evaluationsRecues;
    }
    
    public void setEvaluationsRecues(Integer evaluationsRecues) {
        this.evaluationsRecues = evaluationsRecues;
    }
    public BigDecimal getNoteMoyenneJour() {
        return this.noteMoyenneJour;
    }
    
    public void setNoteMoyenneJour(BigDecimal noteMoyenneJour) {
        this.noteMoyenneJour = noteMoyenneJour;
    }
    public Integer getNouveauxClients() {
        return this.nouveauxClients;
    }
    
    public void setNouveauxClients(Integer nouveauxClients) {
        this.nouveauxClients = nouveauxClients;
    }
    public Integer getNouveauxVendeurs() {
        return this.nouveauxVendeurs;
    }
    
    public void setNouveauxVendeurs(Integer nouveauxVendeurs) {
        this.nouveauxVendeurs = nouveauxVendeurs;
    }
    public Timestamp getCalculeeLe() {
        return this.calculeeLe;
    }
    
    public void setCalculeeLe(Timestamp calculeeLe) {
        this.calculeeLe = calculeeLe;
    }




}


