package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

/**
 * MouvementsStock generated by hbm2java
 */
public class MouvementsStock  implements java.io.Serializable {


     private int id;
     private Produits produits;
     private ComptesUtilisateur comptesUtilisateur;
     private Employes employes;
     private String typeMouvement;
     private String motif;
     private int quantiteAvant;
     private int quantiteMouvement;
     private int quantiteApres;
     private BigDecimal prixUnitaire;
     private BigDecimal valeurTotale;
     private String referenceExterne;
     private String commentaire;
     private String documentJustificatifUrl;
     private String lotNumero;
     private Date dateExpiration;
     private Timestamp creeLe;

    public MouvementsStock() {
    }

	
    public MouvementsStock(int id, Produits produits, String typeMouvement, int quantiteAvant, int quantiteMouvement, int quantiteApres) {
        this.id = id;
        this.produits = produits;
        this.typeMouvement = typeMouvement;
        this.quantiteAvant = quantiteAvant;
        this.quantiteMouvement = quantiteMouvement;
        this.quantiteApres = quantiteApres;
    }
    public MouvementsStock(int id, Produits produits, ComptesUtilisateur comptesUtilisateur, Employes employes, String typeMouvement, String motif, int quantiteAvant, int quantiteMouvement, int quantiteApres, BigDecimal prixUnitaire, BigDecimal valeurTotale, String referenceExterne, String commentaire, String documentJustificatifUrl, String lotNumero, Date dateExpiration, Timestamp creeLe) {
       this.id = id;
       this.produits = produits;
       this.comptesUtilisateur = comptesUtilisateur;
       this.employes = employes;
       this.typeMouvement = typeMouvement;
       this.motif = motif;
       this.quantiteAvant = quantiteAvant;
       this.quantiteMouvement = quantiteMouvement;
       this.quantiteApres = quantiteApres;
       this.prixUnitaire = prixUnitaire;
       this.valeurTotale = valeurTotale;
       this.referenceExterne = referenceExterne;
       this.commentaire = commentaire;
       this.documentJustificatifUrl = documentJustificatifUrl;
       this.lotNumero = lotNumero;
       this.dateExpiration = dateExpiration;
       this.creeLe = creeLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public Employes getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Employes employes) {
        this.employes = employes;
    }
    public String getTypeMouvement() {
        return this.typeMouvement;
    }
    
    public void setTypeMouvement(String typeMouvement) {
        this.typeMouvement = typeMouvement;
    }
    public String getMotif() {
        return this.motif;
    }
    
    public void setMotif(String motif) {
        this.motif = motif;
    }
    public int getQuantiteAvant() {
        return this.quantiteAvant;
    }
    
    public void setQuantiteAvant(int quantiteAvant) {
        this.quantiteAvant = quantiteAvant;
    }
    public int getQuantiteMouvement() {
        return this.quantiteMouvement;
    }
    
    public void setQuantiteMouvement(int quantiteMouvement) {
        this.quantiteMouvement = quantiteMouvement;
    }
    public int getQuantiteApres() {
        return this.quantiteApres;
    }
    
    public void setQuantiteApres(int quantiteApres) {
        this.quantiteApres = quantiteApres;
    }
    public BigDecimal getPrixUnitaire() {
        return this.prixUnitaire;
    }
    
    public void setPrixUnitaire(BigDecimal prixUnitaire) {
        this.prixUnitaire = prixUnitaire;
    }
    public BigDecimal getValeurTotale() {
        return this.valeurTotale;
    }
    
    public void setValeurTotale(BigDecimal valeurTotale) {
        this.valeurTotale = valeurTotale;
    }
    public String getReferenceExterne() {
        return this.referenceExterne;
    }
    
    public void setReferenceExterne(String referenceExterne) {
        this.referenceExterne = referenceExterne;
    }
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }
    public String getDocumentJustificatifUrl() {
        return this.documentJustificatifUrl;
    }
    
    public void setDocumentJustificatifUrl(String documentJustificatifUrl) {
        this.documentJustificatifUrl = documentJustificatifUrl;
    }
    public String getLotNumero() {
        return this.lotNumero;
    }
    
    public void setLotNumero(String lotNumero) {
        this.lotNumero = lotNumero;
    }
    public Date getDateExpiration() {
        return this.dateExpiration;
    }
    
    public void setDateExpiration(Date dateExpiration) {
        this.dateExpiration = dateExpiration;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }




}


