package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;

/**
 * NotificationsEnvoyees generated by hbm2java
 */
public class NotificationsEnvoyees  implements java.io.Serializable {


     private int id;
     private ComptesUtilisateur comptesUtilisateur;
     private TemplatesNotifications templatesNotifications;
     private String sujet;
     private String contenu;
     private String canal;
     private String statut;
     private String adresseDestination;
     private String providerExterne;
     private String idExterne;
     private Timestamp dateEnvoi;
     private Timestamp dateLivraison;
     private Timestamp dateOuverture;
     private Timestamp dateClic;
     private String codeErreur;
     private String messageErreur;
     private Integer nombreTentatives;
     private Serializable contexte;
     private Timestamp creeLe;

    public NotificationsEnvoyees() {
    }

	
    public NotificationsEnvoyees(int id, String canal) {
        this.id = id;
        this.canal = canal;
    }
    public NotificationsEnvoyees(int id, ComptesUtilisateur comptesUtilisateur, TemplatesNotifications templatesNotifications, String sujet, String contenu, String canal, String statut, String adresseDestination, String providerExterne, String idExterne, Timestamp dateEnvoi, Timestamp dateLivraison, Timestamp dateOuverture, Timestamp dateClic, String codeErreur, String messageErreur, Integer nombreTentatives, Serializable contexte, Timestamp creeLe) {
       this.id = id;
       this.comptesUtilisateur = comptesUtilisateur;
       this.templatesNotifications = templatesNotifications;
       this.sujet = sujet;
       this.contenu = contenu;
       this.canal = canal;
       this.statut = statut;
       this.adresseDestination = adresseDestination;
       this.providerExterne = providerExterne;
       this.idExterne = idExterne;
       this.dateEnvoi = dateEnvoi;
       this.dateLivraison = dateLivraison;
       this.dateOuverture = dateOuverture;
       this.dateClic = dateClic;
       this.codeErreur = codeErreur;
       this.messageErreur = messageErreur;
       this.nombreTentatives = nombreTentatives;
       this.contexte = contexte;
       this.creeLe = creeLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public TemplatesNotifications getTemplatesNotifications() {
        return this.templatesNotifications;
    }
    
    public void setTemplatesNotifications(TemplatesNotifications templatesNotifications) {
        this.templatesNotifications = templatesNotifications;
    }
    public String getSujet() {
        return this.sujet;
    }
    
    public void setSujet(String sujet) {
        this.sujet = sujet;
    }
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }
    public String getCanal() {
        return this.canal;
    }
    
    public void setCanal(String canal) {
        this.canal = canal;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }
    public String getAdresseDestination() {
        return this.adresseDestination;
    }
    
    public void setAdresseDestination(String adresseDestination) {
        this.adresseDestination = adresseDestination;
    }
    public String getProviderExterne() {
        return this.providerExterne;
    }
    
    public void setProviderExterne(String providerExterne) {
        this.providerExterne = providerExterne;
    }
    public String getIdExterne() {
        return this.idExterne;
    }
    
    public void setIdExterne(String idExterne) {
        this.idExterne = idExterne;
    }
    public Timestamp getDateEnvoi() {
        return this.dateEnvoi;
    }
    
    public void setDateEnvoi(Timestamp dateEnvoi) {
        this.dateEnvoi = dateEnvoi;
    }
    public Timestamp getDateLivraison() {
        return this.dateLivraison;
    }
    
    public void setDateLivraison(Timestamp dateLivraison) {
        this.dateLivraison = dateLivraison;
    }
    public Timestamp getDateOuverture() {
        return this.dateOuverture;
    }
    
    public void setDateOuverture(Timestamp dateOuverture) {
        this.dateOuverture = dateOuverture;
    }
    public Timestamp getDateClic() {
        return this.dateClic;
    }
    
    public void setDateClic(Timestamp dateClic) {
        this.dateClic = dateClic;
    }
    public String getCodeErreur() {
        return this.codeErreur;
    }
    
    public void setCodeErreur(String codeErreur) {
        this.codeErreur = codeErreur;
    }
    public String getMessageErreur() {
        return this.messageErreur;
    }
    
    public void setMessageErreur(String messageErreur) {
        this.messageErreur = messageErreur;
    }
    public Integer getNombreTentatives() {
        return this.nombreTentatives;
    }
    
    public void setNombreTentatives(Integer nombreTentatives) {
        this.nombreTentatives = nombreTentatives;
    }
    public Serializable getContexte() {
        return this.contexte;
    }
    
    public void setContexte(Serializable contexte) {
        this.contexte = contexte;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }




}


