package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Pays generated by hbm2java
 */
public class Pays  implements java.io.Serializable {


     private int id;
     private String code;
     private String nom;
     private String codeDevise;
     private String prefixeTelephone;
     private String fuseauHoraire;
     private String languePrincipale;
     private Boolean estActif;
     private Set boutiqueses = new HashSet(0);
     private Set entrepriseses = new HashSet(0);
     private Set personneses = new HashSet(0);
     private Set marqueses = new HashSet(0);

    public Pays() {
    }

	
    public Pays(int id, String code, String nom) {
        this.id = id;
        this.code = code;
        this.nom = nom;
    }
    public Pays(int id, String code, String nom, String codeDevise, String prefixeTelephone, String fuseauHoraire, String languePrincipale, Boolean estActif, Set boutiqueses, Set entrepriseses, Set personneses, Set marqueses) {
       this.id = id;
       this.code = code;
       this.nom = nom;
       this.codeDevise = codeDevise;
       this.prefixeTelephone = prefixeTelephone;
       this.fuseauHoraire = fuseauHoraire;
       this.languePrincipale = languePrincipale;
       this.estActif = estActif;
       this.boutiqueses = boutiqueses;
       this.entrepriseses = entrepriseses;
       this.personneses = personneses;
       this.marqueses = marqueses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getCodeDevise() {
        return this.codeDevise;
    }
    
    public void setCodeDevise(String codeDevise) {
        this.codeDevise = codeDevise;
    }
    public String getPrefixeTelephone() {
        return this.prefixeTelephone;
    }
    
    public void setPrefixeTelephone(String prefixeTelephone) {
        this.prefixeTelephone = prefixeTelephone;
    }
    public String getFuseauHoraire() {
        return this.fuseauHoraire;
    }
    
    public void setFuseauHoraire(String fuseauHoraire) {
        this.fuseauHoraire = fuseauHoraire;
    }
    public String getLanguePrincipale() {
        return this.languePrincipale;
    }
    
    public void setLanguePrincipale(String languePrincipale) {
        this.languePrincipale = languePrincipale;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Set getBoutiqueses() {
        return this.boutiqueses;
    }
    
    public void setBoutiqueses(Set boutiqueses) {
        this.boutiqueses = boutiqueses;
    }
    public Set getEntrepriseses() {
        return this.entrepriseses;
    }
    
    public void setEntrepriseses(Set entrepriseses) {
        this.entrepriseses = entrepriseses;
    }
    public Set getPersonneses() {
        return this.personneses;
    }
    
    public void setPersonneses(Set personneses) {
        this.personneses = personneses;
    }
    public Set getMarqueses() {
        return this.marqueses;
    }
    
    public void setMarqueses(Set marqueses) {
        this.marqueses = marqueses;
    }




}


