package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.sql.Time;
import java.sql.Timestamp;

/**
 * PreferencesNotifications generated by hbm2java
 */
public class PreferencesNotifications  implements java.io.Serializable {


     private int id;
     private ComptesUtilisateur comptesUtilisateur;
     private Boolean notificationsEmail;
     private Boolean notificationsSms;
     private Boolean notificationsPush;
     private Boolean notificationsInApp;
     private Boolean commandesEmail;
     private Boolean commandesSms;
     private Boolean promotionsEmail;
     private Boolean promotionsSms;
     private Boolean newsletter;
     private Boolean resumeQuotidien;
     private Boolean resumeHebdomadaire;
     private Time heureDebut;
     private Time heureFin;
     private Timestamp modifieLe;

    public PreferencesNotifications() {
    }

	
    public PreferencesNotifications(int id, ComptesUtilisateur comptesUtilisateur) {
        this.id = id;
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public PreferencesNotifications(int id, ComptesUtilisateur comptesUtilisateur, Boolean notificationsEmail, Boolean notificationsSms, Boolean notificationsPush, Boolean notificationsInApp, Boolean commandesEmail, Boolean commandesSms, Boolean promotionsEmail, Boolean promotionsSms, Boolean newsletter, Boolean resumeQuotidien, Boolean resumeHebdomadaire, Time heureDebut, Time heureFin, Timestamp modifieLe) {
       this.id = id;
       this.comptesUtilisateur = comptesUtilisateur;
       this.notificationsEmail = notificationsEmail;
       this.notificationsSms = notificationsSms;
       this.notificationsPush = notificationsPush;
       this.notificationsInApp = notificationsInApp;
       this.commandesEmail = commandesEmail;
       this.commandesSms = commandesSms;
       this.promotionsEmail = promotionsEmail;
       this.promotionsSms = promotionsSms;
       this.newsletter = newsletter;
       this.resumeQuotidien = resumeQuotidien;
       this.resumeHebdomadaire = resumeHebdomadaire;
       this.heureDebut = heureDebut;
       this.heureFin = heureFin;
       this.modifieLe = modifieLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ComptesUtilisateur getComptesUtilisateur() {
        return this.comptesUtilisateur;
    }
    
    public void setComptesUtilisateur(ComptesUtilisateur comptesUtilisateur) {
        this.comptesUtilisateur = comptesUtilisateur;
    }
    public Boolean getNotificationsEmail() {
        return this.notificationsEmail;
    }
    
    public void setNotificationsEmail(Boolean notificationsEmail) {
        this.notificationsEmail = notificationsEmail;
    }
    public Boolean getNotificationsSms() {
        return this.notificationsSms;
    }
    
    public void setNotificationsSms(Boolean notificationsSms) {
        this.notificationsSms = notificationsSms;
    }
    public Boolean getNotificationsPush() {
        return this.notificationsPush;
    }
    
    public void setNotificationsPush(Boolean notificationsPush) {
        this.notificationsPush = notificationsPush;
    }
    public Boolean getNotificationsInApp() {
        return this.notificationsInApp;
    }
    
    public void setNotificationsInApp(Boolean notificationsInApp) {
        this.notificationsInApp = notificationsInApp;
    }
    public Boolean getCommandesEmail() {
        return this.commandesEmail;
    }
    
    public void setCommandesEmail(Boolean commandesEmail) {
        this.commandesEmail = commandesEmail;
    }
    public Boolean getCommandesSms() {
        return this.commandesSms;
    }
    
    public void setCommandesSms(Boolean commandesSms) {
        this.commandesSms = commandesSms;
    }
    public Boolean getPromotionsEmail() {
        return this.promotionsEmail;
    }
    
    public void setPromotionsEmail(Boolean promotionsEmail) {
        this.promotionsEmail = promotionsEmail;
    }
    public Boolean getPromotionsSms() {
        return this.promotionsSms;
    }
    
    public void setPromotionsSms(Boolean promotionsSms) {
        this.promotionsSms = promotionsSms;
    }
    public Boolean getNewsletter() {
        return this.newsletter;
    }
    
    public void setNewsletter(Boolean newsletter) {
        this.newsletter = newsletter;
    }
    public Boolean getResumeQuotidien() {
        return this.resumeQuotidien;
    }
    
    public void setResumeQuotidien(Boolean resumeQuotidien) {
        this.resumeQuotidien = resumeQuotidien;
    }
    public Boolean getResumeHebdomadaire() {
        return this.resumeHebdomadaire;
    }
    
    public void setResumeHebdomadaire(Boolean resumeHebdomadaire) {
        this.resumeHebdomadaire = resumeHebdomadaire;
    }
    public Time getHeureDebut() {
        return this.heureDebut;
    }
    
    public void setHeureDebut(Time heureDebut) {
        this.heureDebut = heureDebut;
    }
    public Time getHeureFin() {
        return this.heureFin;
    }
    
    public void setHeureFin(Time heureFin) {
        this.heureFin = heureFin;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }




}


