package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * ProfilsUtilisateur generated by hbm2java
 */
public class ProfilsUtilisateur  implements java.io.Serializable {


     private int id;
     private String code;
     private String nom;
     private String description;
     private Serializable permissions;
     private Integer niveauAcces;
     private Boolean estActif;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set personneses = new HashSet(0);

    public ProfilsUtilisateur() {
    }

	
    public ProfilsUtilisateur(int id, String code, String nom) {
        this.id = id;
        this.code = code;
        this.nom = nom;
    }
    public ProfilsUtilisateur(int id, String code, String nom, String description, Serializable permissions, Integer niveauAcces, Boolean estActif, Timestamp creeLe, Timestamp modifieLe, Set personneses) {
       this.id = id;
       this.code = code;
       this.nom = nom;
       this.description = description;
       this.permissions = permissions;
       this.niveauAcces = niveauAcces;
       this.estActif = estActif;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.personneses = personneses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Serializable getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(Serializable permissions) {
        this.permissions = permissions;
    }
    public Integer getNiveauAcces() {
        return this.niveauAcces;
    }
    
    public void setNiveauAcces(Integer niveauAcces) {
        this.niveauAcces = niveauAcces;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getPersonneses() {
        return this.personneses;
    }
    
    public void setPersonneses(Set personneses) {
        this.personneses = personneses;
    }




}


