package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Remboursements generated by hbm2java
 */
public class Remboursements  implements java.io.Serializable {


     private int id;
     private ComptesUtilisateur comptesUtilisateurByApprouvePar;
     private ComptesUtilisateur comptesUtilisateurByDemandePar;
     private TransactionsPaiement transactionsPaiement;
     private Commandes commandes;
     private BigDecimal montantDemande;
     private BigDecimal montantApprouve;
     private BigDecimal fraisRemboursement;
     private String motif;
     private String description;
     private Serializable piecesJustificatives;
     private Timestamp dateDemande;
     private Timestamp dateApprobation;
     private Timestamp dateTraitement;
     private String statut;
     private String commentaireInterne;
     private String stripeRefundId;
     private Timestamp creeLe;

    public Remboursements() {
    }

	
    public Remboursements(int id, TransactionsPaiement transactionsPaiement, Commandes commandes, BigDecimal montantDemande, String motif) {
        this.id = id;
        this.transactionsPaiement = transactionsPaiement;
        this.commandes = commandes;
        this.montantDemande = montantDemande;
        this.motif = motif;
    }
    public Remboursements(int id, ComptesUtilisateur comptesUtilisateurByApprouvePar, ComptesUtilisateur comptesUtilisateurByDemandePar, TransactionsPaiement transactionsPaiement, Commandes commandes, BigDecimal montantDemande, BigDecimal montantApprouve, BigDecimal fraisRemboursement, String motif, String description, Serializable piecesJustificatives, Timestamp dateDemande, Timestamp dateApprobation, Timestamp dateTraitement, String statut, String commentaireInterne, String stripeRefundId, Timestamp creeLe) {
       this.id = id;
       this.comptesUtilisateurByApprouvePar = comptesUtilisateurByApprouvePar;
       this.comptesUtilisateurByDemandePar = comptesUtilisateurByDemandePar;
       this.transactionsPaiement = transactionsPaiement;
       this.commandes = commandes;
       this.montantDemande = montantDemande;
       this.montantApprouve = montantApprouve;
       this.fraisRemboursement = fraisRemboursement;
       this.motif = motif;
       this.description = description;
       this.piecesJustificatives = piecesJustificatives;
       this.dateDemande = dateDemande;
       this.dateApprobation = dateApprobation;
       this.dateTraitement = dateTraitement;
       this.statut = statut;
       this.commentaireInterne = commentaireInterne;
       this.stripeRefundId = stripeRefundId;
       this.creeLe = creeLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ComptesUtilisateur getComptesUtilisateurByApprouvePar() {
        return this.comptesUtilisateurByApprouvePar;
    }
    
    public void setComptesUtilisateurByApprouvePar(ComptesUtilisateur comptesUtilisateurByApprouvePar) {
        this.comptesUtilisateurByApprouvePar = comptesUtilisateurByApprouvePar;
    }
    public ComptesUtilisateur getComptesUtilisateurByDemandePar() {
        return this.comptesUtilisateurByDemandePar;
    }
    
    public void setComptesUtilisateurByDemandePar(ComptesUtilisateur comptesUtilisateurByDemandePar) {
        this.comptesUtilisateurByDemandePar = comptesUtilisateurByDemandePar;
    }
    public TransactionsPaiement getTransactionsPaiement() {
        return this.transactionsPaiement;
    }
    
    public void setTransactionsPaiement(TransactionsPaiement transactionsPaiement) {
        this.transactionsPaiement = transactionsPaiement;
    }
    public Commandes getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Commandes commandes) {
        this.commandes = commandes;
    }
    public BigDecimal getMontantDemande() {
        return this.montantDemande;
    }
    
    public void setMontantDemande(BigDecimal montantDemande) {
        this.montantDemande = montantDemande;
    }
    public BigDecimal getMontantApprouve() {
        return this.montantApprouve;
    }
    
    public void setMontantApprouve(BigDecimal montantApprouve) {
        this.montantApprouve = montantApprouve;
    }
    public BigDecimal getFraisRemboursement() {
        return this.fraisRemboursement;
    }
    
    public void setFraisRemboursement(BigDecimal fraisRemboursement) {
        this.fraisRemboursement = fraisRemboursement;
    }
    public String getMotif() {
        return this.motif;
    }
    
    public void setMotif(String motif) {
        this.motif = motif;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Serializable getPiecesJustificatives() {
        return this.piecesJustificatives;
    }
    
    public void setPiecesJustificatives(Serializable piecesJustificatives) {
        this.piecesJustificatives = piecesJustificatives;
    }
    public Timestamp getDateDemande() {
        return this.dateDemande;
    }
    
    public void setDateDemande(Timestamp dateDemande) {
        this.dateDemande = dateDemande;
    }
    public Timestamp getDateApprobation() {
        return this.dateApprobation;
    }
    
    public void setDateApprobation(Timestamp dateApprobation) {
        this.dateApprobation = dateApprobation;
    }
    public Timestamp getDateTraitement() {
        return this.dateTraitement;
    }
    
    public void setDateTraitement(Timestamp dateTraitement) {
        this.dateTraitement = dateTraitement;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }
    public String getCommentaireInterne() {
        return this.commentaireInterne;
    }
    
    public void setCommentaireInterne(String commentaireInterne) {
        this.commentaireInterne = commentaireInterne;
    }
    public String getStripeRefundId() {
        return this.stripeRefundId;
    }
    
    public void setStripeRefundId(String stripeRefundId) {
        this.stripeRefundId = stripeRefundId;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }




}


