package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * TransactionsPaiement generated by hbm2java
 */
public class TransactionsPaiement  implements java.io.Serializable {


     private int id;
     private Devises devises;
     private MethodesPaiement methodesPaiement;
     private Commandes commandes;
     private Serializable uuid;
     private BigDecimal montant;
     private BigDecimal fraisTransaction;
     private BigDecimal montantNet;
     private String stripePaymentIntentId;
     private String stripeChargeId;
     private String stripeTransferId;
     private String referenceExterne;
     private String statut;
     private String codeErreur;
     private String messageErreur;
     private Serializable detailsCarte;
     private Serializable detailsMobileMoney;
     private Timestamp dateInitiation;
     private Timestamp dateAutorisation;
     private Timestamp dateCapture;
     private Timestamp dateEchec;
     private BigDecimal scoreRisque;
     private Serializable controlesSecurite;
     private Serializable adresseIpPaiement;
     private BigDecimal montantRembourse;
     private Timestamp dateRemboursement;
     private String raisonRemboursement;
     private Timestamp creeLe;
     private Timestamp modifieLe;
     private Set remboursementses = new HashSet(0);

    public TransactionsPaiement() {
    }

	
    public TransactionsPaiement(int id, MethodesPaiement methodesPaiement, Commandes commandes, BigDecimal montant, BigDecimal montantNet) {
        this.id = id;
        this.methodesPaiement = methodesPaiement;
        this.commandes = commandes;
        this.montant = montant;
        this.montantNet = montantNet;
    }
    public TransactionsPaiement(int id, Devises devises, MethodesPaiement methodesPaiement, Commandes commandes, Serializable uuid, BigDecimal montant, BigDecimal fraisTransaction, BigDecimal montantNet, String stripePaymentIntentId, String stripeChargeId, String stripeTransferId, String referenceExterne, String statut, String codeErreur, String messageErreur, Serializable detailsCarte, Serializable detailsMobileMoney, Timestamp dateInitiation, Timestamp dateAutorisation, Timestamp dateCapture, Timestamp dateEchec, BigDecimal scoreRisque, Serializable controlesSecurite, Serializable adresseIpPaiement, BigDecimal montantRembourse, Timestamp dateRemboursement, String raisonRemboursement, Timestamp creeLe, Timestamp modifieLe, Set remboursementses) {
       this.id = id;
       this.devises = devises;
       this.methodesPaiement = methodesPaiement;
       this.commandes = commandes;
       this.uuid = uuid;
       this.montant = montant;
       this.fraisTransaction = fraisTransaction;
       this.montantNet = montantNet;
       this.stripePaymentIntentId = stripePaymentIntentId;
       this.stripeChargeId = stripeChargeId;
       this.stripeTransferId = stripeTransferId;
       this.referenceExterne = referenceExterne;
       this.statut = statut;
       this.codeErreur = codeErreur;
       this.messageErreur = messageErreur;
       this.detailsCarte = detailsCarte;
       this.detailsMobileMoney = detailsMobileMoney;
       this.dateInitiation = dateInitiation;
       this.dateAutorisation = dateAutorisation;
       this.dateCapture = dateCapture;
       this.dateEchec = dateEchec;
       this.scoreRisque = scoreRisque;
       this.controlesSecurite = controlesSecurite;
       this.adresseIpPaiement = adresseIpPaiement;
       this.montantRembourse = montantRembourse;
       this.dateRemboursement = dateRemboursement;
       this.raisonRemboursement = raisonRemboursement;
       this.creeLe = creeLe;
       this.modifieLe = modifieLe;
       this.remboursementses = remboursementses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Devises getDevises() {
        return this.devises;
    }
    
    public void setDevises(Devises devises) {
        this.devises = devises;
    }
    public MethodesPaiement getMethodesPaiement() {
        return this.methodesPaiement;
    }
    
    public void setMethodesPaiement(MethodesPaiement methodesPaiement) {
        this.methodesPaiement = methodesPaiement;
    }
    public Commandes getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Commandes commandes) {
        this.commandes = commandes;
    }
    public Serializable getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Serializable uuid) {
        this.uuid = uuid;
    }
    public BigDecimal getMontant() {
        return this.montant;
    }
    
    public void setMontant(BigDecimal montant) {
        this.montant = montant;
    }
    public BigDecimal getFraisTransaction() {
        return this.fraisTransaction;
    }
    
    public void setFraisTransaction(BigDecimal fraisTransaction) {
        this.fraisTransaction = fraisTransaction;
    }
    public BigDecimal getMontantNet() {
        return this.montantNet;
    }
    
    public void setMontantNet(BigDecimal montantNet) {
        this.montantNet = montantNet;
    }
    public String getStripePaymentIntentId() {
        return this.stripePaymentIntentId;
    }
    
    public void setStripePaymentIntentId(String stripePaymentIntentId) {
        this.stripePaymentIntentId = stripePaymentIntentId;
    }
    public String getStripeChargeId() {
        return this.stripeChargeId;
    }
    
    public void setStripeChargeId(String stripeChargeId) {
        this.stripeChargeId = stripeChargeId;
    }
    public String getStripeTransferId() {
        return this.stripeTransferId;
    }
    
    public void setStripeTransferId(String stripeTransferId) {
        this.stripeTransferId = stripeTransferId;
    }
    public String getReferenceExterne() {
        return this.referenceExterne;
    }
    
    public void setReferenceExterne(String referenceExterne) {
        this.referenceExterne = referenceExterne;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }
    public String getCodeErreur() {
        return this.codeErreur;
    }
    
    public void setCodeErreur(String codeErreur) {
        this.codeErreur = codeErreur;
    }
    public String getMessageErreur() {
        return this.messageErreur;
    }
    
    public void setMessageErreur(String messageErreur) {
        this.messageErreur = messageErreur;
    }
    public Serializable getDetailsCarte() {
        return this.detailsCarte;
    }
    
    public void setDetailsCarte(Serializable detailsCarte) {
        this.detailsCarte = detailsCarte;
    }
    public Serializable getDetailsMobileMoney() {
        return this.detailsMobileMoney;
    }
    
    public void setDetailsMobileMoney(Serializable detailsMobileMoney) {
        this.detailsMobileMoney = detailsMobileMoney;
    }
    public Timestamp getDateInitiation() {
        return this.dateInitiation;
    }
    
    public void setDateInitiation(Timestamp dateInitiation) {
        this.dateInitiation = dateInitiation;
    }
    public Timestamp getDateAutorisation() {
        return this.dateAutorisation;
    }
    
    public void setDateAutorisation(Timestamp dateAutorisation) {
        this.dateAutorisation = dateAutorisation;
    }
    public Timestamp getDateCapture() {
        return this.dateCapture;
    }
    
    public void setDateCapture(Timestamp dateCapture) {
        this.dateCapture = dateCapture;
    }
    public Timestamp getDateEchec() {
        return this.dateEchec;
    }
    
    public void setDateEchec(Timestamp dateEchec) {
        this.dateEchec = dateEchec;
    }
    public BigDecimal getScoreRisque() {
        return this.scoreRisque;
    }
    
    public void setScoreRisque(BigDecimal scoreRisque) {
        this.scoreRisque = scoreRisque;
    }
    public Serializable getControlesSecurite() {
        return this.controlesSecurite;
    }
    
    public void setControlesSecurite(Serializable controlesSecurite) {
        this.controlesSecurite = controlesSecurite;
    }
    public Serializable getAdresseIpPaiement() {
        return this.adresseIpPaiement;
    }
    
    public void setAdresseIpPaiement(Serializable adresseIpPaiement) {
        this.adresseIpPaiement = adresseIpPaiement;
    }
    public BigDecimal getMontantRembourse() {
        return this.montantRembourse;
    }
    
    public void setMontantRembourse(BigDecimal montantRembourse) {
        this.montantRembourse = montantRembourse;
    }
    public Timestamp getDateRemboursement() {
        return this.dateRemboursement;
    }
    
    public void setDateRemboursement(Timestamp dateRemboursement) {
        this.dateRemboursement = dateRemboursement;
    }
    public String getRaisonRemboursement() {
        return this.raisonRemboursement;
    }
    
    public void setRaisonRemboursement(String raisonRemboursement) {
        this.raisonRemboursement = raisonRemboursement;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Timestamp getModifieLe() {
        return this.modifieLe;
    }
    
    public void setModifieLe(Timestamp modifieLe) {
        this.modifieLe = modifieLe;
    }
    public Set getRemboursementses() {
        return this.remboursementses;
    }
    
    public void setRemboursementses(Set remboursementses) {
        this.remboursementses = remboursementses;
    }




}


