package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Transporteurs generated by hbm2java
 */
public class Transporteurs  implements java.io.Serializable {


     private int id;
     private String nom;
     private String code;
     private String description;
     private String telephone;
     private String email;
     private String siteWeb;
     private String apiUrl;
     private String apiKeyHash;
     private String formatNumeroSuivi;
     private Serializable zonesCouverture;
     private Serializable tarifs;
     private BigDecimal fraisBase;
     private Integer delaiLivraisonMin;
     private Integer delaiLivraisonMax;
     private BigDecimal noteMoyenne;
     private Integer nombreEvaluations;
     private Boolean estActif;
     private Timestamp creeLe;
     private Set livraisonses = new HashSet(0);

    public Transporteurs() {
    }

	
    public Transporteurs(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }
    public Transporteurs(int id, String nom, String code, String description, String telephone, String email, String siteWeb, String apiUrl, String apiKeyHash, String formatNumeroSuivi, Serializable zonesCouverture, Serializable tarifs, BigDecimal fraisBase, Integer delaiLivraisonMin, Integer delaiLivraisonMax, BigDecimal noteMoyenne, Integer nombreEvaluations, Boolean estActif, Timestamp creeLe, Set livraisonses) {
       this.id = id;
       this.nom = nom;
       this.code = code;
       this.description = description;
       this.telephone = telephone;
       this.email = email;
       this.siteWeb = siteWeb;
       this.apiUrl = apiUrl;
       this.apiKeyHash = apiKeyHash;
       this.formatNumeroSuivi = formatNumeroSuivi;
       this.zonesCouverture = zonesCouverture;
       this.tarifs = tarifs;
       this.fraisBase = fraisBase;
       this.delaiLivraisonMin = delaiLivraisonMin;
       this.delaiLivraisonMax = delaiLivraisonMax;
       this.noteMoyenne = noteMoyenne;
       this.nombreEvaluations = nombreEvaluations;
       this.estActif = estActif;
       this.creeLe = creeLe;
       this.livraisonses = livraisonses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSiteWeb() {
        return this.siteWeb;
    }
    
    public void setSiteWeb(String siteWeb) {
        this.siteWeb = siteWeb;
    }
    public String getApiUrl() {
        return this.apiUrl;
    }
    
    public void setApiUrl(String apiUrl) {
        this.apiUrl = apiUrl;
    }
    public String getApiKeyHash() {
        return this.apiKeyHash;
    }
    
    public void setApiKeyHash(String apiKeyHash) {
        this.apiKeyHash = apiKeyHash;
    }
    public String getFormatNumeroSuivi() {
        return this.formatNumeroSuivi;
    }
    
    public void setFormatNumeroSuivi(String formatNumeroSuivi) {
        this.formatNumeroSuivi = formatNumeroSuivi;
    }
    public Serializable getZonesCouverture() {
        return this.zonesCouverture;
    }
    
    public void setZonesCouverture(Serializable zonesCouverture) {
        this.zonesCouverture = zonesCouverture;
    }
    public Serializable getTarifs() {
        return this.tarifs;
    }
    
    public void setTarifs(Serializable tarifs) {
        this.tarifs = tarifs;
    }
    public BigDecimal getFraisBase() {
        return this.fraisBase;
    }
    
    public void setFraisBase(BigDecimal fraisBase) {
        this.fraisBase = fraisBase;
    }
    public Integer getDelaiLivraisonMin() {
        return this.delaiLivraisonMin;
    }
    
    public void setDelaiLivraisonMin(Integer delaiLivraisonMin) {
        this.delaiLivraisonMin = delaiLivraisonMin;
    }
    public Integer getDelaiLivraisonMax() {
        return this.delaiLivraisonMax;
    }
    
    public void setDelaiLivraisonMax(Integer delaiLivraisonMax) {
        this.delaiLivraisonMax = delaiLivraisonMax;
    }
    public BigDecimal getNoteMoyenne() {
        return this.noteMoyenne;
    }
    
    public void setNoteMoyenne(BigDecimal noteMoyenne) {
        this.noteMoyenne = noteMoyenne;
    }
    public Integer getNombreEvaluations() {
        return this.nombreEvaluations;
    }
    
    public void setNombreEvaluations(Integer nombreEvaluations) {
        this.nombreEvaluations = nombreEvaluations;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Timestamp getCreeLe() {
        return this.creeLe;
    }
    
    public void setCreeLe(Timestamp creeLe) {
        this.creeLe = creeLe;
    }
    public Set getLivraisonses() {
        return this.livraisonses;
    }
    
    public void setLivraisonses(Set livraisonses) {
        this.livraisonses = livraisonses;
    }




}


