package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * UtilisationsCodesPromo generated by hbm2java
 */
public class UtilisationsCodesPromo  implements java.io.Serializable {


     private int id;
     private CodesPromotionnels codesPromotionnels;
     private Commandes commandes;
     private Clients clients;
     private BigDecimal montantRemiseApplique;
     private Timestamp utiliseLe;

    public UtilisationsCodesPromo() {
    }

	
    public UtilisationsCodesPromo(int id, CodesPromotionnels codesPromotionnels, Commandes commandes, Clients clients, BigDecimal montantRemiseApplique) {
        this.id = id;
        this.codesPromotionnels = codesPromotionnels;
        this.commandes = commandes;
        this.clients = clients;
        this.montantRemiseApplique = montantRemiseApplique;
    }
    public UtilisationsCodesPromo(int id, CodesPromotionnels codesPromotionnels, Commandes commandes, Clients clients, BigDecimal montantRemiseApplique, Timestamp utiliseLe) {
       this.id = id;
       this.codesPromotionnels = codesPromotionnels;
       this.commandes = commandes;
       this.clients = clients;
       this.montantRemiseApplique = montantRemiseApplique;
       this.utiliseLe = utiliseLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CodesPromotionnels getCodesPromotionnels() {
        return this.codesPromotionnels;
    }
    
    public void setCodesPromotionnels(CodesPromotionnels codesPromotionnels) {
        this.codesPromotionnels = codesPromotionnels;
    }
    public Commandes getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Commandes commandes) {
        this.commandes = commandes;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public BigDecimal getMontantRemiseApplique() {
        return this.montantRemiseApplique;
    }
    
    public void setMontantRemiseApplique(BigDecimal montantRemiseApplique) {
        this.montantRemiseApplique = montantRemiseApplique;
    }
    public Timestamp getUtiliseLe() {
        return this.utiliseLe;
    }
    
    public void setUtiliseLe(Timestamp utiliseLe) {
        this.utiliseLe = utiliseLe;
    }




}


