package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * VClientsActifsId generated by hbm2java
 */
public class VClientsActifsId  implements java.io.Serializable {


     private Timestamp derniereCommandeLe;
     private String email;
     private Integer id;
     private String niveauFidelite;
     private String nomComplet;
     private Integer nombreCommandes;
     private BigDecimal panierMoyen;
     private Integer pointsFidelite;
     private String statutActivite;
     private String telephone;
     private BigDecimal totalDepense;
     private String ville;

    public VClientsActifsId() {
    }

    public VClientsActifsId(Timestamp derniereCommandeLe, String email, Integer id, String niveauFidelite, String nomComplet, Integer nombreCommandes, BigDecimal panierMoyen, Integer pointsFidelite, String statutActivite, String telephone, BigDecimal totalDepense, String ville) {
       this.derniereCommandeLe = derniereCommandeLe;
       this.email = email;
       this.id = id;
       this.niveauFidelite = niveauFidelite;
       this.nomComplet = nomComplet;
       this.nombreCommandes = nombreCommandes;
       this.panierMoyen = panierMoyen;
       this.pointsFidelite = pointsFidelite;
       this.statutActivite = statutActivite;
       this.telephone = telephone;
       this.totalDepense = totalDepense;
       this.ville = ville;
    }
   
    public Timestamp getDerniereCommandeLe() {
        return this.derniereCommandeLe;
    }
    
    public void setDerniereCommandeLe(Timestamp derniereCommandeLe) {
        this.derniereCommandeLe = derniereCommandeLe;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNiveauFidelite() {
        return this.niveauFidelite;
    }
    
    public void setNiveauFidelite(String niveauFidelite) {
        this.niveauFidelite = niveauFidelite;
    }
    public String getNomComplet() {
        return this.nomComplet;
    }
    
    public void setNomComplet(String nomComplet) {
        this.nomComplet = nomComplet;
    }
    public Integer getNombreCommandes() {
        return this.nombreCommandes;
    }
    
    public void setNombreCommandes(Integer nombreCommandes) {
        this.nombreCommandes = nombreCommandes;
    }
    public BigDecimal getPanierMoyen() {
        return this.panierMoyen;
    }
    
    public void setPanierMoyen(BigDecimal panierMoyen) {
        this.panierMoyen = panierMoyen;
    }
    public Integer getPointsFidelite() {
        return this.pointsFidelite;
    }
    
    public void setPointsFidelite(Integer pointsFidelite) {
        this.pointsFidelite = pointsFidelite;
    }
    public String getStatutActivite() {
        return this.statutActivite;
    }
    
    public void setStatutActivite(String statutActivite) {
        this.statutActivite = statutActivite;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public BigDecimal getTotalDepense() {
        return this.totalDepense;
    }
    
    public void setTotalDepense(BigDecimal totalDepense) {
        this.totalDepense = totalDepense;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VClientsActifsId) ) return false;
		 VClientsActifsId castOther = ( VClientsActifsId ) other; 
         
		 return ( (this.getDerniereCommandeLe()==castOther.getDerniereCommandeLe()) || ( this.getDerniereCommandeLe()!=null && castOther.getDerniereCommandeLe()!=null && this.getDerniereCommandeLe().equals(castOther.getDerniereCommandeLe()) ) )
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getNiveauFidelite()==castOther.getNiveauFidelite()) || ( this.getNiveauFidelite()!=null && castOther.getNiveauFidelite()!=null && this.getNiveauFidelite().equals(castOther.getNiveauFidelite()) ) )
 && ( (this.getNomComplet()==castOther.getNomComplet()) || ( this.getNomComplet()!=null && castOther.getNomComplet()!=null && this.getNomComplet().equals(castOther.getNomComplet()) ) )
 && ( (this.getNombreCommandes()==castOther.getNombreCommandes()) || ( this.getNombreCommandes()!=null && castOther.getNombreCommandes()!=null && this.getNombreCommandes().equals(castOther.getNombreCommandes()) ) )
 && ( (this.getPanierMoyen()==castOther.getPanierMoyen()) || ( this.getPanierMoyen()!=null && castOther.getPanierMoyen()!=null && this.getPanierMoyen().equals(castOther.getPanierMoyen()) ) )
 && ( (this.getPointsFidelite()==castOther.getPointsFidelite()) || ( this.getPointsFidelite()!=null && castOther.getPointsFidelite()!=null && this.getPointsFidelite().equals(castOther.getPointsFidelite()) ) )
 && ( (this.getStatutActivite()==castOther.getStatutActivite()) || ( this.getStatutActivite()!=null && castOther.getStatutActivite()!=null && this.getStatutActivite().equals(castOther.getStatutActivite()) ) )
 && ( (this.getTelephone()==castOther.getTelephone()) || ( this.getTelephone()!=null && castOther.getTelephone()!=null && this.getTelephone().equals(castOther.getTelephone()) ) )
 && ( (this.getTotalDepense()==castOther.getTotalDepense()) || ( this.getTotalDepense()!=null && castOther.getTotalDepense()!=null && this.getTotalDepense().equals(castOther.getTotalDepense()) ) )
 && ( (this.getVille()==castOther.getVille()) || ( this.getVille()!=null && castOther.getVille()!=null && this.getVille().equals(castOther.getVille()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getDerniereCommandeLe() == null ? 0 : this.getDerniereCommandeLe().hashCode() );
        result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
        result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
        result = 37 * result + ( getNiveauFidelite() == null ? 0 : this.getNiveauFidelite().hashCode() );
        result = 37 * result + ( getNomComplet() == null ? 0 : this.getNomComplet().hashCode() );
        result = 37 * result + ( getNombreCommandes() == null ? 0 : this.getNombreCommandes().hashCode() );
        result = 37 * result + ( getPanierMoyen() == null ? 0 : this.getPanierMoyen().hashCode() );
        result = 37 * result + ( getPointsFidelite() == null ? 0 : this.getPointsFidelite().hashCode() );
        result = 37 * result + ( getStatutActivite() == null ? 0 : this.getStatutActivite().hashCode() );
        result = 37 * result + ( getTelephone() == null ? 0 : this.getTelephone().hashCode() );
        result = 37 * result + ( getTotalDepense() == null ? 0 : this.getTotalDepense().hashCode() );
        result = 37 * result + ( getVille() == null ? 0 : this.getVille().hashCode() );
         return result;
   }   


}


