package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final



/**
 * VClientsActifs generated by hbm2java
 */
public class VClientsActifs  implements java.io.Serializable {


     private VClientsActifsId id;

    public VClientsActifs() {
    }

    public VClientsActifs(VClientsActifsId id) {
       this.id = id;
    }
   
    public VClientsActifsId getId() {
        return this.id;
    }
    
    public void setId(VClientsActifsId id) {
        this.id = id;
    }




}


