package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * VCommandesCompletesId generated by hbm2java
 */
public class VCommandesCompletesId  implements java.io.Serializable {


     private String boutiqueNom;
     private String clientEmail;
     private String clientNom;
     private Timestamp dateCommande;
     private Integer id;
     private String modePaiement;
     private Long nombreArticles;
     private String numeroCommande;
     private String statutCouleur;
     private String statutLibelle;
     private String statutPaiement;
     private BigDecimal totalCommande;
     private Serializable uuid;

    public VCommandesCompletesId() {
    }

    public VCommandesCompletesId(String boutiqueNom, String clientEmail, String clientNom, Timestamp dateCommande, Integer id, String modePaiement, Long nombreArticles, String numeroCommande, String statutCouleur, String statutLibelle, String statutPaiement, BigDecimal totalCommande, Serializable uuid) {
       this.boutiqueNom = boutiqueNom;
       this.clientEmail = clientEmail;
       this.clientNom = clientNom;
       this.dateCommande = dateCommande;
       this.id = id;
       this.modePaiement = modePaiement;
       this.nombreArticles = nombreArticles;
       this.numeroCommande = numeroCommande;
       this.statutCouleur = statutCouleur;
       this.statutLibelle = statutLibelle;
       this.statutPaiement = statutPaiement;
       this.totalCommande = totalCommande;
       this.uuid = uuid;
    }
   
    public String getBoutiqueNom() {
        return this.boutiqueNom;
    }
    
    public void setBoutiqueNom(String boutiqueNom) {
        this.boutiqueNom = boutiqueNom;
    }
    public String getClientEmail() {
        return this.clientEmail;
    }
    
    public void setClientEmail(String clientEmail) {
        this.clientEmail = clientEmail;
    }
    public String getClientNom() {
        return this.clientNom;
    }
    
    public void setClientNom(String clientNom) {
        this.clientNom = clientNom;
    }
    public Timestamp getDateCommande() {
        return this.dateCommande;
    }
    
    public void setDateCommande(Timestamp dateCommande) {
        this.dateCommande = dateCommande;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getModePaiement() {
        return this.modePaiement;
    }
    
    public void setModePaiement(String modePaiement) {
        this.modePaiement = modePaiement;
    }
    public Long getNombreArticles() {
        return this.nombreArticles;
    }
    
    public void setNombreArticles(Long nombreArticles) {
        this.nombreArticles = nombreArticles;
    }
    public String getNumeroCommande() {
        return this.numeroCommande;
    }
    
    public void setNumeroCommande(String numeroCommande) {
        this.numeroCommande = numeroCommande;
    }
    public String getStatutCouleur() {
        return this.statutCouleur;
    }
    
    public void setStatutCouleur(String statutCouleur) {
        this.statutCouleur = statutCouleur;
    }
    public String getStatutLibelle() {
        return this.statutLibelle;
    }
    
    public void setStatutLibelle(String statutLibelle) {
        this.statutLibelle = statutLibelle;
    }
    public String getStatutPaiement() {
        return this.statutPaiement;
    }
    
    public void setStatutPaiement(String statutPaiement) {
        this.statutPaiement = statutPaiement;
    }
    public BigDecimal getTotalCommande() {
        return this.totalCommande;
    }
    
    public void setTotalCommande(BigDecimal totalCommande) {
        this.totalCommande = totalCommande;
    }
    public Serializable getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Serializable uuid) {
        this.uuid = uuid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VCommandesCompletesId) ) return false;
		 VCommandesCompletesId castOther = ( VCommandesCompletesId ) other; 
         
		 return ( (this.getBoutiqueNom()==castOther.getBoutiqueNom()) || ( this.getBoutiqueNom()!=null && castOther.getBoutiqueNom()!=null && this.getBoutiqueNom().equals(castOther.getBoutiqueNom()) ) )
 && ( (this.getClientEmail()==castOther.getClientEmail()) || ( this.getClientEmail()!=null && castOther.getClientEmail()!=null && this.getClientEmail().equals(castOther.getClientEmail()) ) )
 && ( (this.getClientNom()==castOther.getClientNom()) || ( this.getClientNom()!=null && castOther.getClientNom()!=null && this.getClientNom().equals(castOther.getClientNom()) ) )
 && ( (this.getDateCommande()==castOther.getDateCommande()) || ( this.getDateCommande()!=null && castOther.getDateCommande()!=null && this.getDateCommande().equals(castOther.getDateCommande()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getModePaiement()==castOther.getModePaiement()) || ( this.getModePaiement()!=null && castOther.getModePaiement()!=null && this.getModePaiement().equals(castOther.getModePaiement()) ) )
 && ( (this.getNombreArticles()==castOther.getNombreArticles()) || ( this.getNombreArticles()!=null && castOther.getNombreArticles()!=null && this.getNombreArticles().equals(castOther.getNombreArticles()) ) )
 && ( (this.getNumeroCommande()==castOther.getNumeroCommande()) || ( this.getNumeroCommande()!=null && castOther.getNumeroCommande()!=null && this.getNumeroCommande().equals(castOther.getNumeroCommande()) ) )
 && ( (this.getStatutCouleur()==castOther.getStatutCouleur()) || ( this.getStatutCouleur()!=null && castOther.getStatutCouleur()!=null && this.getStatutCouleur().equals(castOther.getStatutCouleur()) ) )
 && ( (this.getStatutLibelle()==castOther.getStatutLibelle()) || ( this.getStatutLibelle()!=null && castOther.getStatutLibelle()!=null && this.getStatutLibelle().equals(castOther.getStatutLibelle()) ) )
 && ( (this.getStatutPaiement()==castOther.getStatutPaiement()) || ( this.getStatutPaiement()!=null && castOther.getStatutPaiement()!=null && this.getStatutPaiement().equals(castOther.getStatutPaiement()) ) )
 && ( (this.getTotalCommande()==castOther.getTotalCommande()) || ( this.getTotalCommande()!=null && castOther.getTotalCommande()!=null && this.getTotalCommande().equals(castOther.getTotalCommande()) ) )
 && ( (this.getUuid()==castOther.getUuid()) || ( this.getUuid()!=null && castOther.getUuid()!=null && this.getUuid().equals(castOther.getUuid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getBoutiqueNom() == null ? 0 : this.getBoutiqueNom().hashCode() );
        result = 37 * result + ( getClientEmail() == null ? 0 : this.getClientEmail().hashCode() );
        result = 37 * result + ( getClientNom() == null ? 0 : this.getClientNom().hashCode() );
        result = 37 * result + ( getDateCommande() == null ? 0 : this.getDateCommande().hashCode() );
        result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
        result = 37 * result + ( getModePaiement() == null ? 0 : this.getModePaiement().hashCode() );
        result = 37 * result + ( getNombreArticles() == null ? 0 : this.getNombreArticles().hashCode() );
        result = 37 * result + ( getNumeroCommande() == null ? 0 : this.getNumeroCommande().hashCode() );
        result = 37 * result + ( getStatutCouleur() == null ? 0 : this.getStatutCouleur().hashCode() );
        result = 37 * result + ( getStatutLibelle() == null ? 0 : this.getStatutLibelle().hashCode() );
        result = 37 * result + ( getStatutPaiement() == null ? 0 : this.getStatutPaiement().hashCode() );
        result = 37 * result + ( getTotalCommande() == null ? 0 : this.getTotalCommande().hashCode() );
        result = 37 * result + ( getUuid() == null ? 0 : this.getUuid().hashCode() );
         return result;
   }   


}


