package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final



/**
 * VCommandesCompletes generated by hbm2java
 */
public class VCommandesCompletes  implements java.io.Serializable {


     private VCommandesCompletesId id;

    public VCommandesCompletes() {
    }

    public VCommandesCompletes(VCommandesCompletesId id) {
       this.id = id;
    }
   
    public VCommandesCompletesId getId() {
        return this.id;
    }
    
    public void setId(VCommandesCompletesId id) {
        this.id = id;
    }




}


