package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * VLivraisonsCompletesId generated by hbm2java
 */
public class VLivraisonsCompletesId  implements java.io.Serializable {


     private String boutiqueNom;
     private String clientNom;
     private String clientTelephone;
     private Timestamp dateExpedition;
     private Timestamp dateLivraisonPrevue;
     private Timestamp dateLivraisonReelle;
     private BigDecimal fraisLivraison;
     private Integer id;
     private String numeroCommande;
     private String numeroSuivi;
     private String statut;
     private String transporteurNom;
     private String typeLivraison;
     private Serializable uuid;

    public VLivraisonsCompletesId() {
    }

    public VLivraisonsCompletesId(String boutiqueNom, String clientNom, String clientTelephone, Timestamp dateExpedition, Timestamp dateLivraisonPrevue, Timestamp dateLivraisonReelle, BigDecimal fraisLivraison, Integer id, String numeroCommande, String numeroSuivi, String statut, String transporteurNom, String typeLivraison, Serializable uuid) {
       this.boutiqueNom = boutiqueNom;
       this.clientNom = clientNom;
       this.clientTelephone = clientTelephone;
       this.dateExpedition = dateExpedition;
       this.dateLivraisonPrevue = dateLivraisonPrevue;
       this.dateLivraisonReelle = dateLivraisonReelle;
       this.fraisLivraison = fraisLivraison;
       this.id = id;
       this.numeroCommande = numeroCommande;
       this.numeroSuivi = numeroSuivi;
       this.statut = statut;
       this.transporteurNom = transporteurNom;
       this.typeLivraison = typeLivraison;
       this.uuid = uuid;
    }
   
    public String getBoutiqueNom() {
        return this.boutiqueNom;
    }
    
    public void setBoutiqueNom(String boutiqueNom) {
        this.boutiqueNom = boutiqueNom;
    }
    public String getClientNom() {
        return this.clientNom;
    }
    
    public void setClientNom(String clientNom) {
        this.clientNom = clientNom;
    }
    public String getClientTelephone() {
        return this.clientTelephone;
    }
    
    public void setClientTelephone(String clientTelephone) {
        this.clientTelephone = clientTelephone;
    }
    public Timestamp getDateExpedition() {
        return this.dateExpedition;
    }
    
    public void setDateExpedition(Timestamp dateExpedition) {
        this.dateExpedition = dateExpedition;
    }
    public Timestamp getDateLivraisonPrevue() {
        return this.dateLivraisonPrevue;
    }
    
    public void setDateLivraisonPrevue(Timestamp dateLivraisonPrevue) {
        this.dateLivraisonPrevue = dateLivraisonPrevue;
    }
    public Timestamp getDateLivraisonReelle() {
        return this.dateLivraisonReelle;
    }
    
    public void setDateLivraisonReelle(Timestamp dateLivraisonReelle) {
        this.dateLivraisonReelle = dateLivraisonReelle;
    }
    public BigDecimal getFraisLivraison() {
        return this.fraisLivraison;
    }
    
    public void setFraisLivraison(BigDecimal fraisLivraison) {
        this.fraisLivraison = fraisLivraison;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNumeroCommande() {
        return this.numeroCommande;
    }
    
    public void setNumeroCommande(String numeroCommande) {
        this.numeroCommande = numeroCommande;
    }
    public String getNumeroSuivi() {
        return this.numeroSuivi;
    }
    
    public void setNumeroSuivi(String numeroSuivi) {
        this.numeroSuivi = numeroSuivi;
    }
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }
    public String getTransporteurNom() {
        return this.transporteurNom;
    }
    
    public void setTransporteurNom(String transporteurNom) {
        this.transporteurNom = transporteurNom;
    }
    public String getTypeLivraison() {
        return this.typeLivraison;
    }
    
    public void setTypeLivraison(String typeLivraison) {
        this.typeLivraison = typeLivraison;
    }
    public Serializable getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Serializable uuid) {
        this.uuid = uuid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VLivraisonsCompletesId) ) return false;
		 VLivraisonsCompletesId castOther = ( VLivraisonsCompletesId ) other; 
         
		 return ( (this.getBoutiqueNom()==castOther.getBoutiqueNom()) || ( this.getBoutiqueNom()!=null && castOther.getBoutiqueNom()!=null && this.getBoutiqueNom().equals(castOther.getBoutiqueNom()) ) )
 && ( (this.getClientNom()==castOther.getClientNom()) || ( this.getClientNom()!=null && castOther.getClientNom()!=null && this.getClientNom().equals(castOther.getClientNom()) ) )
 && ( (this.getClientTelephone()==castOther.getClientTelephone()) || ( this.getClientTelephone()!=null && castOther.getClientTelephone()!=null && this.getClientTelephone().equals(castOther.getClientTelephone()) ) )
 && ( (this.getDateExpedition()==castOther.getDateExpedition()) || ( this.getDateExpedition()!=null && castOther.getDateExpedition()!=null && this.getDateExpedition().equals(castOther.getDateExpedition()) ) )
 && ( (this.getDateLivraisonPrevue()==castOther.getDateLivraisonPrevue()) || ( this.getDateLivraisonPrevue()!=null && castOther.getDateLivraisonPrevue()!=null && this.getDateLivraisonPrevue().equals(castOther.getDateLivraisonPrevue()) ) )
 && ( (this.getDateLivraisonReelle()==castOther.getDateLivraisonReelle()) || ( this.getDateLivraisonReelle()!=null && castOther.getDateLivraisonReelle()!=null && this.getDateLivraisonReelle().equals(castOther.getDateLivraisonReelle()) ) )
 && ( (this.getFraisLivraison()==castOther.getFraisLivraison()) || ( this.getFraisLivraison()!=null && castOther.getFraisLivraison()!=null && this.getFraisLivraison().equals(castOther.getFraisLivraison()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getNumeroCommande()==castOther.getNumeroCommande()) || ( this.getNumeroCommande()!=null && castOther.getNumeroCommande()!=null && this.getNumeroCommande().equals(castOther.getNumeroCommande()) ) )
 && ( (this.getNumeroSuivi()==castOther.getNumeroSuivi()) || ( this.getNumeroSuivi()!=null && castOther.getNumeroSuivi()!=null && this.getNumeroSuivi().equals(castOther.getNumeroSuivi()) ) )
 && ( (this.getStatut()==castOther.getStatut()) || ( this.getStatut()!=null && castOther.getStatut()!=null && this.getStatut().equals(castOther.getStatut()) ) )
 && ( (this.getTransporteurNom()==castOther.getTransporteurNom()) || ( this.getTransporteurNom()!=null && castOther.getTransporteurNom()!=null && this.getTransporteurNom().equals(castOther.getTransporteurNom()) ) )
 && ( (this.getTypeLivraison()==castOther.getTypeLivraison()) || ( this.getTypeLivraison()!=null && castOther.getTypeLivraison()!=null && this.getTypeLivraison().equals(castOther.getTypeLivraison()) ) )
 && ( (this.getUuid()==castOther.getUuid()) || ( this.getUuid()!=null && castOther.getUuid()!=null && this.getUuid().equals(castOther.getUuid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getBoutiqueNom() == null ? 0 : this.getBoutiqueNom().hashCode() );
        result = 37 * result + ( getClientNom() == null ? 0 : this.getClientNom().hashCode() );
        result = 37 * result + ( getClientTelephone() == null ? 0 : this.getClientTelephone().hashCode() );
        result = 37 * result + ( getDateExpedition() == null ? 0 : this.getDateExpedition().hashCode() );
        result = 37 * result + ( getDateLivraisonPrevue() == null ? 0 : this.getDateLivraisonPrevue().hashCode() );
        result = 37 * result + ( getDateLivraisonReelle() == null ? 0 : this.getDateLivraisonReelle().hashCode() );
        result = 37 * result + ( getFraisLivraison() == null ? 0 : this.getFraisLivraison().hashCode() );
        result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
        result = 37 * result + ( getNumeroCommande() == null ? 0 : this.getNumeroCommande().hashCode() );
        result = 37 * result + ( getNumeroSuivi() == null ? 0 : this.getNumeroSuivi().hashCode() );
        result = 37 * result + ( getStatut() == null ? 0 : this.getStatut().hashCode() );
        result = 37 * result + ( getTransporteurNom() == null ? 0 : this.getTransporteurNom().hashCode() );
        result = 37 * result + ( getTypeLivraison() == null ? 0 : this.getTypeLivraison().hashCode() );
        result = 37 * result + ( getUuid() == null ? 0 : this.getUuid().hashCode() );
         return result;
   }   


}


