package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final



/**
 * VLivraisonsCompletes generated by hbm2java
 */
public class VLivraisonsCompletes  implements java.io.Serializable {


     private VLivraisonsCompletesId id;

    public VLivraisonsCompletes() {
    }

    public VLivraisonsCompletes(VLivraisonsCompletesId id) {
       this.id = id;
    }
   
    public VLivraisonsCompletesId getId() {
        return this.id;
    }
    
    public void setId(VLivraisonsCompletesId id) {
        this.id = id;
    }




}


