package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.sql.Timestamp;

/**
 * VotesEvaluations generated by hbm2java
 */
public class VotesEvaluations  implements java.io.Serializable {


     private int id;
     private EvaluationsProduits evaluationsProduits;
     private EvaluationsBoutiques evaluationsBoutiques;
     private Clients clients;
     private String typeVote;
     private Timestamp voteLe;

    public VotesEvaluations() {
    }

	
    public VotesEvaluations(int id, Clients clients, String typeVote) {
        this.id = id;
        this.clients = clients;
        this.typeVote = typeVote;
    }
    public VotesEvaluations(int id, EvaluationsProduits evaluationsProduits, EvaluationsBoutiques evaluationsBoutiques, Clients clients, String typeVote, Timestamp voteLe) {
       this.id = id;
       this.evaluationsProduits = evaluationsProduits;
       this.evaluationsBoutiques = evaluationsBoutiques;
       this.clients = clients;
       this.typeVote = typeVote;
       this.voteLe = voteLe;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public EvaluationsProduits getEvaluationsProduits() {
        return this.evaluationsProduits;
    }
    
    public void setEvaluationsProduits(EvaluationsProduits evaluationsProduits) {
        this.evaluationsProduits = evaluationsProduits;
    }
    public EvaluationsBoutiques getEvaluationsBoutiques() {
        return this.evaluationsBoutiques;
    }
    
    public void setEvaluationsBoutiques(EvaluationsBoutiques evaluationsBoutiques) {
        this.evaluationsBoutiques = evaluationsBoutiques;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public String getTypeVote() {
        return this.typeVote;
    }
    
    public void setTypeVote(String typeVote) {
        this.typeVote = typeVote;
    }
    public Timestamp getVoteLe() {
        return this.voteLe;
    }
    
    public void setVoteLe(Timestamp voteLe) {
        this.voteLe = voteLe;
    }




}


