package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final



/**
 * VProduitsComplets generated by hbm2java
 */
public class VProduitsComplets  implements java.io.Serializable {


     private VProduitsCompletsId id;

    public VProduitsComplets() {
    }

    public VProduitsComplets(VProduitsCompletsId id) {
       this.id = id;
    }
   
    public VProduitsCompletsId getId() {
        return this.id;
    }
    
    public void setId(VProduitsCompletsId id) {
        this.id = id;
    }




}


