package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final



/**
 * VProduitsPopulaires generated by hbm2java
 */
public class VProduitsPopulaires  implements java.io.Serializable {


     private VProduitsPopulairesId id;

    public VProduitsPopulaires() {
    }

    public VProduitsPopulaires(VProduitsPopulairesId id) {
       this.id = id;
    }
   
    public VProduitsPopulairesId getId() {
        return this.id;
    }
    
    public void setId(VProduitsPopulairesId id) {
        this.id = id;
    }




}


