package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.math.BigDecimal;

/**
 * VProduitsPopulairesId generated by hbm2java
 */
public class VProduitsPopulairesId  implements java.io.Serializable {


     private String boutiqueNom;
     private String categorieNom;
     private Integer id;
     private String imagePrincipaleUrl;
     private String nom;
     private Long nombreCommandes;
     private Byte noteMoyenne;
     private BigDecimal prixVente;
     private Long quantiteVendue;
     private Integer stockActuel;

    public VProduitsPopulairesId() {
    }

    public VProduitsPopulairesId(String boutiqueNom, String categorieNom, Integer id, String imagePrincipaleUrl, String nom, Long nombreCommandes, Byte noteMoyenne, BigDecimal prixVente, Long quantiteVendue, Integer stockActuel) {
       this.boutiqueNom = boutiqueNom;
       this.categorieNom = categorieNom;
       this.id = id;
       this.imagePrincipaleUrl = imagePrincipaleUrl;
       this.nom = nom;
       this.nombreCommandes = nombreCommandes;
       this.noteMoyenne = noteMoyenne;
       this.prixVente = prixVente;
       this.quantiteVendue = quantiteVendue;
       this.stockActuel = stockActuel;
    }
   
    public String getBoutiqueNom() {
        return this.boutiqueNom;
    }
    
    public void setBoutiqueNom(String boutiqueNom) {
        this.boutiqueNom = boutiqueNom;
    }
    public String getCategorieNom() {
        return this.categorieNom;
    }
    
    public void setCategorieNom(String categorieNom) {
        this.categorieNom = categorieNom;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getImagePrincipaleUrl() {
        return this.imagePrincipaleUrl;
    }
    
    public void setImagePrincipaleUrl(String imagePrincipaleUrl) {
        this.imagePrincipaleUrl = imagePrincipaleUrl;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Long getNombreCommandes() {
        return this.nombreCommandes;
    }
    
    public void setNombreCommandes(Long nombreCommandes) {
        this.nombreCommandes = nombreCommandes;
    }
    public Byte getNoteMoyenne() {
        return this.noteMoyenne;
    }
    
    public void setNoteMoyenne(Byte noteMoyenne) {
        this.noteMoyenne = noteMoyenne;
    }
    public BigDecimal getPrixVente() {
        return this.prixVente;
    }
    
    public void setPrixVente(BigDecimal prixVente) {
        this.prixVente = prixVente;
    }
    public Long getQuantiteVendue() {
        return this.quantiteVendue;
    }
    
    public void setQuantiteVendue(Long quantiteVendue) {
        this.quantiteVendue = quantiteVendue;
    }
    public Integer getStockActuel() {
        return this.stockActuel;
    }
    
    public void setStockActuel(Integer stockActuel) {
        this.stockActuel = stockActuel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VProduitsPopulairesId) ) return false;
		 VProduitsPopulairesId castOther = ( VProduitsPopulairesId ) other; 
         
		 return ( (this.getBoutiqueNom()==castOther.getBoutiqueNom()) || ( this.getBoutiqueNom()!=null && castOther.getBoutiqueNom()!=null && this.getBoutiqueNom().equals(castOther.getBoutiqueNom()) ) )
 && ( (this.getCategorieNom()==castOther.getCategorieNom()) || ( this.getCategorieNom()!=null && castOther.getCategorieNom()!=null && this.getCategorieNom().equals(castOther.getCategorieNom()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getImagePrincipaleUrl()==castOther.getImagePrincipaleUrl()) || ( this.getImagePrincipaleUrl()!=null && castOther.getImagePrincipaleUrl()!=null && this.getImagePrincipaleUrl().equals(castOther.getImagePrincipaleUrl()) ) )
 && ( (this.getNom()==castOther.getNom()) || ( this.getNom()!=null && castOther.getNom()!=null && this.getNom().equals(castOther.getNom()) ) )
 && ( (this.getNombreCommandes()==castOther.getNombreCommandes()) || ( this.getNombreCommandes()!=null && castOther.getNombreCommandes()!=null && this.getNombreCommandes().equals(castOther.getNombreCommandes()) ) )
 && ( (this.getNoteMoyenne()==castOther.getNoteMoyenne()) || ( this.getNoteMoyenne()!=null && castOther.getNoteMoyenne()!=null && this.getNoteMoyenne().equals(castOther.getNoteMoyenne()) ) )
 && ( (this.getPrixVente()==castOther.getPrixVente()) || ( this.getPrixVente()!=null && castOther.getPrixVente()!=null && this.getPrixVente().equals(castOther.getPrixVente()) ) )
 && ( (this.getQuantiteVendue()==castOther.getQuantiteVendue()) || ( this.getQuantiteVendue()!=null && castOther.getQuantiteVendue()!=null && this.getQuantiteVendue().equals(castOther.getQuantiteVendue()) ) )
 && ( (this.getStockActuel()==castOther.getStockActuel()) || ( this.getStockActuel()!=null && castOther.getStockActuel()!=null && this.getStockActuel().equals(castOther.getStockActuel()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getBoutiqueNom() == null ? 0 : this.getBoutiqueNom().hashCode() );
        result = 37 * result + ( getCategorieNom() == null ? 0 : this.getCategorieNom().hashCode() );
        result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
        result = 37 * result + ( getImagePrincipaleUrl() == null ? 0 : this.getImagePrincipaleUrl().hashCode() );
        result = 37 * result + ( getNom() == null ? 0 : this.getNom().hashCode() );
        result = 37 * result + ( getNombreCommandes() == null ? 0 : this.getNombreCommandes().hashCode() );
        result = 37 * result + ( getNoteMoyenne() == null ? 0 : this.getNoteMoyenne().hashCode() );
        result = 37 * result + ( getPrixVente() == null ? 0 : this.getPrixVente().hashCode() );
        result = 37 * result + ( getQuantiteVendue() == null ? 0 : this.getQuantiteVendue().hashCode() );
        result = 37 * result + ( getStockActuel() == null ? 0 : this.getStockActuel().hashCode() );
         return result;
   }   


}


