package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * VProduitsCompletsId generated by hbm2java
 */
public class VProduitsCompletsId  implements java.io.Serializable {


     private Serializable boutiqueCoordonnees;
     private String boutiqueNom;
     private String boutiqueVille;
     private String categorieNom;
     private String descriptionCourte;
     private Boolean estEnPromotion;
     private Integer id;
     private String imagePrincipaleUrl;
     private String marqueNom;
     private String nom;
     private Integer nombreEvaluations;
     private BigDecimal noteMoyenne;
     private BigDecimal prixPromo;
     private BigDecimal prixVente;
     private Integer stockActuel;
     private Serializable uuid;

    public VProduitsCompletsId() {
    }

    public VProduitsCompletsId(Serializable boutiqueCoordonnees, String boutiqueNom, String boutiqueVille, String categorieNom, String descriptionCourte, Boolean estEnPromotion, Integer id, String imagePrincipaleUrl, String marqueNom, String nom, Integer nombreEvaluations, BigDecimal noteMoyenne, BigDecimal prixPromo, BigDecimal prixVente, Integer stockActuel, Serializable uuid) {
       this.boutiqueCoordonnees = boutiqueCoordonnees;
       this.boutiqueNom = boutiqueNom;
       this.boutiqueVille = boutiqueVille;
       this.categorieNom = categorieNom;
       this.descriptionCourte = descriptionCourte;
       this.estEnPromotion = estEnPromotion;
       this.id = id;
       this.imagePrincipaleUrl = imagePrincipaleUrl;
       this.marqueNom = marqueNom;
       this.nom = nom;
       this.nombreEvaluations = nombreEvaluations;
       this.noteMoyenne = noteMoyenne;
       this.prixPromo = prixPromo;
       this.prixVente = prixVente;
       this.stockActuel = stockActuel;
       this.uuid = uuid;
    }
   
    public Serializable getBoutiqueCoordonnees() {
        return this.boutiqueCoordonnees;
    }
    
    public void setBoutiqueCoordonnees(Serializable boutiqueCoordonnees) {
        this.boutiqueCoordonnees = boutiqueCoordonnees;
    }
    public String getBoutiqueNom() {
        return this.boutiqueNom;
    }
    
    public void setBoutiqueNom(String boutiqueNom) {
        this.boutiqueNom = boutiqueNom;
    }
    public String getBoutiqueVille() {
        return this.boutiqueVille;
    }
    
    public void setBoutiqueVille(String boutiqueVille) {
        this.boutiqueVille = boutiqueVille;
    }
    public String getCategorieNom() {
        return this.categorieNom;
    }
    
    public void setCategorieNom(String categorieNom) {
        this.categorieNom = categorieNom;
    }
    public String getDescriptionCourte() {
        return this.descriptionCourte;
    }
    
    public void setDescriptionCourte(String descriptionCourte) {
        this.descriptionCourte = descriptionCourte;
    }
    public Boolean getEstEnPromotion() {
        return this.estEnPromotion;
    }
    
    public void setEstEnPromotion(Boolean estEnPromotion) {
        this.estEnPromotion = estEnPromotion;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getImagePrincipaleUrl() {
        return this.imagePrincipaleUrl;
    }
    
    public void setImagePrincipaleUrl(String imagePrincipaleUrl) {
        this.imagePrincipaleUrl = imagePrincipaleUrl;
    }
    public String getMarqueNom() {
        return this.marqueNom;
    }
    
    public void setMarqueNom(String marqueNom) {
        this.marqueNom = marqueNom;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Integer getNombreEvaluations() {
        return this.nombreEvaluations;
    }
    
    public void setNombreEvaluations(Integer nombreEvaluations) {
        this.nombreEvaluations = nombreEvaluations;
    }
    public BigDecimal getNoteMoyenne() {
        return this.noteMoyenne;
    }
    
    public void setNoteMoyenne(BigDecimal noteMoyenne) {
        this.noteMoyenne = noteMoyenne;
    }
    public BigDecimal getPrixPromo() {
        return this.prixPromo;
    }
    
    public void setPrixPromo(BigDecimal prixPromo) {
        this.prixPromo = prixPromo;
    }
    public BigDecimal getPrixVente() {
        return this.prixVente;
    }
    
    public void setPrixVente(BigDecimal prixVente) {
        this.prixVente = prixVente;
    }
    public Integer getStockActuel() {
        return this.stockActuel;
    }
    
    public void setStockActuel(Integer stockActuel) {
        this.stockActuel = stockActuel;
    }
    public Serializable getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Serializable uuid) {
        this.uuid = uuid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VProduitsCompletsId) ) return false;
		 VProduitsCompletsId castOther = ( VProduitsCompletsId ) other; 
         
		 return ( (this.getBoutiqueCoordonnees()==castOther.getBoutiqueCoordonnees()) || ( this.getBoutiqueCoordonnees()!=null && castOther.getBoutiqueCoordonnees()!=null && this.getBoutiqueCoordonnees().equals(castOther.getBoutiqueCoordonnees()) ) )
 && ( (this.getBoutiqueNom()==castOther.getBoutiqueNom()) || ( this.getBoutiqueNom()!=null && castOther.getBoutiqueNom()!=null && this.getBoutiqueNom().equals(castOther.getBoutiqueNom()) ) )
 && ( (this.getBoutiqueVille()==castOther.getBoutiqueVille()) || ( this.getBoutiqueVille()!=null && castOther.getBoutiqueVille()!=null && this.getBoutiqueVille().equals(castOther.getBoutiqueVille()) ) )
 && ( (this.getCategorieNom()==castOther.getCategorieNom()) || ( this.getCategorieNom()!=null && castOther.getCategorieNom()!=null && this.getCategorieNom().equals(castOther.getCategorieNom()) ) )
 && ( (this.getDescriptionCourte()==castOther.getDescriptionCourte()) || ( this.getDescriptionCourte()!=null && castOther.getDescriptionCourte()!=null && this.getDescriptionCourte().equals(castOther.getDescriptionCourte()) ) )
 && ( (this.getEstEnPromotion()==castOther.getEstEnPromotion()) || ( this.getEstEnPromotion()!=null && castOther.getEstEnPromotion()!=null && this.getEstEnPromotion().equals(castOther.getEstEnPromotion()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getImagePrincipaleUrl()==castOther.getImagePrincipaleUrl()) || ( this.getImagePrincipaleUrl()!=null && castOther.getImagePrincipaleUrl()!=null && this.getImagePrincipaleUrl().equals(castOther.getImagePrincipaleUrl()) ) )
 && ( (this.getMarqueNom()==castOther.getMarqueNom()) || ( this.getMarqueNom()!=null && castOther.getMarqueNom()!=null && this.getMarqueNom().equals(castOther.getMarqueNom()) ) )
 && ( (this.getNom()==castOther.getNom()) || ( this.getNom()!=null && castOther.getNom()!=null && this.getNom().equals(castOther.getNom()) ) )
 && ( (this.getNombreEvaluations()==castOther.getNombreEvaluations()) || ( this.getNombreEvaluations()!=null && castOther.getNombreEvaluations()!=null && this.getNombreEvaluations().equals(castOther.getNombreEvaluations()) ) )
 && ( (this.getNoteMoyenne()==castOther.getNoteMoyenne()) || ( this.getNoteMoyenne()!=null && castOther.getNoteMoyenne()!=null && this.getNoteMoyenne().equals(castOther.getNoteMoyenne()) ) )
 && ( (this.getPrixPromo()==castOther.getPrixPromo()) || ( this.getPrixPromo()!=null && castOther.getPrixPromo()!=null && this.getPrixPromo().equals(castOther.getPrixPromo()) ) )
 && ( (this.getPrixVente()==castOther.getPrixVente()) || ( this.getPrixVente()!=null && castOther.getPrixVente()!=null && this.getPrixVente().equals(castOther.getPrixVente()) ) )
 && ( (this.getStockActuel()==castOther.getStockActuel()) || ( this.getStockActuel()!=null && castOther.getStockActuel()!=null && this.getStockActuel().equals(castOther.getStockActuel()) ) )
 && ( (this.getUuid()==castOther.getUuid()) || ( this.getUuid()!=null && castOther.getUuid()!=null && this.getUuid().equals(castOther.getUuid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getBoutiqueCoordonnees() == null ? 0 : this.getBoutiqueCoordonnees().hashCode() );
        result = 37 * result + ( getBoutiqueNom() == null ? 0 : this.getBoutiqueNom().hashCode() );
        result = 37 * result + ( getBoutiqueVille() == null ? 0 : this.getBoutiqueVille().hashCode() );
        result = 37 * result + ( getCategorieNom() == null ? 0 : this.getCategorieNom().hashCode() );
        result = 37 * result + ( getDescriptionCourte() == null ? 0 : this.getDescriptionCourte().hashCode() );
        result = 37 * result + ( getEstEnPromotion() == null ? 0 : this.getEstEnPromotion().hashCode() );
        result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
        result = 37 * result + ( getImagePrincipaleUrl() == null ? 0 : this.getImagePrincipaleUrl().hashCode() );
        result = 37 * result + ( getMarqueNom() == null ? 0 : this.getMarqueNom().hashCode() );
        result = 37 * result + ( getNom() == null ? 0 : this.getNom().hashCode() );
        result = 37 * result + ( getNombreEvaluations() == null ? 0 : this.getNombreEvaluations().hashCode() );
        result = 37 * result + ( getNoteMoyenne() == null ? 0 : this.getNoteMoyenne().hashCode() );
        result = 37 * result + ( getPrixPromo() == null ? 0 : this.getPrixPromo().hashCode() );
        result = 37 * result + ( getPrixVente() == null ? 0 : this.getPrixVente().hashCode() );
        result = 37 * result + ( getStockActuel() == null ? 0 : this.getStockActuel().hashCode() );
        result = 37 * result + ( getUuid() == null ? 0 : this.getUuid().hashCode() );
         return result;
   }   


}


