package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final



/**
 * VStatistiquesRecherche generated by hbm2java
 */
public class VStatistiquesRecherche  implements java.io.Serializable {


     private VStatistiquesRechercheId id;

    public VStatistiquesRecherche() {
    }

    public VStatistiquesRecherche(VStatistiquesRechercheId id) {
       this.id = id;
    }
   
    public VStatistiquesRechercheId getId() {
        return this.id;
    }
    
    public void setId(VStatistiquesRechercheId id) {
        this.id = id;
    }




}


