package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.sql.Date;

/**
 * VStatistiquesRechercheId generated by hbm2java
 */
public class VStatistiquesRechercheId  implements java.io.Serializable {


     private Date dateRecherche;
     private String langueRecherche;
     private Long nombreRecherches;
     private Long recherchesAvecClic;
     private Long recherchesAvecResultats;
     private Byte tauxClicPct;
     private String typeRecherche;

    public VStatistiquesRechercheId() {
    }

    public VStatistiquesRechercheId(Date dateRecherche, String langueRecherche, Long nombreRecherches, Long recherchesAvecClic, Long recherchesAvecResultats, Byte tauxClicPct, String typeRecherche) {
       this.dateRecherche = dateRecherche;
       this.langueRecherche = langueRecherche;
       this.nombreRecherches = nombreRecherches;
       this.recherchesAvecClic = recherchesAvecClic;
       this.recherchesAvecResultats = recherchesAvecResultats;
       this.tauxClicPct = tauxClicPct;
       this.typeRecherche = typeRecherche;
    }
   
    public Date getDateRecherche() {
        return this.dateRecherche;
    }
    
    public void setDateRecherche(Date dateRecherche) {
        this.dateRecherche = dateRecherche;
    }
    public String getLangueRecherche() {
        return this.langueRecherche;
    }
    
    public void setLangueRecherche(String langueRecherche) {
        this.langueRecherche = langueRecherche;
    }
    public Long getNombreRecherches() {
        return this.nombreRecherches;
    }
    
    public void setNombreRecherches(Long nombreRecherches) {
        this.nombreRecherches = nombreRecherches;
    }
    public Long getRecherchesAvecClic() {
        return this.recherchesAvecClic;
    }
    
    public void setRecherchesAvecClic(Long recherchesAvecClic) {
        this.recherchesAvecClic = recherchesAvecClic;
    }
    public Long getRecherchesAvecResultats() {
        return this.recherchesAvecResultats;
    }
    
    public void setRecherchesAvecResultats(Long recherchesAvecResultats) {
        this.recherchesAvecResultats = recherchesAvecResultats;
    }
    public Byte getTauxClicPct() {
        return this.tauxClicPct;
    }
    
    public void setTauxClicPct(Byte tauxClicPct) {
        this.tauxClicPct = tauxClicPct;
    }
    public String getTypeRecherche() {
        return this.typeRecherche;
    }
    
    public void setTypeRecherche(String typeRecherche) {
        this.typeRecherche = typeRecherche;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VStatistiquesRechercheId) ) return false;
		 VStatistiquesRechercheId castOther = ( VStatistiquesRechercheId ) other; 
         
		 return ( (this.getDateRecherche()==castOther.getDateRecherche()) || ( this.getDateRecherche()!=null && castOther.getDateRecherche()!=null && this.getDateRecherche().equals(castOther.getDateRecherche()) ) )
 && ( (this.getLangueRecherche()==castOther.getLangueRecherche()) || ( this.getLangueRecherche()!=null && castOther.getLangueRecherche()!=null && this.getLangueRecherche().equals(castOther.getLangueRecherche()) ) )
 && ( (this.getNombreRecherches()==castOther.getNombreRecherches()) || ( this.getNombreRecherches()!=null && castOther.getNombreRecherches()!=null && this.getNombreRecherches().equals(castOther.getNombreRecherches()) ) )
 && ( (this.getRecherchesAvecClic()==castOther.getRecherchesAvecClic()) || ( this.getRecherchesAvecClic()!=null && castOther.getRecherchesAvecClic()!=null && this.getRecherchesAvecClic().equals(castOther.getRecherchesAvecClic()) ) )
 && ( (this.getRecherchesAvecResultats()==castOther.getRecherchesAvecResultats()) || ( this.getRecherchesAvecResultats()!=null && castOther.getRecherchesAvecResultats()!=null && this.getRecherchesAvecResultats().equals(castOther.getRecherchesAvecResultats()) ) )
 && ( (this.getTauxClicPct()==castOther.getTauxClicPct()) || ( this.getTauxClicPct()!=null && castOther.getTauxClicPct()!=null && this.getTauxClicPct().equals(castOther.getTauxClicPct()) ) )
 && ( (this.getTypeRecherche()==castOther.getTypeRecherche()) || ( this.getTypeRecherche()!=null && castOther.getTypeRecherche()!=null && this.getTypeRecherche().equals(castOther.getTypeRecherche()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getDateRecherche() == null ? 0 : this.getDateRecherche().hashCode() );
        result = 37 * result + ( getLangueRecherche() == null ? 0 : this.getLangueRecherche().hashCode() );
        result = 37 * result + ( getNombreRecherches() == null ? 0 : this.getNombreRecherches().hashCode() );
        result = 37 * result + ( getRecherchesAvecClic() == null ? 0 : this.getRecherchesAvecClic().hashCode() );
        result = 37 * result + ( getRecherchesAvecResultats() == null ? 0 : this.getRecherchesAvecResultats().hashCode() );
        result = 37 * result + ( getTauxClicPct() == null ? 0 : this.getTauxClicPct().hashCode() );
        result = 37 * result + ( getTypeRecherche() == null ? 0 : this.getTypeRecherche().hashCode() );
         return result;
   }   


}


