package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final



/**
 * VUtilisateursComplets generated by hbm2java
 */
public class VUtilisateursComplets  implements java.io.Serializable {


     private VUtilisateursCompletsId id;

    public VUtilisateursComplets() {
    }

    public VUtilisateursComplets(VUtilisateursCompletsId id) {
       this.id = id;
    }
   
    public VUtilisateursCompletsId getId() {
        return this.id;
    }
    
    public void setId(VUtilisateursCompletsId id) {
        this.id = id;
    }




}


