package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.io.Serializable;
import java.sql.Timestamp;

/**
 * VUtilisateursCompletsId generated by hbm2java
 */
public class VUtilisateursCompletsId  implements java.io.Serializable {


     private Boolean compteActif;
     private Boolean connexionGoogle;
     private Timestamp derniereConnexionLe;
     private String email;
     private Boolean estVerifie;
     private Integer id;
     private String nomComplet;
     private String nomUtilisateur;
     private Integer paysId;
     private String paysNom;
     private String profilNom;
     private String telephone;
     private Serializable uuid;

    public VUtilisateursCompletsId() {
    }

    public VUtilisateursCompletsId(Boolean compteActif, Boolean connexionGoogle, Timestamp derniereConnexionLe, String email, Boolean estVerifie, Integer id, String nomComplet, String nomUtilisateur, Integer paysId, String paysNom, String profilNom, String telephone, Serializable uuid) {
       this.compteActif = compteActif;
       this.connexionGoogle = connexionGoogle;
       this.derniereConnexionLe = derniereConnexionLe;
       this.email = email;
       this.estVerifie = estVerifie;
       this.id = id;
       this.nomComplet = nomComplet;
       this.nomUtilisateur = nomUtilisateur;
       this.paysId = paysId;
       this.paysNom = paysNom;
       this.profilNom = profilNom;
       this.telephone = telephone;
       this.uuid = uuid;
    }
   
    public Boolean getCompteActif() {
        return this.compteActif;
    }
    
    public void setCompteActif(Boolean compteActif) {
        this.compteActif = compteActif;
    }
    public Boolean getConnexionGoogle() {
        return this.connexionGoogle;
    }
    
    public void setConnexionGoogle(Boolean connexionGoogle) {
        this.connexionGoogle = connexionGoogle;
    }
    public Timestamp getDerniereConnexionLe() {
        return this.derniereConnexionLe;
    }
    
    public void setDerniereConnexionLe(Timestamp derniereConnexionLe) {
        this.derniereConnexionLe = derniereConnexionLe;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getEstVerifie() {
        return this.estVerifie;
    }
    
    public void setEstVerifie(Boolean estVerifie) {
        this.estVerifie = estVerifie;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomComplet() {
        return this.nomComplet;
    }
    
    public void setNomComplet(String nomComplet) {
        this.nomComplet = nomComplet;
    }
    public String getNomUtilisateur() {
        return this.nomUtilisateur;
    }
    
    public void setNomUtilisateur(String nomUtilisateur) {
        this.nomUtilisateur = nomUtilisateur;
    }
    public Integer getPaysId() {
        return this.paysId;
    }
    
    public void setPaysId(Integer paysId) {
        this.paysId = paysId;
    }
    public String getPaysNom() {
        return this.paysNom;
    }
    
    public void setPaysNom(String paysNom) {
        this.paysNom = paysNom;
    }
    public String getProfilNom() {
        return this.profilNom;
    }
    
    public void setProfilNom(String profilNom) {
        this.profilNom = profilNom;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public Serializable getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Serializable uuid) {
        this.uuid = uuid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VUtilisateursCompletsId) ) return false;
		 VUtilisateursCompletsId castOther = ( VUtilisateursCompletsId ) other; 
         
		 return ( (this.getCompteActif()==castOther.getCompteActif()) || ( this.getCompteActif()!=null && castOther.getCompteActif()!=null && this.getCompteActif().equals(castOther.getCompteActif()) ) )
 && ( (this.getConnexionGoogle()==castOther.getConnexionGoogle()) || ( this.getConnexionGoogle()!=null && castOther.getConnexionGoogle()!=null && this.getConnexionGoogle().equals(castOther.getConnexionGoogle()) ) )
 && ( (this.getDerniereConnexionLe()==castOther.getDerniereConnexionLe()) || ( this.getDerniereConnexionLe()!=null && castOther.getDerniereConnexionLe()!=null && this.getDerniereConnexionLe().equals(castOther.getDerniereConnexionLe()) ) )
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getEstVerifie()==castOther.getEstVerifie()) || ( this.getEstVerifie()!=null && castOther.getEstVerifie()!=null && this.getEstVerifie().equals(castOther.getEstVerifie()) ) )
 && ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getNomComplet()==castOther.getNomComplet()) || ( this.getNomComplet()!=null && castOther.getNomComplet()!=null && this.getNomComplet().equals(castOther.getNomComplet()) ) )
 && ( (this.getNomUtilisateur()==castOther.getNomUtilisateur()) || ( this.getNomUtilisateur()!=null && castOther.getNomUtilisateur()!=null && this.getNomUtilisateur().equals(castOther.getNomUtilisateur()) ) )
 && ( (this.getPaysId()==castOther.getPaysId()) || ( this.getPaysId()!=null && castOther.getPaysId()!=null && this.getPaysId().equals(castOther.getPaysId()) ) )
 && ( (this.getPaysNom()==castOther.getPaysNom()) || ( this.getPaysNom()!=null && castOther.getPaysNom()!=null && this.getPaysNom().equals(castOther.getPaysNom()) ) )
 && ( (this.getProfilNom()==castOther.getProfilNom()) || ( this.getProfilNom()!=null && castOther.getProfilNom()!=null && this.getProfilNom().equals(castOther.getProfilNom()) ) )
 && ( (this.getTelephone()==castOther.getTelephone()) || ( this.getTelephone()!=null && castOther.getTelephone()!=null && this.getTelephone().equals(castOther.getTelephone()) ) )
 && ( (this.getUuid()==castOther.getUuid()) || ( this.getUuid()!=null && castOther.getUuid()!=null && this.getUuid().equals(castOther.getUuid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getCompteActif() == null ? 0 : this.getCompteActif().hashCode() );
        result = 37 * result + ( getConnexionGoogle() == null ? 0 : this.getConnexionGoogle().hashCode() );
        result = 37 * result + ( getDerniereConnexionLe() == null ? 0 : this.getDerniereConnexionLe().hashCode() );
        result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
        result = 37 * result + ( getEstVerifie() == null ? 0 : this.getEstVerifie().hashCode() );
        result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
        result = 37 * result + ( getNomComplet() == null ? 0 : this.getNomComplet().hashCode() );
        result = 37 * result + ( getNomUtilisateur() == null ? 0 : this.getNomUtilisateur().hashCode() );
        result = 37 * result + ( getPaysId() == null ? 0 : this.getPaysId().hashCode() );
        result = 37 * result + ( getPaysNom() == null ? 0 : this.getPaysNom().hashCode() );
        result = 37 * result + ( getProfilNom() == null ? 0 : this.getProfilNom().hashCode() );
        result = 37 * result + ( getTelephone() == null ? 0 : this.getTelephone().hashCode() );
        result = 37 * result + ( getUuid() == null ? 0 : this.getUuid().hashCode() );
         return result;
   }   


}


