package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.sql.Timestamp;

/**
 * VVentesBoutiquesId generated by hbm2java
 */
public class VVentesBoutiquesId  implements java.io.Serializable {


     private Integer boutiqueId;
     private String boutiqueNom;
     private Byte chiffreAffaires;
     private Long clientsUniques;
     private Timestamp derniereVente;
     private Long nombreCommandes;
     private Byte panierMoyen;
     private String ville;

    public VVentesBoutiquesId() {
    }

    public VVentesBoutiquesId(Integer boutiqueId, String boutiqueNom, Byte chiffreAffaires, Long clientsUniques, Timestamp derniereVente, Long nombreCommandes, Byte panierMoyen, String ville) {
       this.boutiqueId = boutiqueId;
       this.boutiqueNom = boutiqueNom;
       this.chiffreAffaires = chiffreAffaires;
       this.clientsUniques = clientsUniques;
       this.derniereVente = derniereVente;
       this.nombreCommandes = nombreCommandes;
       this.panierMoyen = panierMoyen;
       this.ville = ville;
    }
   
    public Integer getBoutiqueId() {
        return this.boutiqueId;
    }
    
    public void setBoutiqueId(Integer boutiqueId) {
        this.boutiqueId = boutiqueId;
    }
    public String getBoutiqueNom() {
        return this.boutiqueNom;
    }
    
    public void setBoutiqueNom(String boutiqueNom) {
        this.boutiqueNom = boutiqueNom;
    }
    public Byte getChiffreAffaires() {
        return this.chiffreAffaires;
    }
    
    public void setChiffreAffaires(Byte chiffreAffaires) {
        this.chiffreAffaires = chiffreAffaires;
    }
    public Long getClientsUniques() {
        return this.clientsUniques;
    }
    
    public void setClientsUniques(Long clientsUniques) {
        this.clientsUniques = clientsUniques;
    }
    public Timestamp getDerniereVente() {
        return this.derniereVente;
    }
    
    public void setDerniereVente(Timestamp derniereVente) {
        this.derniereVente = derniereVente;
    }
    public Long getNombreCommandes() {
        return this.nombreCommandes;
    }
    
    public void setNombreCommandes(Long nombreCommandes) {
        this.nombreCommandes = nombreCommandes;
    }
    public Byte getPanierMoyen() {
        return this.panierMoyen;
    }
    
    public void setPanierMoyen(Byte panierMoyen) {
        this.panierMoyen = panierMoyen;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VVentesBoutiquesId) ) return false;
		 VVentesBoutiquesId castOther = ( VVentesBoutiquesId ) other; 
         
		 return ( (this.getBoutiqueId()==castOther.getBoutiqueId()) || ( this.getBoutiqueId()!=null && castOther.getBoutiqueId()!=null && this.getBoutiqueId().equals(castOther.getBoutiqueId()) ) )
 && ( (this.getBoutiqueNom()==castOther.getBoutiqueNom()) || ( this.getBoutiqueNom()!=null && castOther.getBoutiqueNom()!=null && this.getBoutiqueNom().equals(castOther.getBoutiqueNom()) ) )
 && ( (this.getChiffreAffaires()==castOther.getChiffreAffaires()) || ( this.getChiffreAffaires()!=null && castOther.getChiffreAffaires()!=null && this.getChiffreAffaires().equals(castOther.getChiffreAffaires()) ) )
 && ( (this.getClientsUniques()==castOther.getClientsUniques()) || ( this.getClientsUniques()!=null && castOther.getClientsUniques()!=null && this.getClientsUniques().equals(castOther.getClientsUniques()) ) )
 && ( (this.getDerniereVente()==castOther.getDerniereVente()) || ( this.getDerniereVente()!=null && castOther.getDerniereVente()!=null && this.getDerniereVente().equals(castOther.getDerniereVente()) ) )
 && ( (this.getNombreCommandes()==castOther.getNombreCommandes()) || ( this.getNombreCommandes()!=null && castOther.getNombreCommandes()!=null && this.getNombreCommandes().equals(castOther.getNombreCommandes()) ) )
 && ( (this.getPanierMoyen()==castOther.getPanierMoyen()) || ( this.getPanierMoyen()!=null && castOther.getPanierMoyen()!=null && this.getPanierMoyen().equals(castOther.getPanierMoyen()) ) )
 && ( (this.getVille()==castOther.getVille()) || ( this.getVille()!=null && castOther.getVille()!=null && this.getVille().equals(castOther.getVille()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + ( getBoutiqueId() == null ? 0 : this.getBoutiqueId().hashCode() );
        result = 37 * result + ( getBoutiqueNom() == null ? 0 : this.getBoutiqueNom().hashCode() );
        result = 37 * result + ( getChiffreAffaires() == null ? 0 : this.getChiffreAffaires().hashCode() );
        result = 37 * result + ( getClientsUniques() == null ? 0 : this.getClientsUniques().hashCode() );
        result = 37 * result + ( getDerniereVente() == null ? 0 : this.getDerniereVente().hashCode() );
        result = 37 * result + ( getNombreCommandes() == null ? 0 : this.getNombreCommandes().hashCode() );
        result = 37 * result + ( getPanierMoyen() == null ? 0 : this.getPanierMoyen().hashCode() );
        result = 37 * result + ( getVille() == null ? 0 : this.getVille().hashCode() );
         return result;
   }   


}


