package model;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final



/**
 * VVentesBoutiques generated by hbm2java
 */
public class VVentesBoutiques  implements java.io.Serializable {


     private VVentesBoutiquesId id;

    public VVentesBoutiques() {
    }

    public VVentesBoutiques(VVentesBoutiquesId id) {
       this.id = id;
    }
   
    public VVentesBoutiquesId getId() {
        return this.id;
    }
    
    public void setId(VVentesBoutiquesId id) {
        this.id = id;
    }




}


