package model.commande;
// Generated 1 juil. 2025, 15:15:57 by Hibernate Tools 6.5.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * StatutsCommande generated by hbm2java
 */
public class StatutsCommande  implements java.io.Serializable {


     private int id;
     private String code;
     private String libelle;
     private String description;
     private String couleurHex;
     private Integer ordreWorkflow;
     private Boolean estFinal;
     private Boolean estActif;
     private Set historiqueStatutsCommandesForAncienStatutId = new HashSet(0);
     private Set historiqueStatutsCommandesForNouveauStatutId = new HashSet(0);
     private Set commandeses = new HashSet(0);

    public StatutsCommande() {
    }

	
    public StatutsCommande(int id, String code, String libelle) {
        this.id = id;
        this.code = code;
        this.libelle = libelle;
    }
    public StatutsCommande(int id, String code, String libelle, String description, String couleurHex, Integer ordreWorkflow, Boolean estFinal, Boolean estActif, Set historiqueStatutsCommandesForAncienStatutId, Set historiqueStatutsCommandesForNouveauStatutId, Set commandeses) {
       this.id = id;
       this.code = code;
       this.libelle = libelle;
       this.description = description;
       this.couleurHex = couleurHex;
       this.ordreWorkflow = ordreWorkflow;
       this.estFinal = estFinal;
       this.estActif = estActif;
       this.historiqueStatutsCommandesForAncienStatutId = historiqueStatutsCommandesForAncienStatutId;
       this.historiqueStatutsCommandesForNouveauStatutId = historiqueStatutsCommandesForNouveauStatutId;
       this.commandeses = commandeses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getCouleurHex() {
        return this.couleurHex;
    }
    
    public void setCouleurHex(String couleurHex) {
        this.couleurHex = couleurHex;
    }
    public Integer getOrdreWorkflow() {
        return this.ordreWorkflow;
    }
    
    public void setOrdreWorkflow(Integer ordreWorkflow) {
        this.ordreWorkflow = ordreWorkflow;
    }
    public Boolean getEstFinal() {
        return this.estFinal;
    }
    
    public void setEstFinal(Boolean estFinal) {
        this.estFinal = estFinal;
    }
    public Boolean getEstActif() {
        return this.estActif;
    }
    
    public void setEstActif(Boolean estActif) {
        this.estActif = estActif;
    }
    public Set getHistoriqueStatutsCommandesForAncienStatutId() {
        return this.historiqueStatutsCommandesForAncienStatutId;
    }
    
    public void setHistoriqueStatutsCommandesForAncienStatutId(Set historiqueStatutsCommandesForAncienStatutId) {
        this.historiqueStatutsCommandesForAncienStatutId = historiqueStatutsCommandesForAncienStatutId;
    }
    public Set getHistoriqueStatutsCommandesForNouveauStatutId() {
        return this.historiqueStatutsCommandesForNouveauStatutId;
    }
    
    public void setHistoriqueStatutsCommandesForNouveauStatutId(Set historiqueStatutsCommandesForNouveauStatutId) {
        this.historiqueStatutsCommandesForNouveauStatutId = historiqueStatutsCommandesForNouveauStatutId;
    }
    public Set getCommandeses() {
        return this.commandeses;
    }
    
    public void setCommandeses(Set commandeses) {
        this.commandeses = commandeses;
    }




}


